// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: api/reference/v1/reference.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationReferenceGetLoanProduct = "/api.reference.v1.Reference/GetLoanProduct"
const OperationReferenceListApplicationStatuses = "/api.reference.v1.Reference/ListApplicationStatuses"
const OperationReferenceListBranches = "/api.reference.v1.Reference/ListBranches"
const OperationReferenceListFinancialGLAccounts = "/api.reference.v1.Reference/ListFinancialGLAccounts"
const OperationReferenceListLoanOfficers = "/api.reference.v1.Reference/ListLoanOfficers"
const OperationReferenceListLoanProducts = "/api.reference.v1.Reference/ListLoanProducts"

type ReferenceHTTPServer interface {
	GetLoanProduct(context.Context, *GetLoanProductRequest) (*LoanProduct, error)
	ListApplicationStatuses(context.Context, *ListApplicationStatusesRequest) (*ListApplicationStatusesReply, error)
	ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesReply, error)
	ListFinancialGLAccounts(context.Context, *ListFinancialGLAccountsRequest) (*ListFinancialGLAccountsReply, error)
	ListLoanOfficers(context.Context, *ListLoanOfficersRequest) (*ListLoanOfficersReply, error)
	ListLoanProducts(context.Context, *ListLoanProductsRequest) (*ListLoanProductsReply, error)
}

func RegisterReferenceHTTPServer(s *http.Server, srv ReferenceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/reference/loan-products", _Reference_ListLoanProducts0_HTTP_Handler(srv))
	r.GET("/v1/reference/loan-products/{id}", _Reference_GetLoanProduct0_HTTP_Handler(srv))
	r.GET("/v1/reference/branches", _Reference_ListBranches0_HTTP_Handler(srv))
	r.GET("/v1/reference/branches/{branch_code}/officers", _Reference_ListLoanOfficers0_HTTP_Handler(srv))
	r.GET("/v1/reference/application-statuses", _Reference_ListApplicationStatuses0_HTTP_Handler(srv))
	r.GET("/v1/reference/gl-accounts", _Reference_ListFinancialGLAccounts0_HTTP_Handler(srv))
}

func _Reference_ListLoanProducts0_HTTP_Handler(srv ReferenceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLoanProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceListLoanProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLoanProducts(ctx, req.(*ListLoanProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLoanProductsReply)
		return ctx.Result(200, reply)
	}
}

func _Reference_GetLoanProduct0_HTTP_Handler(srv ReferenceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLoanProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceGetLoanProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLoanProduct(ctx, req.(*GetLoanProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoanProduct)
		return ctx.Result(200, reply)
	}
}

func _Reference_ListBranches0_HTTP_Handler(srv ReferenceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBranchesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceListBranches)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBranches(ctx, req.(*ListBranchesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBranchesReply)
		return ctx.Result(200, reply)
	}
}

func _Reference_ListLoanOfficers0_HTTP_Handler(srv ReferenceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLoanOfficersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceListLoanOfficers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLoanOfficers(ctx, req.(*ListLoanOfficersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLoanOfficersReply)
		return ctx.Result(200, reply)
	}
}

func _Reference_ListApplicationStatuses0_HTTP_Handler(srv ReferenceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListApplicationStatusesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceListApplicationStatuses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListApplicationStatuses(ctx, req.(*ListApplicationStatusesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApplicationStatusesReply)
		return ctx.Result(200, reply)
	}
}

func _Reference_ListFinancialGLAccounts0_HTTP_Handler(srv ReferenceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFinancialGLAccountsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceListFinancialGLAccounts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFinancialGLAccounts(ctx, req.(*ListFinancialGLAccountsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFinancialGLAccountsReply)
		return ctx.Result(200, reply)
	}
}

type ReferenceHTTPClient interface {
	GetLoanProduct(ctx context.Context, req *GetLoanProductRequest, opts ...http.CallOption) (rsp *LoanProduct, err error)
	ListApplicationStatuses(ctx context.Context, req *ListApplicationStatusesRequest, opts ...http.CallOption) (rsp *ListApplicationStatusesReply, err error)
	ListBranches(ctx context.Context, req *ListBranchesRequest, opts ...http.CallOption) (rsp *ListBranchesReply, err error)
	ListFinancialGLAccounts(ctx context.Context, req *ListFinancialGLAccountsRequest, opts ...http.CallOption) (rsp *ListFinancialGLAccountsReply, err error)
	ListLoanOfficers(ctx context.Context, req *ListLoanOfficersRequest, opts ...http.CallOption) (rsp *ListLoanOfficersReply, err error)
	ListLoanProducts(ctx context.Context, req *ListLoanProductsRequest, opts ...http.CallOption) (rsp *ListLoanProductsReply, err error)
}

type ReferenceHTTPClientImpl struct {
	cc *http.Client
}

func NewReferenceHTTPClient(client *http.Client) ReferenceHTTPClient {
	return &ReferenceHTTPClientImpl{client}
}

func (c *ReferenceHTTPClientImpl) GetLoanProduct(ctx context.Context, in *GetLoanProductRequest, opts ...http.CallOption) (*LoanProduct, error) {
	var out LoanProduct
	pattern := "/v1/reference/loan-products/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceGetLoanProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceHTTPClientImpl) ListApplicationStatuses(ctx context.Context, in *ListApplicationStatusesRequest, opts ...http.CallOption) (*ListApplicationStatusesReply, error) {
	var out ListApplicationStatusesReply
	pattern := "/v1/reference/application-statuses"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceListApplicationStatuses))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceHTTPClientImpl) ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...http.CallOption) (*ListBranchesReply, error) {
	var out ListBranchesReply
	pattern := "/v1/reference/branches"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceListBranches))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceHTTPClientImpl) ListFinancialGLAccounts(ctx context.Context, in *ListFinancialGLAccountsRequest, opts ...http.CallOption) (*ListFinancialGLAccountsReply, error) {
	var out ListFinancialGLAccountsReply
	pattern := "/v1/reference/gl-accounts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceListFinancialGLAccounts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceHTTPClientImpl) ListLoanOfficers(ctx context.Context, in *ListLoanOfficersRequest, opts ...http.CallOption) (*ListLoanOfficersReply, error) {
	var out ListLoanOfficersReply
	pattern := "/v1/reference/branches/{branch_code}/officers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceListLoanOfficers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceHTTPClientImpl) ListLoanProducts(ctx context.Context, in *ListLoanProductsRequest, opts ...http.CallOption) (*ListLoanProductsReply, error) {
	var out ListLoanProductsReply
	pattern := "/v1/reference/loan-products"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceListLoanProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
