// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/reference/v1/reference.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reference_ListLoanProducts_FullMethodName        = "/api.reference.v1.Reference/ListLoanProducts"
	Reference_GetLoanProduct_FullMethodName          = "/api.reference.v1.Reference/GetLoanProduct"
	Reference_ListBranches_FullMethodName            = "/api.reference.v1.Reference/ListBranches"
	Reference_ListLoanOfficers_FullMethodName        = "/api.reference.v1.Reference/ListLoanOfficers"
	Reference_ListApplicationStatuses_FullMethodName = "/api.reference.v1.Reference/ListApplicationStatuses"
	Reference_ListFinancialGLAccounts_FullMethodName = "/api.reference.v1.Reference/ListFinancialGLAccounts"
)

// ReferenceClient is the client API for Reference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReferenceClient interface {
	ListLoanProducts(ctx context.Context, in *ListLoanProductsRequest, opts ...grpc.CallOption) (*ListLoanProductsReply, error)
	GetLoanProduct(ctx context.Context, in *GetLoanProductRequest, opts ...grpc.CallOption) (*LoanProduct, error)
	ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesReply, error)
	ListLoanOfficers(ctx context.Context, in *ListLoanOfficersRequest, opts ...grpc.CallOption) (*ListLoanOfficersReply, error)
	ListApplicationStatuses(ctx context.Context, in *ListApplicationStatusesRequest, opts ...grpc.CallOption) (*ListApplicationStatusesReply, error)
	ListFinancialGLAccounts(ctx context.Context, in *ListFinancialGLAccountsRequest, opts ...grpc.CallOption) (*ListFinancialGLAccountsReply, error)
}

type referenceClient struct {
	cc grpc.ClientConnInterface
}

func NewReferenceClient(cc grpc.ClientConnInterface) ReferenceClient {
	return &referenceClient{cc}
}

func (c *referenceClient) ListLoanProducts(ctx context.Context, in *ListLoanProductsRequest, opts ...grpc.CallOption) (*ListLoanProductsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoanProductsReply)
	err := c.cc.Invoke(ctx, Reference_ListLoanProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceClient) GetLoanProduct(ctx context.Context, in *GetLoanProductRequest, opts ...grpc.CallOption) (*LoanProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanProduct)
	err := c.cc.Invoke(ctx, Reference_GetLoanProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceClient) ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBranchesReply)
	err := c.cc.Invoke(ctx, Reference_ListBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceClient) ListLoanOfficers(ctx context.Context, in *ListLoanOfficersRequest, opts ...grpc.CallOption) (*ListLoanOfficersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoanOfficersReply)
	err := c.cc.Invoke(ctx, Reference_ListLoanOfficers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceClient) ListApplicationStatuses(ctx context.Context, in *ListApplicationStatusesRequest, opts ...grpc.CallOption) (*ListApplicationStatusesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApplicationStatusesReply)
	err := c.cc.Invoke(ctx, Reference_ListApplicationStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceClient) ListFinancialGLAccounts(ctx context.Context, in *ListFinancialGLAccountsRequest, opts ...grpc.CallOption) (*ListFinancialGLAccountsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFinancialGLAccountsReply)
	err := c.cc.Invoke(ctx, Reference_ListFinancialGLAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReferenceServer is the server API for Reference service.
// All implementations must embed UnimplementedReferenceServer
// for forward compatibility.
type ReferenceServer interface {
	ListLoanProducts(context.Context, *ListLoanProductsRequest) (*ListLoanProductsReply, error)
	GetLoanProduct(context.Context, *GetLoanProductRequest) (*LoanProduct, error)
	ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesReply, error)
	ListLoanOfficers(context.Context, *ListLoanOfficersRequest) (*ListLoanOfficersReply, error)
	ListApplicationStatuses(context.Context, *ListApplicationStatusesRequest) (*ListApplicationStatusesReply, error)
	ListFinancialGLAccounts(context.Context, *ListFinancialGLAccountsRequest) (*ListFinancialGLAccountsReply, error)
	mustEmbedUnimplementedReferenceServer()
}

// UnimplementedReferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReferenceServer struct{}

func (UnimplementedReferenceServer) ListLoanProducts(context.Context, *ListLoanProductsRequest) (*ListLoanProductsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLoanProducts not implemented")
}
func (UnimplementedReferenceServer) GetLoanProduct(context.Context, *GetLoanProductRequest) (*LoanProduct, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoanProduct not implemented")
}
func (UnimplementedReferenceServer) ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBranches not implemented")
}
func (UnimplementedReferenceServer) ListLoanOfficers(context.Context, *ListLoanOfficersRequest) (*ListLoanOfficersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLoanOfficers not implemented")
}
func (UnimplementedReferenceServer) ListApplicationStatuses(context.Context, *ListApplicationStatusesRequest) (*ListApplicationStatusesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplicationStatuses not implemented")
}
func (UnimplementedReferenceServer) ListFinancialGLAccounts(context.Context, *ListFinancialGLAccountsRequest) (*ListFinancialGLAccountsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFinancialGLAccounts not implemented")
}
func (UnimplementedReferenceServer) mustEmbedUnimplementedReferenceServer() {}
func (UnimplementedReferenceServer) testEmbeddedByValue()                   {}

// UnsafeReferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReferenceServer will
// result in compilation errors.
type UnsafeReferenceServer interface {
	mustEmbedUnimplementedReferenceServer()
}

func RegisterReferenceServer(s grpc.ServiceRegistrar, srv ReferenceServer) {
	// If the following call panics, it indicates UnimplementedReferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reference_ServiceDesc, srv)
}

func _Reference_ListLoanProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoanProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceServer).ListLoanProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reference_ListLoanProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceServer).ListLoanProducts(ctx, req.(*ListLoanProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reference_GetLoanProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoanProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceServer).GetLoanProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reference_GetLoanProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceServer).GetLoanProduct(ctx, req.(*GetLoanProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reference_ListBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceServer).ListBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reference_ListBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceServer).ListBranches(ctx, req.(*ListBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reference_ListLoanOfficers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoanOfficersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceServer).ListLoanOfficers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reference_ListLoanOfficers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceServer).ListLoanOfficers(ctx, req.(*ListLoanOfficersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reference_ListApplicationStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceServer).ListApplicationStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reference_ListApplicationStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceServer).ListApplicationStatuses(ctx, req.(*ListApplicationStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reference_ListFinancialGLAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFinancialGLAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceServer).ListFinancialGLAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reference_ListFinancialGLAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceServer).ListFinancialGLAccounts(ctx, req.(*ListFinancialGLAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reference_ServiceDesc is the grpc.ServiceDesc for Reference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.reference.v1.Reference",
	HandlerType: (*ReferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLoanProducts",
			Handler:    _Reference_ListLoanProducts_Handler,
		},
		{
			MethodName: "GetLoanProduct",
			Handler:    _Reference_GetLoanProduct_Handler,
		},
		{
			MethodName: "ListBranches",
			Handler:    _Reference_ListBranches_Handler,
		},
		{
			MethodName: "ListLoanOfficers",
			Handler:    _Reference_ListLoanOfficers_Handler,
		},
		{
			MethodName: "ListApplicationStatuses",
			Handler:    _Reference_ListApplicationStatuses_Handler,
		},
		{
			MethodName: "ListFinancialGLAccounts",
			Handler:    _Reference_ListFinancialGLAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/reference/v1/reference.proto",
}
