// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: survey/v1/survey.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSurveyServiceAssignSurvey = "/api.survey.v1.SurveyService/AssignSurvey"
const OperationSurveyServiceCreateSurveyTemplate = "/api.survey.v1.SurveyService/CreateSurveyTemplate"
const OperationSurveyServiceGetSurvey = "/api.survey.v1.SurveyService/GetSurvey"
const OperationSurveyServiceListSurveyTemplates = "/api.survey.v1.SurveyService/ListSurveyTemplates"
const OperationSurveyServiceListSurveys = "/api.survey.v1.SurveyService/ListSurveys"
const OperationSurveyServiceListSurveysByApplication = "/api.survey.v1.SurveyService/ListSurveysByApplication"
const OperationSurveyServiceStartSurvey = "/api.survey.v1.SurveyService/StartSurvey"
const OperationSurveyServiceSubmitSurvey = "/api.survey.v1.SurveyService/SubmitSurvey"
const OperationSurveyServiceSubmitSurveyAnswer = "/api.survey.v1.SurveyService/SubmitSurveyAnswer"
const OperationSurveyServiceUploadSurveyEvidence = "/api.survey.v1.SurveyService/UploadSurveyEvidence"
const OperationSurveyServiceVerifySurvey = "/api.survey.v1.SurveyService/VerifySurvey"

type SurveyServiceHTTPServer interface {
	// AssignSurvey ===== ASSIGN & GET =====
	AssignSurvey(context.Context, *AssignSurveyRequest) (*ApplicationSurvey, error)
	CreateSurveyTemplate(context.Context, *CreateSurveyTemplateRequest) (*SurveyTemplate, error)
	GetSurvey(context.Context, *GetSurveyRequest) (*ApplicationSurvey, error)
	// ListSurveyTemplates ===== TEMPLATES (Optional Admin/Setup) =====
	ListSurveyTemplates(context.Context, *ListSurveyTemplatesRequest) (*ListSurveyTemplatesResponse, error)
	// ListSurveys ===== GLOBAL LIST (Mobile App / Backend Filter) =====
	ListSurveys(context.Context, *ListSurveysRequest) (*ListSurveysResponse, error)
	// ListSurveysByApplication ===== LIST BY APPLICATION =====
	ListSurveysByApplication(context.Context, *ListSurveysByApplicationRequest) (*ListSurveysByApplicationResponse, error)
	// StartSurvey ===== WORKFLOW =====
	StartSurvey(context.Context, *StartSurveyRequest) (*ApplicationSurvey, error)
	SubmitSurvey(context.Context, *SubmitSurveyRequest) (*ApplicationSurvey, error)
	// SubmitSurveyAnswer ===== ANSWERS & EVIDENCE =====
	SubmitSurveyAnswer(context.Context, *SubmitSurveyAnswerRequest) (*SurveyAnswer, error)
	UploadSurveyEvidence(context.Context, *UploadSurveyEvidenceRequest) (*SurveyEvidence, error)
	VerifySurvey(context.Context, *VerifySurveyRequest) (*ApplicationSurvey, error)
}

func RegisterSurveyServiceHTTPServer(s *http.Server, srv SurveyServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/applications/{application_id}/surveys", _SurveyService_AssignSurvey0_HTTP_Handler(srv))
	r.GET("/v1/surveys/{id}", _SurveyService_GetSurvey0_HTTP_Handler(srv))
	r.GET("/v1/applications/{application_id}/surveys", _SurveyService_ListSurveysByApplication0_HTTP_Handler(srv))
	r.GET("/v1/surveys", _SurveyService_ListSurveys0_HTTP_Handler(srv))
	r.PUT("/v1/surveys/{id}/start", _SurveyService_StartSurvey0_HTTP_Handler(srv))
	r.PUT("/v1/surveys/{id}/submit", _SurveyService_SubmitSurvey0_HTTP_Handler(srv))
	r.PUT("/v1/surveys/{id}/verify", _SurveyService_VerifySurvey0_HTTP_Handler(srv))
	r.POST("/v1/surveys/{survey_id}/answers", _SurveyService_SubmitSurveyAnswer0_HTTP_Handler(srv))
	r.POST("/v1/surveys/{survey_id}/evidences", _SurveyService_UploadSurveyEvidence0_HTTP_Handler(srv))
	r.GET("/v1/survey-templates", _SurveyService_ListSurveyTemplates0_HTTP_Handler(srv))
	r.POST("/v1/survey-templates", _SurveyService_CreateSurveyTemplate0_HTTP_Handler(srv))
}

func _SurveyService_AssignSurvey0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignSurveyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceAssignSurvey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignSurvey(ctx, req.(*AssignSurveyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationSurvey)
		return ctx.Result(200, reply)
	}
}

func _SurveyService_GetSurvey0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSurveyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceGetSurvey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSurvey(ctx, req.(*GetSurveyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationSurvey)
		return ctx.Result(200, reply)
	}
}

func _SurveyService_ListSurveysByApplication0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSurveysByApplicationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceListSurveysByApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSurveysByApplication(ctx, req.(*ListSurveysByApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSurveysByApplicationResponse)
		return ctx.Result(200, reply)
	}
}

func _SurveyService_ListSurveys0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSurveysRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceListSurveys)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSurveys(ctx, req.(*ListSurveysRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSurveysResponse)
		return ctx.Result(200, reply)
	}
}

func _SurveyService_StartSurvey0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartSurveyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceStartSurvey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartSurvey(ctx, req.(*StartSurveyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationSurvey)
		return ctx.Result(200, reply)
	}
}

func _SurveyService_SubmitSurvey0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitSurveyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceSubmitSurvey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitSurvey(ctx, req.(*SubmitSurveyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationSurvey)
		return ctx.Result(200, reply)
	}
}

func _SurveyService_VerifySurvey0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in VerifySurveyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceVerifySurvey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.VerifySurvey(ctx, req.(*VerifySurveyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationSurvey)
		return ctx.Result(200, reply)
	}
}

func _SurveyService_SubmitSurveyAnswer0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitSurveyAnswerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceSubmitSurveyAnswer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitSurveyAnswer(ctx, req.(*SubmitSurveyAnswerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SurveyAnswer)
		return ctx.Result(200, reply)
	}
}

func _SurveyService_UploadSurveyEvidence0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadSurveyEvidenceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceUploadSurveyEvidence)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadSurveyEvidence(ctx, req.(*UploadSurveyEvidenceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SurveyEvidence)
		return ctx.Result(200, reply)
	}
}

func _SurveyService_ListSurveyTemplates0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSurveyTemplatesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceListSurveyTemplates)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSurveyTemplates(ctx, req.(*ListSurveyTemplatesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSurveyTemplatesResponse)
		return ctx.Result(200, reply)
	}
}

func _SurveyService_CreateSurveyTemplate0_HTTP_Handler(srv SurveyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSurveyTemplateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSurveyServiceCreateSurveyTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSurveyTemplate(ctx, req.(*CreateSurveyTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SurveyTemplate)
		return ctx.Result(200, reply)
	}
}

type SurveyServiceHTTPClient interface {
	// AssignSurvey ===== ASSIGN & GET =====
	AssignSurvey(ctx context.Context, req *AssignSurveyRequest, opts ...http.CallOption) (rsp *ApplicationSurvey, err error)
	CreateSurveyTemplate(ctx context.Context, req *CreateSurveyTemplateRequest, opts ...http.CallOption) (rsp *SurveyTemplate, err error)
	GetSurvey(ctx context.Context, req *GetSurveyRequest, opts ...http.CallOption) (rsp *ApplicationSurvey, err error)
	// ListSurveyTemplates ===== TEMPLATES (Optional Admin/Setup) =====
	ListSurveyTemplates(ctx context.Context, req *ListSurveyTemplatesRequest, opts ...http.CallOption) (rsp *ListSurveyTemplatesResponse, err error)
	// ListSurveys ===== GLOBAL LIST (Mobile App / Backend Filter) =====
	ListSurveys(ctx context.Context, req *ListSurveysRequest, opts ...http.CallOption) (rsp *ListSurveysResponse, err error)
	// ListSurveysByApplication ===== LIST BY APPLICATION =====
	ListSurveysByApplication(ctx context.Context, req *ListSurveysByApplicationRequest, opts ...http.CallOption) (rsp *ListSurveysByApplicationResponse, err error)
	// StartSurvey ===== WORKFLOW =====
	StartSurvey(ctx context.Context, req *StartSurveyRequest, opts ...http.CallOption) (rsp *ApplicationSurvey, err error)
	SubmitSurvey(ctx context.Context, req *SubmitSurveyRequest, opts ...http.CallOption) (rsp *ApplicationSurvey, err error)
	// SubmitSurveyAnswer ===== ANSWERS & EVIDENCE =====
	SubmitSurveyAnswer(ctx context.Context, req *SubmitSurveyAnswerRequest, opts ...http.CallOption) (rsp *SurveyAnswer, err error)
	UploadSurveyEvidence(ctx context.Context, req *UploadSurveyEvidenceRequest, opts ...http.CallOption) (rsp *SurveyEvidence, err error)
	VerifySurvey(ctx context.Context, req *VerifySurveyRequest, opts ...http.CallOption) (rsp *ApplicationSurvey, err error)
}

type SurveyServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSurveyServiceHTTPClient(client *http.Client) SurveyServiceHTTPClient {
	return &SurveyServiceHTTPClientImpl{client}
}

// AssignSurvey ===== ASSIGN & GET =====
func (c *SurveyServiceHTTPClientImpl) AssignSurvey(ctx context.Context, in *AssignSurveyRequest, opts ...http.CallOption) (*ApplicationSurvey, error) {
	var out ApplicationSurvey
	pattern := "/v1/applications/{application_id}/surveys"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSurveyServiceAssignSurvey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SurveyServiceHTTPClientImpl) CreateSurveyTemplate(ctx context.Context, in *CreateSurveyTemplateRequest, opts ...http.CallOption) (*SurveyTemplate, error) {
	var out SurveyTemplate
	pattern := "/v1/survey-templates"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSurveyServiceCreateSurveyTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SurveyServiceHTTPClientImpl) GetSurvey(ctx context.Context, in *GetSurveyRequest, opts ...http.CallOption) (*ApplicationSurvey, error) {
	var out ApplicationSurvey
	pattern := "/v1/surveys/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSurveyServiceGetSurvey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSurveyTemplates ===== TEMPLATES (Optional Admin/Setup) =====
func (c *SurveyServiceHTTPClientImpl) ListSurveyTemplates(ctx context.Context, in *ListSurveyTemplatesRequest, opts ...http.CallOption) (*ListSurveyTemplatesResponse, error) {
	var out ListSurveyTemplatesResponse
	pattern := "/v1/survey-templates"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSurveyServiceListSurveyTemplates))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSurveys ===== GLOBAL LIST (Mobile App / Backend Filter) =====
func (c *SurveyServiceHTTPClientImpl) ListSurveys(ctx context.Context, in *ListSurveysRequest, opts ...http.CallOption) (*ListSurveysResponse, error) {
	var out ListSurveysResponse
	pattern := "/v1/surveys"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSurveyServiceListSurveys))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSurveysByApplication ===== LIST BY APPLICATION =====
func (c *SurveyServiceHTTPClientImpl) ListSurveysByApplication(ctx context.Context, in *ListSurveysByApplicationRequest, opts ...http.CallOption) (*ListSurveysByApplicationResponse, error) {
	var out ListSurveysByApplicationResponse
	pattern := "/v1/applications/{application_id}/surveys"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSurveyServiceListSurveysByApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartSurvey ===== WORKFLOW =====
func (c *SurveyServiceHTTPClientImpl) StartSurvey(ctx context.Context, in *StartSurveyRequest, opts ...http.CallOption) (*ApplicationSurvey, error) {
	var out ApplicationSurvey
	pattern := "/v1/surveys/{id}/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSurveyServiceStartSurvey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SurveyServiceHTTPClientImpl) SubmitSurvey(ctx context.Context, in *SubmitSurveyRequest, opts ...http.CallOption) (*ApplicationSurvey, error) {
	var out ApplicationSurvey
	pattern := "/v1/surveys/{id}/submit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSurveyServiceSubmitSurvey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitSurveyAnswer ===== ANSWERS & EVIDENCE =====
func (c *SurveyServiceHTTPClientImpl) SubmitSurveyAnswer(ctx context.Context, in *SubmitSurveyAnswerRequest, opts ...http.CallOption) (*SurveyAnswer, error) {
	var out SurveyAnswer
	pattern := "/v1/surveys/{survey_id}/answers"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSurveyServiceSubmitSurveyAnswer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SurveyServiceHTTPClientImpl) UploadSurveyEvidence(ctx context.Context, in *UploadSurveyEvidenceRequest, opts ...http.CallOption) (*SurveyEvidence, error) {
	var out SurveyEvidence
	pattern := "/v1/surveys/{survey_id}/evidences"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSurveyServiceUploadSurveyEvidence))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SurveyServiceHTTPClientImpl) VerifySurvey(ctx context.Context, in *VerifySurveyRequest, opts ...http.CallOption) (*ApplicationSurvey, error) {
	var out ApplicationSurvey
	pattern := "/v1/surveys/{id}/verify"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSurveyServiceVerifySurvey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
