// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: survey/v1/survey.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SurveyService_AssignSurvey_FullMethodName             = "/api.survey.v1.SurveyService/AssignSurvey"
	SurveyService_GetSurvey_FullMethodName                = "/api.survey.v1.SurveyService/GetSurvey"
	SurveyService_ListSurveysByApplication_FullMethodName = "/api.survey.v1.SurveyService/ListSurveysByApplication"
	SurveyService_ListSurveys_FullMethodName              = "/api.survey.v1.SurveyService/ListSurveys"
	SurveyService_StartSurvey_FullMethodName              = "/api.survey.v1.SurveyService/StartSurvey"
	SurveyService_SubmitSurvey_FullMethodName             = "/api.survey.v1.SurveyService/SubmitSurvey"
	SurveyService_VerifySurvey_FullMethodName             = "/api.survey.v1.SurveyService/VerifySurvey"
	SurveyService_SubmitSurveyAnswer_FullMethodName       = "/api.survey.v1.SurveyService/SubmitSurveyAnswer"
	SurveyService_UploadSurveyEvidence_FullMethodName     = "/api.survey.v1.SurveyService/UploadSurveyEvidence"
	SurveyService_ListSurveyTemplates_FullMethodName      = "/api.survey.v1.SurveyService/ListSurveyTemplates"
)

// SurveyServiceClient is the client API for SurveyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SurveyServiceClient interface {
	// ===== ASSIGN & GET =====
	AssignSurvey(ctx context.Context, in *AssignSurveyRequest, opts ...grpc.CallOption) (*ApplicationSurvey, error)
	GetSurvey(ctx context.Context, in *GetSurveyRequest, opts ...grpc.CallOption) (*ApplicationSurvey, error)
	// ===== LIST BY APPLICATION =====
	ListSurveysByApplication(ctx context.Context, in *ListSurveysByApplicationRequest, opts ...grpc.CallOption) (*ListSurveysByApplicationResponse, error)
	// ===== GLOBAL LIST (Mobile App / Backend Filter) =====
	ListSurveys(ctx context.Context, in *ListSurveysRequest, opts ...grpc.CallOption) (*ListSurveysResponse, error)
	// ===== WORKFLOW =====
	StartSurvey(ctx context.Context, in *StartSurveyRequest, opts ...grpc.CallOption) (*ApplicationSurvey, error)
	SubmitSurvey(ctx context.Context, in *SubmitSurveyRequest, opts ...grpc.CallOption) (*ApplicationSurvey, error)
	VerifySurvey(ctx context.Context, in *VerifySurveyRequest, opts ...grpc.CallOption) (*ApplicationSurvey, error)
	// ===== ANSWERS & EVIDENCE =====
	SubmitSurveyAnswer(ctx context.Context, in *SubmitSurveyAnswerRequest, opts ...grpc.CallOption) (*SurveyAnswer, error)
	UploadSurveyEvidence(ctx context.Context, in *UploadSurveyEvidenceRequest, opts ...grpc.CallOption) (*SurveyEvidence, error)
	// ===== TEMPLATES (Optional Admin/Setup) =====
	ListSurveyTemplates(ctx context.Context, in *ListSurveyTemplatesRequest, opts ...grpc.CallOption) (*ListSurveyTemplatesResponse, error)
}

type surveyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSurveyServiceClient(cc grpc.ClientConnInterface) SurveyServiceClient {
	return &surveyServiceClient{cc}
}

func (c *surveyServiceClient) AssignSurvey(ctx context.Context, in *AssignSurveyRequest, opts ...grpc.CallOption) (*ApplicationSurvey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationSurvey)
	err := c.cc.Invoke(ctx, SurveyService_AssignSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveyServiceClient) GetSurvey(ctx context.Context, in *GetSurveyRequest, opts ...grpc.CallOption) (*ApplicationSurvey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationSurvey)
	err := c.cc.Invoke(ctx, SurveyService_GetSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveyServiceClient) ListSurveysByApplication(ctx context.Context, in *ListSurveysByApplicationRequest, opts ...grpc.CallOption) (*ListSurveysByApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSurveysByApplicationResponse)
	err := c.cc.Invoke(ctx, SurveyService_ListSurveysByApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveyServiceClient) ListSurveys(ctx context.Context, in *ListSurveysRequest, opts ...grpc.CallOption) (*ListSurveysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSurveysResponse)
	err := c.cc.Invoke(ctx, SurveyService_ListSurveys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveyServiceClient) StartSurvey(ctx context.Context, in *StartSurveyRequest, opts ...grpc.CallOption) (*ApplicationSurvey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationSurvey)
	err := c.cc.Invoke(ctx, SurveyService_StartSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveyServiceClient) SubmitSurvey(ctx context.Context, in *SubmitSurveyRequest, opts ...grpc.CallOption) (*ApplicationSurvey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationSurvey)
	err := c.cc.Invoke(ctx, SurveyService_SubmitSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveyServiceClient) VerifySurvey(ctx context.Context, in *VerifySurveyRequest, opts ...grpc.CallOption) (*ApplicationSurvey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationSurvey)
	err := c.cc.Invoke(ctx, SurveyService_VerifySurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveyServiceClient) SubmitSurveyAnswer(ctx context.Context, in *SubmitSurveyAnswerRequest, opts ...grpc.CallOption) (*SurveyAnswer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurveyAnswer)
	err := c.cc.Invoke(ctx, SurveyService_SubmitSurveyAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveyServiceClient) UploadSurveyEvidence(ctx context.Context, in *UploadSurveyEvidenceRequest, opts ...grpc.CallOption) (*SurveyEvidence, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurveyEvidence)
	err := c.cc.Invoke(ctx, SurveyService_UploadSurveyEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveyServiceClient) ListSurveyTemplates(ctx context.Context, in *ListSurveyTemplatesRequest, opts ...grpc.CallOption) (*ListSurveyTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSurveyTemplatesResponse)
	err := c.cc.Invoke(ctx, SurveyService_ListSurveyTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SurveyServiceServer is the server API for SurveyService service.
// All implementations must embed UnimplementedSurveyServiceServer
// for forward compatibility.
type SurveyServiceServer interface {
	// ===== ASSIGN & GET =====
	AssignSurvey(context.Context, *AssignSurveyRequest) (*ApplicationSurvey, error)
	GetSurvey(context.Context, *GetSurveyRequest) (*ApplicationSurvey, error)
	// ===== LIST BY APPLICATION =====
	ListSurveysByApplication(context.Context, *ListSurveysByApplicationRequest) (*ListSurveysByApplicationResponse, error)
	// ===== GLOBAL LIST (Mobile App / Backend Filter) =====
	ListSurveys(context.Context, *ListSurveysRequest) (*ListSurveysResponse, error)
	// ===== WORKFLOW =====
	StartSurvey(context.Context, *StartSurveyRequest) (*ApplicationSurvey, error)
	SubmitSurvey(context.Context, *SubmitSurveyRequest) (*ApplicationSurvey, error)
	VerifySurvey(context.Context, *VerifySurveyRequest) (*ApplicationSurvey, error)
	// ===== ANSWERS & EVIDENCE =====
	SubmitSurveyAnswer(context.Context, *SubmitSurveyAnswerRequest) (*SurveyAnswer, error)
	UploadSurveyEvidence(context.Context, *UploadSurveyEvidenceRequest) (*SurveyEvidence, error)
	// ===== TEMPLATES (Optional Admin/Setup) =====
	ListSurveyTemplates(context.Context, *ListSurveyTemplatesRequest) (*ListSurveyTemplatesResponse, error)
	mustEmbedUnimplementedSurveyServiceServer()
}

// UnimplementedSurveyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSurveyServiceServer struct{}

func (UnimplementedSurveyServiceServer) AssignSurvey(context.Context, *AssignSurveyRequest) (*ApplicationSurvey, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignSurvey not implemented")
}
func (UnimplementedSurveyServiceServer) GetSurvey(context.Context, *GetSurveyRequest) (*ApplicationSurvey, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSurvey not implemented")
}
func (UnimplementedSurveyServiceServer) ListSurveysByApplication(context.Context, *ListSurveysByApplicationRequest) (*ListSurveysByApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSurveysByApplication not implemented")
}
func (UnimplementedSurveyServiceServer) ListSurveys(context.Context, *ListSurveysRequest) (*ListSurveysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSurveys not implemented")
}
func (UnimplementedSurveyServiceServer) StartSurvey(context.Context, *StartSurveyRequest) (*ApplicationSurvey, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSurvey not implemented")
}
func (UnimplementedSurveyServiceServer) SubmitSurvey(context.Context, *SubmitSurveyRequest) (*ApplicationSurvey, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSurvey not implemented")
}
func (UnimplementedSurveyServiceServer) VerifySurvey(context.Context, *VerifySurveyRequest) (*ApplicationSurvey, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySurvey not implemented")
}
func (UnimplementedSurveyServiceServer) SubmitSurveyAnswer(context.Context, *SubmitSurveyAnswerRequest) (*SurveyAnswer, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSurveyAnswer not implemented")
}
func (UnimplementedSurveyServiceServer) UploadSurveyEvidence(context.Context, *UploadSurveyEvidenceRequest) (*SurveyEvidence, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadSurveyEvidence not implemented")
}
func (UnimplementedSurveyServiceServer) ListSurveyTemplates(context.Context, *ListSurveyTemplatesRequest) (*ListSurveyTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSurveyTemplates not implemented")
}
func (UnimplementedSurveyServiceServer) mustEmbedUnimplementedSurveyServiceServer() {}
func (UnimplementedSurveyServiceServer) testEmbeddedByValue()                       {}

// UnsafeSurveyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SurveyServiceServer will
// result in compilation errors.
type UnsafeSurveyServiceServer interface {
	mustEmbedUnimplementedSurveyServiceServer()
}

func RegisterSurveyServiceServer(s grpc.ServiceRegistrar, srv SurveyServiceServer) {
	// If the following call panics, it indicates UnimplementedSurveyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SurveyService_ServiceDesc, srv)
}

func _SurveyService_AssignSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServiceServer).AssignSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurveyService_AssignSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServiceServer).AssignSurvey(ctx, req.(*AssignSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurveyService_GetSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServiceServer).GetSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurveyService_GetSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServiceServer).GetSurvey(ctx, req.(*GetSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurveyService_ListSurveysByApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSurveysByApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServiceServer).ListSurveysByApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurveyService_ListSurveysByApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServiceServer).ListSurveysByApplication(ctx, req.(*ListSurveysByApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurveyService_ListSurveys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSurveysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServiceServer).ListSurveys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurveyService_ListSurveys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServiceServer).ListSurveys(ctx, req.(*ListSurveysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurveyService_StartSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServiceServer).StartSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurveyService_StartSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServiceServer).StartSurvey(ctx, req.(*StartSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurveyService_SubmitSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServiceServer).SubmitSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurveyService_SubmitSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServiceServer).SubmitSurvey(ctx, req.(*SubmitSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurveyService_VerifySurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServiceServer).VerifySurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurveyService_VerifySurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServiceServer).VerifySurvey(ctx, req.(*VerifySurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurveyService_SubmitSurveyAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSurveyAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServiceServer).SubmitSurveyAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurveyService_SubmitSurveyAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServiceServer).SubmitSurveyAnswer(ctx, req.(*SubmitSurveyAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurveyService_UploadSurveyEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSurveyEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServiceServer).UploadSurveyEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurveyService_UploadSurveyEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServiceServer).UploadSurveyEvidence(ctx, req.(*UploadSurveyEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurveyService_ListSurveyTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSurveyTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveyServiceServer).ListSurveyTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurveyService_ListSurveyTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveyServiceServer).ListSurveyTemplates(ctx, req.(*ListSurveyTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SurveyService_ServiceDesc is the grpc.ServiceDesc for SurveyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SurveyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.survey.v1.SurveyService",
	HandlerType: (*SurveyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignSurvey",
			Handler:    _SurveyService_AssignSurvey_Handler,
		},
		{
			MethodName: "GetSurvey",
			Handler:    _SurveyService_GetSurvey_Handler,
		},
		{
			MethodName: "ListSurveysByApplication",
			Handler:    _SurveyService_ListSurveysByApplication_Handler,
		},
		{
			MethodName: "ListSurveys",
			Handler:    _SurveyService_ListSurveys_Handler,
		},
		{
			MethodName: "StartSurvey",
			Handler:    _SurveyService_StartSurvey_Handler,
		},
		{
			MethodName: "SubmitSurvey",
			Handler:    _SurveyService_SubmitSurvey_Handler,
		},
		{
			MethodName: "VerifySurvey",
			Handler:    _SurveyService_VerifySurvey_Handler,
		},
		{
			MethodName: "SubmitSurveyAnswer",
			Handler:    _SurveyService_SubmitSurveyAnswer_Handler,
		},
		{
			MethodName: "UploadSurveyEvidence",
			Handler:    _SurveyService_UploadSurveyEvidence_Handler,
		},
		{
			MethodName: "ListSurveyTemplates",
			Handler:    _SurveyService_ListSurveyTemplates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "survey/v1/survey.proto",
}
