// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"credit-analytics-backend/internal/biz"
	"credit-analytics-backend/internal/conf"
	"credit-analytics-backend/internal/data"
	"credit-analytics-backend/internal/server"
	"credit-analytics-backend/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	applicationRepo := data.NewApplicationRepo(dataData, logger)
	applicationUsecase := biz.NewApplicationUsecase(applicationRepo, logger)
	applicationService := service.NewApplicationService(applicationUsecase)
	applicantRepo := data.NewApplicantRepo(dataData, logger)
	applicantUsecase := biz.NewApplicantUsecase(applicantRepo, logger)
	applicantService := service.NewApplicantService(applicantUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, applicationService, applicantService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, applicationService, applicantService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
