// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/decision/v1/decision.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitteeSession struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId   string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	SessionSequence int32                  `protobuf:"varint,3,opt,name=session_sequence,json=sessionSequence,proto3" json:"session_sequence,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ScheduledAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitteeSession) Reset() {
	*x = CommitteeSession{}
	mi := &file_api_decision_v1_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitteeSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitteeSession) ProtoMessage() {}

func (x *CommitteeSession) ProtoReflect() protoreflect.Message {
	mi := &file_api_decision_v1_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitteeSession.ProtoReflect.Descriptor instead.
func (*CommitteeSession) Descriptor() ([]byte, []int) {
	return file_api_decision_v1_decision_proto_rawDescGZIP(), []int{0}
}

func (x *CommitteeSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommitteeSession) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CommitteeSession) GetSessionSequence() int32 {
	if x != nil {
		return x.SessionSequence
	}
	return 0
}

func (x *CommitteeSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommitteeSession) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *CommitteeSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CommitteeSession) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type CommitteeVote struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommitteeSessionId string                 `protobuf:"bytes,2,opt,name=committee_session_id,json=committeeSessionId,proto3" json:"committee_session_id,omitempty"`
	UserId             string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Vote               string                 `protobuf:"bytes,4,opt,name=vote,proto3" json:"vote,omitempty"`
	VoteReason         string                 `protobuf:"bytes,5,opt,name=vote_reason,json=voteReason,proto3" json:"vote_reason,omitempty"`
	VotedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=voted_at,json=votedAt,proto3" json:"voted_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CommitteeVote) Reset() {
	*x = CommitteeVote{}
	mi := &file_api_decision_v1_decision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitteeVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitteeVote) ProtoMessage() {}

func (x *CommitteeVote) ProtoReflect() protoreflect.Message {
	mi := &file_api_decision_v1_decision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitteeVote.ProtoReflect.Descriptor instead.
func (*CommitteeVote) Descriptor() ([]byte, []int) {
	return file_api_decision_v1_decision_proto_rawDescGZIP(), []int{1}
}

func (x *CommitteeVote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommitteeVote) GetCommitteeSessionId() string {
	if x != nil {
		return x.CommitteeSessionId
	}
	return ""
}

func (x *CommitteeVote) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CommitteeVote) GetVote() string {
	if x != nil {
		return x.Vote
	}
	return ""
}

func (x *CommitteeVote) GetVoteReason() string {
	if x != nil {
		return x.VoteReason
	}
	return ""
}

func (x *CommitteeVote) GetVotedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VotedAt
	}
	return nil
}

type CommitteeDecision struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommitteeSessionId    string                 `protobuf:"bytes,2,opt,name=committee_session_id,json=committeeSessionId,proto3" json:"committee_session_id,omitempty"`
	Decision              string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	DecisionReason        string                 `protobuf:"bytes,4,opt,name=decision_reason,json=decisionReason,proto3" json:"decision_reason,omitempty"`
	ApprovedAmount        string                 `protobuf:"bytes,5,opt,name=approved_amount,json=approvedAmount,proto3" json:"approved_amount,omitempty"`
	ApprovedTenor         int32                  `protobuf:"varint,6,opt,name=approved_tenor,json=approvedTenor,proto3" json:"approved_tenor,omitempty"`
	ApprovedInterestRate  string                 `protobuf:"bytes,7,opt,name=approved_interest_rate,json=approvedInterestRate,proto3" json:"approved_interest_rate,omitempty"`
	RequiresNextCommittee bool                   `protobuf:"varint,8,opt,name=requires_next_committee,json=requiresNextCommittee,proto3" json:"requires_next_committee,omitempty"`
	DecidedAt             *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CommitteeDecision) Reset() {
	*x = CommitteeDecision{}
	mi := &file_api_decision_v1_decision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitteeDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitteeDecision) ProtoMessage() {}

func (x *CommitteeDecision) ProtoReflect() protoreflect.Message {
	mi := &file_api_decision_v1_decision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitteeDecision.ProtoReflect.Descriptor instead.
func (*CommitteeDecision) Descriptor() ([]byte, []int) {
	return file_api_decision_v1_decision_proto_rawDescGZIP(), []int{2}
}

func (x *CommitteeDecision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommitteeDecision) GetCommitteeSessionId() string {
	if x != nil {
		return x.CommitteeSessionId
	}
	return ""
}

func (x *CommitteeDecision) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *CommitteeDecision) GetDecisionReason() string {
	if x != nil {
		return x.DecisionReason
	}
	return ""
}

func (x *CommitteeDecision) GetApprovedAmount() string {
	if x != nil {
		return x.ApprovedAmount
	}
	return ""
}

func (x *CommitteeDecision) GetApprovedTenor() int32 {
	if x != nil {
		return x.ApprovedTenor
	}
	return 0
}

func (x *CommitteeDecision) GetApprovedInterestRate() string {
	if x != nil {
		return x.ApprovedInterestRate
	}
	return ""
}

func (x *CommitteeDecision) GetRequiresNextCommittee() bool {
	if x != nil {
		return x.RequiresNextCommittee
	}
	return false
}

func (x *CommitteeDecision) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

type FinalDecision struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId     string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Decision          string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	DecisionSource    string                 `protobuf:"bytes,4,opt,name=decision_source,json=decisionSource,proto3" json:"decision_source,omitempty"`
	FinalAmount       string                 `protobuf:"bytes,5,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	FinalTenor        int32                  `protobuf:"varint,6,opt,name=final_tenor,json=finalTenor,proto3" json:"final_tenor,omitempty"`
	FinalInterestRate string                 `protobuf:"bytes,7,opt,name=final_interest_rate,json=finalInterestRate,proto3" json:"final_interest_rate,omitempty"`
	DecisionReason    string                 `protobuf:"bytes,8,opt,name=decision_reason,json=decisionReason,proto3" json:"decision_reason,omitempty"`
	DecidedBy         string                 `protobuf:"bytes,9,opt,name=decided_by,json=decidedBy,proto3" json:"decided_by,omitempty"`
	DecidedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FinalDecision) Reset() {
	*x = FinalDecision{}
	mi := &file_api_decision_v1_decision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalDecision) ProtoMessage() {}

func (x *FinalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_api_decision_v1_decision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalDecision.ProtoReflect.Descriptor instead.
func (*FinalDecision) Descriptor() ([]byte, []int) {
	return file_api_decision_v1_decision_proto_rawDescGZIP(), []int{3}
}

func (x *FinalDecision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FinalDecision) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *FinalDecision) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *FinalDecision) GetDecisionSource() string {
	if x != nil {
		return x.DecisionSource
	}
	return ""
}

func (x *FinalDecision) GetFinalAmount() string {
	if x != nil {
		return x.FinalAmount
	}
	return ""
}

func (x *FinalDecision) GetFinalTenor() int32 {
	if x != nil {
		return x.FinalTenor
	}
	return 0
}

func (x *FinalDecision) GetFinalInterestRate() string {
	if x != nil {
		return x.FinalInterestRate
	}
	return ""
}

func (x *FinalDecision) GetDecisionReason() string {
	if x != nil {
		return x.DecisionReason
	}
	return ""
}

func (x *FinalDecision) GetDecidedBy() string {
	if x != nil {
		return x.DecidedBy
	}
	return ""
}

func (x *FinalDecision) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

type CreateCommitteeSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId   string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	SessionSequence int32                  `protobuf:"varint,2,opt,name=session_sequence,json=sessionSequence,proto3" json:"session_sequence,omitempty"`
	ScheduledAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCommitteeSessionRequest) Reset() {
	*x = CreateCommitteeSessionRequest{}
	mi := &file_api_decision_v1_decision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommitteeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommitteeSessionRequest) ProtoMessage() {}

func (x *CreateCommitteeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_decision_v1_decision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommitteeSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateCommitteeSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_decision_v1_decision_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCommitteeSessionRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CreateCommitteeSessionRequest) GetSessionSequence() int32 {
	if x != nil {
		return x.SessionSequence
	}
	return 0
}

func (x *CreateCommitteeSessionRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

type SubmitCommitteeVoteRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CommitteeSessionId string                 `protobuf:"bytes,1,opt,name=committee_session_id,json=committeeSessionId,proto3" json:"committee_session_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Vote               string                 `protobuf:"bytes,3,opt,name=vote,proto3" json:"vote,omitempty"`
	VoteReason         string                 `protobuf:"bytes,4,opt,name=vote_reason,json=voteReason,proto3" json:"vote_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubmitCommitteeVoteRequest) Reset() {
	*x = SubmitCommitteeVoteRequest{}
	mi := &file_api_decision_v1_decision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommitteeVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommitteeVoteRequest) ProtoMessage() {}

func (x *SubmitCommitteeVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_decision_v1_decision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommitteeVoteRequest.ProtoReflect.Descriptor instead.
func (*SubmitCommitteeVoteRequest) Descriptor() ([]byte, []int) {
	return file_api_decision_v1_decision_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitCommitteeVoteRequest) GetCommitteeSessionId() string {
	if x != nil {
		return x.CommitteeSessionId
	}
	return ""
}

func (x *SubmitCommitteeVoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitCommitteeVoteRequest) GetVote() string {
	if x != nil {
		return x.Vote
	}
	return ""
}

func (x *SubmitCommitteeVoteRequest) GetVoteReason() string {
	if x != nil {
		return x.VoteReason
	}
	return ""
}

type FinalizeCommitteeDecisionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CommitteeSessionId    string                 `protobuf:"bytes,1,opt,name=committee_session_id,json=committeeSessionId,proto3" json:"committee_session_id,omitempty"`
	Decision              string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	DecisionReason        string                 `protobuf:"bytes,3,opt,name=decision_reason,json=decisionReason,proto3" json:"decision_reason,omitempty"`
	ApprovedAmount        string                 `protobuf:"bytes,4,opt,name=approved_amount,json=approvedAmount,proto3" json:"approved_amount,omitempty"`
	ApprovedTenor         int32                  `protobuf:"varint,5,opt,name=approved_tenor,json=approvedTenor,proto3" json:"approved_tenor,omitempty"`
	ApprovedInterestRate  string                 `protobuf:"bytes,6,opt,name=approved_interest_rate,json=approvedInterestRate,proto3" json:"approved_interest_rate,omitempty"`
	RequiresNextCommittee bool                   `protobuf:"varint,7,opt,name=requires_next_committee,json=requiresNextCommittee,proto3" json:"requires_next_committee,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FinalizeCommitteeDecisionRequest) Reset() {
	*x = FinalizeCommitteeDecisionRequest{}
	mi := &file_api_decision_v1_decision_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeCommitteeDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeCommitteeDecisionRequest) ProtoMessage() {}

func (x *FinalizeCommitteeDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_decision_v1_decision_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeCommitteeDecisionRequest.ProtoReflect.Descriptor instead.
func (*FinalizeCommitteeDecisionRequest) Descriptor() ([]byte, []int) {
	return file_api_decision_v1_decision_proto_rawDescGZIP(), []int{6}
}

func (x *FinalizeCommitteeDecisionRequest) GetCommitteeSessionId() string {
	if x != nil {
		return x.CommitteeSessionId
	}
	return ""
}

func (x *FinalizeCommitteeDecisionRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *FinalizeCommitteeDecisionRequest) GetDecisionReason() string {
	if x != nil {
		return x.DecisionReason
	}
	return ""
}

func (x *FinalizeCommitteeDecisionRequest) GetApprovedAmount() string {
	if x != nil {
		return x.ApprovedAmount
	}
	return ""
}

func (x *FinalizeCommitteeDecisionRequest) GetApprovedTenor() int32 {
	if x != nil {
		return x.ApprovedTenor
	}
	return 0
}

func (x *FinalizeCommitteeDecisionRequest) GetApprovedInterestRate() string {
	if x != nil {
		return x.ApprovedInterestRate
	}
	return ""
}

func (x *FinalizeCommitteeDecisionRequest) GetRequiresNextCommittee() bool {
	if x != nil {
		return x.RequiresNextCommittee
	}
	return false
}

type RecordFinalDecisionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId     string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Decision          string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	DecisionSource    string                 `protobuf:"bytes,3,opt,name=decision_source,json=decisionSource,proto3" json:"decision_source,omitempty"`
	FinalAmount       string                 `protobuf:"bytes,4,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	FinalTenor        int32                  `protobuf:"varint,5,opt,name=final_tenor,json=finalTenor,proto3" json:"final_tenor,omitempty"`
	FinalInterestRate string                 `protobuf:"bytes,6,opt,name=final_interest_rate,json=finalInterestRate,proto3" json:"final_interest_rate,omitempty"`
	DecisionReason    string                 `protobuf:"bytes,7,opt,name=decision_reason,json=decisionReason,proto3" json:"decision_reason,omitempty"`
	DecidedBy         string                 `protobuf:"bytes,8,opt,name=decided_by,json=decidedBy,proto3" json:"decided_by,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecordFinalDecisionRequest) Reset() {
	*x = RecordFinalDecisionRequest{}
	mi := &file_api_decision_v1_decision_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFinalDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFinalDecisionRequest) ProtoMessage() {}

func (x *RecordFinalDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_decision_v1_decision_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFinalDecisionRequest.ProtoReflect.Descriptor instead.
func (*RecordFinalDecisionRequest) Descriptor() ([]byte, []int) {
	return file_api_decision_v1_decision_proto_rawDescGZIP(), []int{7}
}

func (x *RecordFinalDecisionRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *RecordFinalDecisionRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *RecordFinalDecisionRequest) GetDecisionSource() string {
	if x != nil {
		return x.DecisionSource
	}
	return ""
}

func (x *RecordFinalDecisionRequest) GetFinalAmount() string {
	if x != nil {
		return x.FinalAmount
	}
	return ""
}

func (x *RecordFinalDecisionRequest) GetFinalTenor() int32 {
	if x != nil {
		return x.FinalTenor
	}
	return 0
}

func (x *RecordFinalDecisionRequest) GetFinalInterestRate() string {
	if x != nil {
		return x.FinalInterestRate
	}
	return ""
}

func (x *RecordFinalDecisionRequest) GetDecisionReason() string {
	if x != nil {
		return x.DecisionReason
	}
	return ""
}

func (x *RecordFinalDecisionRequest) GetDecidedBy() string {
	if x != nil {
		return x.DecidedBy
	}
	return ""
}

type GetApplicationDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationDecisionRequest) Reset() {
	*x = GetApplicationDecisionRequest{}
	mi := &file_api_decision_v1_decision_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationDecisionRequest) ProtoMessage() {}

func (x *GetApplicationDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_decision_v1_decision_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationDecisionRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationDecisionRequest) Descriptor() ([]byte, []int) {
	return file_api_decision_v1_decision_proto_rawDescGZIP(), []int{8}
}

func (x *GetApplicationDecisionRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

var File_api_decision_v1_decision_proto protoreflect.FileDescriptor

const file_api_decision_v1_decision_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/decision/v1/decision.proto\x12\x0fapi.decision.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x02\n" +
	"\x10CommitteeSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12)\n" +
	"\x10session_sequence\x18\x03 \x01(\x05R\x0fsessionSequence\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12=\n" +
	"\fscheduled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xd6\x01\n" +
	"\rCommitteeVote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x14committee_session_id\x18\x02 \x01(\tR\x12committeeSessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04vote\x18\x04 \x01(\tR\x04vote\x12\x1f\n" +
	"\vvote_reason\x18\x05 \x01(\tR\n" +
	"voteReason\x125\n" +
	"\bvoted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\avotedAt\"\x93\x03\n" +
	"\x11CommitteeDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x14committee_session_id\x18\x02 \x01(\tR\x12committeeSessionId\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12'\n" +
	"\x0fdecision_reason\x18\x04 \x01(\tR\x0edecisionReason\x12'\n" +
	"\x0fapproved_amount\x18\x05 \x01(\tR\x0eapprovedAmount\x12%\n" +
	"\x0eapproved_tenor\x18\x06 \x01(\x05R\rapprovedTenor\x124\n" +
	"\x16approved_interest_rate\x18\a \x01(\tR\x14approvedInterestRate\x126\n" +
	"\x17requires_next_committee\x18\b \x01(\bR\x15requiresNextCommittee\x129\n" +
	"\n" +
	"decided_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\"\x82\x03\n" +
	"\rFinalDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12'\n" +
	"\x0fdecision_source\x18\x04 \x01(\tR\x0edecisionSource\x12!\n" +
	"\ffinal_amount\x18\x05 \x01(\tR\vfinalAmount\x12\x1f\n" +
	"\vfinal_tenor\x18\x06 \x01(\x05R\n" +
	"finalTenor\x12.\n" +
	"\x13final_interest_rate\x18\a \x01(\tR\x11finalInterestRate\x12'\n" +
	"\x0fdecision_reason\x18\b \x01(\tR\x0edecisionReason\x12\x1d\n" +
	"\n" +
	"decided_by\x18\t \x01(\tR\tdecidedBy\x129\n" +
	"\n" +
	"decided_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\"\xb0\x01\n" +
	"\x1dCreateCommitteeSessionRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12)\n" +
	"\x10session_sequence\x18\x02 \x01(\x05R\x0fsessionSequence\x12=\n" +
	"\fscheduled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"\x9c\x01\n" +
	"\x1aSubmitCommitteeVoteRequest\x120\n" +
	"\x14committee_session_id\x18\x01 \x01(\tR\x12committeeSessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04vote\x18\x03 \x01(\tR\x04vote\x12\x1f\n" +
	"\vvote_reason\x18\x04 \x01(\tR\n" +
	"voteReason\"\xd7\x02\n" +
	" FinalizeCommitteeDecisionRequest\x120\n" +
	"\x14committee_session_id\x18\x01 \x01(\tR\x12committeeSessionId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12'\n" +
	"\x0fdecision_reason\x18\x03 \x01(\tR\x0edecisionReason\x12'\n" +
	"\x0fapproved_amount\x18\x04 \x01(\tR\x0eapprovedAmount\x12%\n" +
	"\x0eapproved_tenor\x18\x05 \x01(\x05R\rapprovedTenor\x124\n" +
	"\x16approved_interest_rate\x18\x06 \x01(\tR\x14approvedInterestRate\x126\n" +
	"\x17requires_next_committee\x18\a \x01(\bR\x15requiresNextCommittee\"\xc4\x02\n" +
	"\x1aRecordFinalDecisionRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12'\n" +
	"\x0fdecision_source\x18\x03 \x01(\tR\x0edecisionSource\x12!\n" +
	"\ffinal_amount\x18\x04 \x01(\tR\vfinalAmount\x12\x1f\n" +
	"\vfinal_tenor\x18\x05 \x01(\x05R\n" +
	"finalTenor\x12.\n" +
	"\x13final_interest_rate\x18\x06 \x01(\tR\x11finalInterestRate\x12'\n" +
	"\x0fdecision_reason\x18\a \x01(\tR\x0edecisionReason\x12\x1d\n" +
	"\n" +
	"decided_by\x18\b \x01(\tR\tdecidedBy\"F\n" +
	"\x1dGetApplicationDecisionRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId2\xb9\x06\n" +
	"\bDecision\x12\x8e\x01\n" +
	"\x16CreateCommitteeSession\x12..api.decision.v1.CreateCommitteeSessionRequest\x1a!.api.decision.v1.CommitteeSession\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/committee/sessions\x12\xa2\x01\n" +
	"\x13SubmitCommitteeVote\x12+.api.decision.v1.SubmitCommitteeVoteRequest\x1a\x1e.api.decision.v1.CommitteeVote\">\x82\xd3\xe4\x93\x028:\x01*\"3/v1/committee/sessions/{committee_session_id}/votes\x12\xb5\x01\n" +
	"\x19FinalizeCommitteeDecision\x121.api.decision.v1.FinalizeCommitteeDecisionRequest\x1a\".api.decision.v1.CommitteeDecision\"A\x82\xd3\xe4\x93\x02;:\x01*\"6/v1/committee/sessions/{committee_session_id}/finalize\x12\x9f\x01\n" +
	"\x13RecordFinalDecision\x12+.api.decision.v1.RecordFinalDecisionRequest\x1a\x1e.api.decision.v1.FinalDecision\";\x82\xd3\xe4\x93\x025:\x01*\"0/v1/applications/{application_id}/final-decision\x12\x9c\x01\n" +
	"\x16GetApplicationDecision\x12..api.decision.v1.GetApplicationDecisionRequest\x1a\x1e.api.decision.v1.FinalDecision\"2\x82\xd3\xe4\x93\x02,\x12*/v1/applications/{application_id}/decisionB@\n" +
	"\x0fapi.decision.v1P\x01Z+credit-analytics-backend/api/decision/v1;v1b\x06proto3"

var (
	file_api_decision_v1_decision_proto_rawDescOnce sync.Once
	file_api_decision_v1_decision_proto_rawDescData []byte
)

func file_api_decision_v1_decision_proto_rawDescGZIP() []byte {
	file_api_decision_v1_decision_proto_rawDescOnce.Do(func() {
		file_api_decision_v1_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_decision_v1_decision_proto_rawDesc), len(file_api_decision_v1_decision_proto_rawDesc)))
	})
	return file_api_decision_v1_decision_proto_rawDescData
}

var file_api_decision_v1_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_decision_v1_decision_proto_goTypes = []any{
	(*CommitteeSession)(nil),                 // 0: api.decision.v1.CommitteeSession
	(*CommitteeVote)(nil),                    // 1: api.decision.v1.CommitteeVote
	(*CommitteeDecision)(nil),                // 2: api.decision.v1.CommitteeDecision
	(*FinalDecision)(nil),                    // 3: api.decision.v1.FinalDecision
	(*CreateCommitteeSessionRequest)(nil),    // 4: api.decision.v1.CreateCommitteeSessionRequest
	(*SubmitCommitteeVoteRequest)(nil),       // 5: api.decision.v1.SubmitCommitteeVoteRequest
	(*FinalizeCommitteeDecisionRequest)(nil), // 6: api.decision.v1.FinalizeCommitteeDecisionRequest
	(*RecordFinalDecisionRequest)(nil),       // 7: api.decision.v1.RecordFinalDecisionRequest
	(*GetApplicationDecisionRequest)(nil),    // 8: api.decision.v1.GetApplicationDecisionRequest
	(*timestamppb.Timestamp)(nil),            // 9: google.protobuf.Timestamp
}
var file_api_decision_v1_decision_proto_depIdxs = []int32{
	9,  // 0: api.decision.v1.CommitteeSession.scheduled_at:type_name -> google.protobuf.Timestamp
	9,  // 1: api.decision.v1.CommitteeSession.started_at:type_name -> google.protobuf.Timestamp
	9,  // 2: api.decision.v1.CommitteeSession.completed_at:type_name -> google.protobuf.Timestamp
	9,  // 3: api.decision.v1.CommitteeVote.voted_at:type_name -> google.protobuf.Timestamp
	9,  // 4: api.decision.v1.CommitteeDecision.decided_at:type_name -> google.protobuf.Timestamp
	9,  // 5: api.decision.v1.FinalDecision.decided_at:type_name -> google.protobuf.Timestamp
	9,  // 6: api.decision.v1.CreateCommitteeSessionRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	4,  // 7: api.decision.v1.Decision.CreateCommitteeSession:input_type -> api.decision.v1.CreateCommitteeSessionRequest
	5,  // 8: api.decision.v1.Decision.SubmitCommitteeVote:input_type -> api.decision.v1.SubmitCommitteeVoteRequest
	6,  // 9: api.decision.v1.Decision.FinalizeCommitteeDecision:input_type -> api.decision.v1.FinalizeCommitteeDecisionRequest
	7,  // 10: api.decision.v1.Decision.RecordFinalDecision:input_type -> api.decision.v1.RecordFinalDecisionRequest
	8,  // 11: api.decision.v1.Decision.GetApplicationDecision:input_type -> api.decision.v1.GetApplicationDecisionRequest
	0,  // 12: api.decision.v1.Decision.CreateCommitteeSession:output_type -> api.decision.v1.CommitteeSession
	1,  // 13: api.decision.v1.Decision.SubmitCommitteeVote:output_type -> api.decision.v1.CommitteeVote
	2,  // 14: api.decision.v1.Decision.FinalizeCommitteeDecision:output_type -> api.decision.v1.CommitteeDecision
	3,  // 15: api.decision.v1.Decision.RecordFinalDecision:output_type -> api.decision.v1.FinalDecision
	3,  // 16: api.decision.v1.Decision.GetApplicationDecision:output_type -> api.decision.v1.FinalDecision
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_decision_v1_decision_proto_init() }
func file_api_decision_v1_decision_proto_init() {
	if File_api_decision_v1_decision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_decision_v1_decision_proto_rawDesc), len(file_api_decision_v1_decision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_decision_v1_decision_proto_goTypes,
		DependencyIndexes: file_api_decision_v1_decision_proto_depIdxs,
		MessageInfos:      file_api_decision_v1_decision_proto_msgTypes,
	}.Build()
	File_api_decision_v1_decision_proto = out.File
	file_api_decision_v1_decision_proto_goTypes = nil
	file_api_decision_v1_decision_proto_depIdxs = nil
}
