// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/decision/v1/decision.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Decision_CreateCommitteeSession_FullMethodName    = "/api.decision.v1.Decision/CreateCommitteeSession"
	Decision_SubmitCommitteeVote_FullMethodName       = "/api.decision.v1.Decision/SubmitCommitteeVote"
	Decision_FinalizeCommitteeDecision_FullMethodName = "/api.decision.v1.Decision/FinalizeCommitteeDecision"
	Decision_RecordFinalDecision_FullMethodName       = "/api.decision.v1.Decision/RecordFinalDecision"
	Decision_GetApplicationDecision_FullMethodName    = "/api.decision.v1.Decision/GetApplicationDecision"
)

// DecisionClient is the client API for Decision service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DecisionClient interface {
	CreateCommitteeSession(ctx context.Context, in *CreateCommitteeSessionRequest, opts ...grpc.CallOption) (*CommitteeSession, error)
	SubmitCommitteeVote(ctx context.Context, in *SubmitCommitteeVoteRequest, opts ...grpc.CallOption) (*CommitteeVote, error)
	FinalizeCommitteeDecision(ctx context.Context, in *FinalizeCommitteeDecisionRequest, opts ...grpc.CallOption) (*CommitteeDecision, error)
	RecordFinalDecision(ctx context.Context, in *RecordFinalDecisionRequest, opts ...grpc.CallOption) (*FinalDecision, error)
	GetApplicationDecision(ctx context.Context, in *GetApplicationDecisionRequest, opts ...grpc.CallOption) (*FinalDecision, error)
}

type decisionClient struct {
	cc grpc.ClientConnInterface
}

func NewDecisionClient(cc grpc.ClientConnInterface) DecisionClient {
	return &decisionClient{cc}
}

func (c *decisionClient) CreateCommitteeSession(ctx context.Context, in *CreateCommitteeSessionRequest, opts ...grpc.CallOption) (*CommitteeSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitteeSession)
	err := c.cc.Invoke(ctx, Decision_CreateCommitteeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decisionClient) SubmitCommitteeVote(ctx context.Context, in *SubmitCommitteeVoteRequest, opts ...grpc.CallOption) (*CommitteeVote, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitteeVote)
	err := c.cc.Invoke(ctx, Decision_SubmitCommitteeVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decisionClient) FinalizeCommitteeDecision(ctx context.Context, in *FinalizeCommitteeDecisionRequest, opts ...grpc.CallOption) (*CommitteeDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitteeDecision)
	err := c.cc.Invoke(ctx, Decision_FinalizeCommitteeDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decisionClient) RecordFinalDecision(ctx context.Context, in *RecordFinalDecisionRequest, opts ...grpc.CallOption) (*FinalDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalDecision)
	err := c.cc.Invoke(ctx, Decision_RecordFinalDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decisionClient) GetApplicationDecision(ctx context.Context, in *GetApplicationDecisionRequest, opts ...grpc.CallOption) (*FinalDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalDecision)
	err := c.cc.Invoke(ctx, Decision_GetApplicationDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DecisionServer is the server API for Decision service.
// All implementations must embed UnimplementedDecisionServer
// for forward compatibility.
type DecisionServer interface {
	CreateCommitteeSession(context.Context, *CreateCommitteeSessionRequest) (*CommitteeSession, error)
	SubmitCommitteeVote(context.Context, *SubmitCommitteeVoteRequest) (*CommitteeVote, error)
	FinalizeCommitteeDecision(context.Context, *FinalizeCommitteeDecisionRequest) (*CommitteeDecision, error)
	RecordFinalDecision(context.Context, *RecordFinalDecisionRequest) (*FinalDecision, error)
	GetApplicationDecision(context.Context, *GetApplicationDecisionRequest) (*FinalDecision, error)
	mustEmbedUnimplementedDecisionServer()
}

// UnimplementedDecisionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecisionServer struct{}

func (UnimplementedDecisionServer) CreateCommitteeSession(context.Context, *CreateCommitteeSessionRequest) (*CommitteeSession, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCommitteeSession not implemented")
}
func (UnimplementedDecisionServer) SubmitCommitteeVote(context.Context, *SubmitCommitteeVoteRequest) (*CommitteeVote, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCommitteeVote not implemented")
}
func (UnimplementedDecisionServer) FinalizeCommitteeDecision(context.Context, *FinalizeCommitteeDecisionRequest) (*CommitteeDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeCommitteeDecision not implemented")
}
func (UnimplementedDecisionServer) RecordFinalDecision(context.Context, *RecordFinalDecisionRequest) (*FinalDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordFinalDecision not implemented")
}
func (UnimplementedDecisionServer) GetApplicationDecision(context.Context, *GetApplicationDecisionRequest) (*FinalDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationDecision not implemented")
}
func (UnimplementedDecisionServer) mustEmbedUnimplementedDecisionServer() {}
func (UnimplementedDecisionServer) testEmbeddedByValue()                  {}

// UnsafeDecisionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecisionServer will
// result in compilation errors.
type UnsafeDecisionServer interface {
	mustEmbedUnimplementedDecisionServer()
}

func RegisterDecisionServer(s grpc.ServiceRegistrar, srv DecisionServer) {
	// If the following call panics, it indicates UnimplementedDecisionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Decision_ServiceDesc, srv)
}

func _Decision_CreateCommitteeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommitteeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecisionServer).CreateCommitteeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Decision_CreateCommitteeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecisionServer).CreateCommitteeSession(ctx, req.(*CreateCommitteeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decision_SubmitCommitteeVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCommitteeVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecisionServer).SubmitCommitteeVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Decision_SubmitCommitteeVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecisionServer).SubmitCommitteeVote(ctx, req.(*SubmitCommitteeVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decision_FinalizeCommitteeDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeCommitteeDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecisionServer).FinalizeCommitteeDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Decision_FinalizeCommitteeDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecisionServer).FinalizeCommitteeDecision(ctx, req.(*FinalizeCommitteeDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decision_RecordFinalDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordFinalDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecisionServer).RecordFinalDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Decision_RecordFinalDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecisionServer).RecordFinalDecision(ctx, req.(*RecordFinalDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decision_GetApplicationDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecisionServer).GetApplicationDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Decision_GetApplicationDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecisionServer).GetApplicationDecision(ctx, req.(*GetApplicationDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Decision_ServiceDesc is the grpc.ServiceDesc for Decision service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Decision_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.decision.v1.Decision",
	HandlerType: (*DecisionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCommitteeSession",
			Handler:    _Decision_CreateCommitteeSession_Handler,
		},
		{
			MethodName: "SubmitCommitteeVote",
			Handler:    _Decision_SubmitCommitteeVote_Handler,
		},
		{
			MethodName: "FinalizeCommitteeDecision",
			Handler:    _Decision_FinalizeCommitteeDecision_Handler,
		},
		{
			MethodName: "RecordFinalDecision",
			Handler:    _Decision_RecordFinalDecision_Handler,
		},
		{
			MethodName: "GetApplicationDecision",
			Handler:    _Decision_GetApplicationDecision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/decision/v1/decision.proto",
}
