// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/applicant/v1/applicant.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Applicant_CreateApplicant_FullMethodName          = "/api.applicant.v1.Applicant/CreateApplicant"
	Applicant_GetApplicant_FullMethodName             = "/api.applicant.v1.Applicant/GetApplicant"
	Applicant_UpdateApplicant_FullMethodName          = "/api.applicant.v1.Applicant/UpdateApplicant"
	Applicant_ListApplicants_FullMethodName           = "/api.applicant.v1.Applicant/ListApplicants"
	Applicant_UpsertApplicantAttribute_FullMethodName = "/api.applicant.v1.Applicant/UpsertApplicantAttribute"
)

// ApplicantClient is the client API for Applicant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplicantClient interface {
	CreateApplicant(ctx context.Context, in *CreateApplicantRequest, opts ...grpc.CallOption) (*CreateApplicantReply, error)
	GetApplicant(ctx context.Context, in *GetApplicantRequest, opts ...grpc.CallOption) (*GetApplicantReply, error)
	UpdateApplicant(ctx context.Context, in *UpdateApplicantRequest, opts ...grpc.CallOption) (*UpdateApplicantReply, error)
	ListApplicants(ctx context.Context, in *ListApplicantsRequest, opts ...grpc.CallOption) (*ListApplicantsReply, error)
	UpsertApplicantAttribute(ctx context.Context, in *UpsertApplicantAttributeRequest, opts ...grpc.CallOption) (*ApplicantAttribute, error)
}

type applicantClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicantClient(cc grpc.ClientConnInterface) ApplicantClient {
	return &applicantClient{cc}
}

func (c *applicantClient) CreateApplicant(ctx context.Context, in *CreateApplicantRequest, opts ...grpc.CallOption) (*CreateApplicantReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateApplicantReply)
	err := c.cc.Invoke(ctx, Applicant_CreateApplicant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicantClient) GetApplicant(ctx context.Context, in *GetApplicantRequest, opts ...grpc.CallOption) (*GetApplicantReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicantReply)
	err := c.cc.Invoke(ctx, Applicant_GetApplicant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicantClient) UpdateApplicant(ctx context.Context, in *UpdateApplicantRequest, opts ...grpc.CallOption) (*UpdateApplicantReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateApplicantReply)
	err := c.cc.Invoke(ctx, Applicant_UpdateApplicant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicantClient) ListApplicants(ctx context.Context, in *ListApplicantsRequest, opts ...grpc.CallOption) (*ListApplicantsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApplicantsReply)
	err := c.cc.Invoke(ctx, Applicant_ListApplicants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicantClient) UpsertApplicantAttribute(ctx context.Context, in *UpsertApplicantAttributeRequest, opts ...grpc.CallOption) (*ApplicantAttribute, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicantAttribute)
	err := c.cc.Invoke(ctx, Applicant_UpsertApplicantAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicantServer is the server API for Applicant service.
// All implementations must embed UnimplementedApplicantServer
// for forward compatibility.
type ApplicantServer interface {
	CreateApplicant(context.Context, *CreateApplicantRequest) (*CreateApplicantReply, error)
	GetApplicant(context.Context, *GetApplicantRequest) (*GetApplicantReply, error)
	UpdateApplicant(context.Context, *UpdateApplicantRequest) (*UpdateApplicantReply, error)
	ListApplicants(context.Context, *ListApplicantsRequest) (*ListApplicantsReply, error)
	UpsertApplicantAttribute(context.Context, *UpsertApplicantAttributeRequest) (*ApplicantAttribute, error)
	mustEmbedUnimplementedApplicantServer()
}

// UnimplementedApplicantServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApplicantServer struct{}

func (UnimplementedApplicantServer) CreateApplicant(context.Context, *CreateApplicantRequest) (*CreateApplicantReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApplicant not implemented")
}
func (UnimplementedApplicantServer) GetApplicant(context.Context, *GetApplicantRequest) (*GetApplicantReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicant not implemented")
}
func (UnimplementedApplicantServer) UpdateApplicant(context.Context, *UpdateApplicantRequest) (*UpdateApplicantReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateApplicant not implemented")
}
func (UnimplementedApplicantServer) ListApplicants(context.Context, *ListApplicantsRequest) (*ListApplicantsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplicants not implemented")
}
func (UnimplementedApplicantServer) UpsertApplicantAttribute(context.Context, *UpsertApplicantAttributeRequest) (*ApplicantAttribute, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertApplicantAttribute not implemented")
}
func (UnimplementedApplicantServer) mustEmbedUnimplementedApplicantServer() {}
func (UnimplementedApplicantServer) testEmbeddedByValue()                   {}

// UnsafeApplicantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicantServer will
// result in compilation errors.
type UnsafeApplicantServer interface {
	mustEmbedUnimplementedApplicantServer()
}

func RegisterApplicantServer(s grpc.ServiceRegistrar, srv ApplicantServer) {
	// If the following call panics, it indicates UnimplementedApplicantServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Applicant_ServiceDesc, srv)
}

func _Applicant_CreateApplicant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServer).CreateApplicant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Applicant_CreateApplicant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServer).CreateApplicant(ctx, req.(*CreateApplicantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applicant_GetApplicant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServer).GetApplicant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Applicant_GetApplicant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServer).GetApplicant(ctx, req.(*GetApplicantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applicant_UpdateApplicant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServer).UpdateApplicant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Applicant_UpdateApplicant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServer).UpdateApplicant(ctx, req.(*UpdateApplicantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applicant_ListApplicants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServer).ListApplicants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Applicant_ListApplicants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServer).ListApplicants(ctx, req.(*ListApplicantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applicant_UpsertApplicantAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertApplicantAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServer).UpsertApplicantAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Applicant_UpsertApplicantAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServer).UpsertApplicantAttribute(ctx, req.(*UpsertApplicantAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Applicant_ServiceDesc is the grpc.ServiceDesc for Applicant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Applicant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.applicant.v1.Applicant",
	HandlerType: (*ApplicantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApplicant",
			Handler:    _Applicant_CreateApplicant_Handler,
		},
		{
			MethodName: "GetApplicant",
			Handler:    _Applicant_GetApplicant_Handler,
		},
		{
			MethodName: "UpdateApplicant",
			Handler:    _Applicant_UpdateApplicant_Handler,
		},
		{
			MethodName: "ListApplicants",
			Handler:    _Applicant_ListApplicants_Handler,
		},
		{
			MethodName: "UpsertApplicantAttribute",
			Handler:    _Applicant_UpsertApplicantAttribute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/applicant/v1/applicant.proto",
}
