// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/applicant/v1/applicant.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicantAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicantAttribute) Reset() {
	*x = ApplicantAttribute{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicantAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicantAttribute) ProtoMessage() {}

func (x *ApplicantAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicantAttribute.ProtoReflect.Descriptor instead.
func (*ApplicantAttribute) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicantAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ApplicantAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ApplicantAttribute) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *ApplicantAttribute) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ApplicantInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicantType     string                 `protobuf:"bytes,2,opt,name=applicant_type,json=applicantType,proto3" json:"applicant_type,omitempty"`
	IdentityNumber    string                 `protobuf:"bytes,3,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	TaxId             string                 `protobuf:"bytes,4,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	FullName          string                 `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	BirthDate         string                 `protobuf:"bytes,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	EstablishmentDate string                 `protobuf:"bytes,7,opt,name=establishment_date,json=establishmentDate,proto3" json:"establishment_date,omitempty"`
	Attributes        []*ApplicantAttribute  `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApplicantInfo) Reset() {
	*x = ApplicantInfo{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicantInfo) ProtoMessage() {}

func (x *ApplicantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicantInfo.ProtoReflect.Descriptor instead.
func (*ApplicantInfo) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicantInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicantInfo) GetApplicantType() string {
	if x != nil {
		return x.ApplicantType
	}
	return ""
}

func (x *ApplicantInfo) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *ApplicantInfo) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *ApplicantInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ApplicantInfo) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *ApplicantInfo) GetEstablishmentDate() string {
	if x != nil {
		return x.EstablishmentDate
	}
	return ""
}

func (x *ApplicantInfo) GetAttributes() []*ApplicantAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ApplicantInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApplicantInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateApplicantRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApplicantType     string                 `protobuf:"bytes,1,opt,name=applicant_type,json=applicantType,proto3" json:"applicant_type,omitempty"`
	IdentityNumber    string                 `protobuf:"bytes,2,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	TaxId             string                 `protobuf:"bytes,3,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	FullName          string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	BirthDate         string                 `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	EstablishmentDate string                 `protobuf:"bytes,6,opt,name=establishment_date,json=establishmentDate,proto3" json:"establishment_date,omitempty"`
	Attributes        []*ApplicantAttribute  `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateApplicantRequest) Reset() {
	*x = CreateApplicantRequest{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicantRequest) ProtoMessage() {}

func (x *CreateApplicantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicantRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicantRequest) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateApplicantRequest) GetApplicantType() string {
	if x != nil {
		return x.ApplicantType
	}
	return ""
}

func (x *CreateApplicantRequest) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *CreateApplicantRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *CreateApplicantRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateApplicantRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CreateApplicantRequest) GetEstablishmentDate() string {
	if x != nil {
		return x.EstablishmentDate
	}
	return ""
}

func (x *CreateApplicantRequest) GetAttributes() []*ApplicantAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CreateApplicantReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicantReply) Reset() {
	*x = CreateApplicantReply{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicantReply) ProtoMessage() {}

func (x *CreateApplicantReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicantReply.ProtoReflect.Descriptor instead.
func (*CreateApplicantReply) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{3}
}

func (x *CreateApplicantReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateApplicantReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetApplicantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicantRequest) Reset() {
	*x = GetApplicantRequest{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicantRequest) ProtoMessage() {}

func (x *GetApplicantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicantRequest.ProtoReflect.Descriptor instead.
func (*GetApplicantRequest) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{4}
}

func (x *GetApplicantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetApplicantReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applicant     *ApplicantInfo         `protobuf:"bytes,1,opt,name=applicant,proto3" json:"applicant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicantReply) Reset() {
	*x = GetApplicantReply{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicantReply) ProtoMessage() {}

func (x *GetApplicantReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicantReply.ProtoReflect.Descriptor instead.
func (*GetApplicantReply) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{5}
}

func (x *GetApplicantReply) GetApplicant() *ApplicantInfo {
	if x != nil {
		return x.Applicant
	}
	return nil
}

type UpdateApplicantRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicantType     string                 `protobuf:"bytes,2,opt,name=applicant_type,json=applicantType,proto3" json:"applicant_type,omitempty"`
	IdentityNumber    string                 `protobuf:"bytes,3,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	TaxId             string                 `protobuf:"bytes,4,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	FullName          string                 `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	BirthDate         string                 `protobuf:"bytes,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	EstablishmentDate string                 `protobuf:"bytes,7,opt,name=establishment_date,json=establishmentDate,proto3" json:"establishment_date,omitempty"`
	Attributes        []*ApplicantAttribute  `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateApplicantRequest) Reset() {
	*x = UpdateApplicantRequest{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicantRequest) ProtoMessage() {}

func (x *UpdateApplicantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicantRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicantRequest) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateApplicantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateApplicantRequest) GetApplicantType() string {
	if x != nil {
		return x.ApplicantType
	}
	return ""
}

func (x *UpdateApplicantRequest) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *UpdateApplicantRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *UpdateApplicantRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateApplicantRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *UpdateApplicantRequest) GetEstablishmentDate() string {
	if x != nil {
		return x.EstablishmentDate
	}
	return ""
}

func (x *UpdateApplicantRequest) GetAttributes() []*ApplicantAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type UpdateApplicantReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicantReply) Reset() {
	*x = UpdateApplicantReply{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicantReply) ProtoMessage() {}

func (x *UpdateApplicantReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicantReply.ProtoReflect.Descriptor instead.
func (*UpdateApplicantReply) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateApplicantReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListApplicantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicantsRequest) Reset() {
	*x = ListApplicantsRequest{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicantsRequest) ProtoMessage() {}

func (x *ListApplicantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicantsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicantsRequest) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{8}
}

func (x *ListApplicantsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListApplicantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListApplicantsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListApplicantsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applicants    []*ApplicantInfo       `protobuf:"bytes,1,rep,name=applicants,proto3" json:"applicants,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicantsReply) Reset() {
	*x = ListApplicantsReply{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicantsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicantsReply) ProtoMessage() {}

func (x *ListApplicantsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicantsReply.ProtoReflect.Descriptor instead.
func (*ListApplicantsReply) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{9}
}

func (x *ListApplicantsReply) GetApplicants() []*ApplicantInfo {
	if x != nil {
		return x.Applicants
	}
	return nil
}

func (x *ListApplicantsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpsertApplicantAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicantId   string                 `protobuf:"bytes,1,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	DataType      string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertApplicantAttributeRequest) Reset() {
	*x = UpsertApplicantAttributeRequest{}
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertApplicantAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertApplicantAttributeRequest) ProtoMessage() {}

func (x *UpsertApplicantAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_applicant_v1_applicant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertApplicantAttributeRequest.ProtoReflect.Descriptor instead.
func (*UpsertApplicantAttributeRequest) Descriptor() ([]byte, []int) {
	return file_api_applicant_v1_applicant_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertApplicantAttributeRequest) GetApplicantId() string {
	if x != nil {
		return x.ApplicantId
	}
	return ""
}

func (x *UpsertApplicantAttributeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpsertApplicantAttributeRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpsertApplicantAttributeRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

var File_api_applicant_v1_applicant_proto protoreflect.FileDescriptor

const file_api_applicant_v1_applicant_proto_rawDesc = "" +
	"\n" +
	" api/applicant/v1/applicant.proto\x12\x10api.applicant.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x01\n" +
	"\x12ApplicantAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xad\x03\n" +
	"\rApplicantInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplicant_type\x18\x02 \x01(\tR\rapplicantType\x12'\n" +
	"\x0fidentity_number\x18\x03 \x01(\tR\x0eidentityNumber\x12\x15\n" +
	"\x06tax_id\x18\x04 \x01(\tR\x05taxId\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x06 \x01(\tR\tbirthDate\x12-\n" +
	"\x12establishment_date\x18\a \x01(\tR\x11establishmentDate\x12D\n" +
	"\n" +
	"attributes\x18\b \x03(\v2$.api.applicant.v1.ApplicantAttributeR\n" +
	"attributes\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb0\x02\n" +
	"\x16CreateApplicantRequest\x12%\n" +
	"\x0eapplicant_type\x18\x01 \x01(\tR\rapplicantType\x12'\n" +
	"\x0fidentity_number\x18\x02 \x01(\tR\x0eidentityNumber\x12\x15\n" +
	"\x06tax_id\x18\x03 \x01(\tR\x05taxId\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tR\tbirthDate\x12-\n" +
	"\x12establishment_date\x18\x06 \x01(\tR\x11establishmentDate\x12D\n" +
	"\n" +
	"attributes\x18\a \x03(\v2$.api.applicant.v1.ApplicantAttributeR\n" +
	"attributes\"@\n" +
	"\x14CreateApplicantReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x13GetApplicantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x11GetApplicantReply\x12=\n" +
	"\tapplicant\x18\x01 \x01(\v2\x1f.api.applicant.v1.ApplicantInfoR\tapplicant\"\xc0\x02\n" +
	"\x16UpdateApplicantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplicant_type\x18\x02 \x01(\tR\rapplicantType\x12'\n" +
	"\x0fidentity_number\x18\x03 \x01(\tR\x0eidentityNumber\x12\x15\n" +
	"\x06tax_id\x18\x04 \x01(\tR\x05taxId\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x06 \x01(\tR\tbirthDate\x12-\n" +
	"\x12establishment_date\x18\a \x01(\tR\x11establishmentDate\x12D\n" +
	"\n" +
	"attributes\x18\b \x03(\v2$.api.applicant.v1.ApplicantAttributeR\n" +
	"attributes\"0\n" +
	"\x14UpdateApplicantReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"b\n" +
	"\x15ListApplicantsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"l\n" +
	"\x13ListApplicantsReply\x12?\n" +
	"\n" +
	"applicants\x18\x01 \x03(\v2\x1f.api.applicant.v1.ApplicantInfoR\n" +
	"applicants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x89\x01\n" +
	"\x1fUpsertApplicantAttributeRequest\x12!\n" +
	"\fapplicant_id\x18\x01 \x01(\tR\vapplicantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType2\xaf\x05\n" +
	"\tApplicant\x12~\n" +
	"\x0fCreateApplicant\x12(.api.applicant.v1.CreateApplicantRequest\x1a&.api.applicant.v1.CreateApplicantReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/applicants\x12w\n" +
	"\fGetApplicant\x12%.api.applicant.v1.GetApplicantRequest\x1a#.api.applicant.v1.GetApplicantReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/applicants/{id}\x12\x83\x01\n" +
	"\x0fUpdateApplicant\x12(.api.applicant.v1.UpdateApplicantRequest\x1a&.api.applicant.v1.UpdateApplicantReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/applicants/{id}\x12x\n" +
	"\x0eListApplicants\x12'.api.applicant.v1.ListApplicantsRequest\x1a%.api.applicant.v1.ListApplicantsReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/applicants\x12\xa8\x01\n" +
	"\x18UpsertApplicantAttribute\x121.api.applicant.v1.UpsertApplicantAttributeRequest\x1a$.api.applicant.v1.ApplicantAttribute\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/applicants/{applicant_id}/attributesBB\n" +
	"\x10api.applicant.v1P\x01Z,credit-analytics-backend/api/applicant/v1;v1b\x06proto3"

var (
	file_api_applicant_v1_applicant_proto_rawDescOnce sync.Once
	file_api_applicant_v1_applicant_proto_rawDescData []byte
)

func file_api_applicant_v1_applicant_proto_rawDescGZIP() []byte {
	file_api_applicant_v1_applicant_proto_rawDescOnce.Do(func() {
		file_api_applicant_v1_applicant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_applicant_v1_applicant_proto_rawDesc), len(file_api_applicant_v1_applicant_proto_rawDesc)))
	})
	return file_api_applicant_v1_applicant_proto_rawDescData
}

var file_api_applicant_v1_applicant_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_applicant_v1_applicant_proto_goTypes = []any{
	(*ApplicantAttribute)(nil),              // 0: api.applicant.v1.ApplicantAttribute
	(*ApplicantInfo)(nil),                   // 1: api.applicant.v1.ApplicantInfo
	(*CreateApplicantRequest)(nil),          // 2: api.applicant.v1.CreateApplicantRequest
	(*CreateApplicantReply)(nil),            // 3: api.applicant.v1.CreateApplicantReply
	(*GetApplicantRequest)(nil),             // 4: api.applicant.v1.GetApplicantRequest
	(*GetApplicantReply)(nil),               // 5: api.applicant.v1.GetApplicantReply
	(*UpdateApplicantRequest)(nil),          // 6: api.applicant.v1.UpdateApplicantRequest
	(*UpdateApplicantReply)(nil),            // 7: api.applicant.v1.UpdateApplicantReply
	(*ListApplicantsRequest)(nil),           // 8: api.applicant.v1.ListApplicantsRequest
	(*ListApplicantsReply)(nil),             // 9: api.applicant.v1.ListApplicantsReply
	(*UpsertApplicantAttributeRequest)(nil), // 10: api.applicant.v1.UpsertApplicantAttributeRequest
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
}
var file_api_applicant_v1_applicant_proto_depIdxs = []int32{
	11, // 0: api.applicant.v1.ApplicantAttribute.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 1: api.applicant.v1.ApplicantInfo.attributes:type_name -> api.applicant.v1.ApplicantAttribute
	11, // 2: api.applicant.v1.ApplicantInfo.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: api.applicant.v1.ApplicantInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: api.applicant.v1.CreateApplicantRequest.attributes:type_name -> api.applicant.v1.ApplicantAttribute
	1,  // 5: api.applicant.v1.GetApplicantReply.applicant:type_name -> api.applicant.v1.ApplicantInfo
	0,  // 6: api.applicant.v1.UpdateApplicantRequest.attributes:type_name -> api.applicant.v1.ApplicantAttribute
	1,  // 7: api.applicant.v1.ListApplicantsReply.applicants:type_name -> api.applicant.v1.ApplicantInfo
	2,  // 8: api.applicant.v1.Applicant.CreateApplicant:input_type -> api.applicant.v1.CreateApplicantRequest
	4,  // 9: api.applicant.v1.Applicant.GetApplicant:input_type -> api.applicant.v1.GetApplicantRequest
	6,  // 10: api.applicant.v1.Applicant.UpdateApplicant:input_type -> api.applicant.v1.UpdateApplicantRequest
	8,  // 11: api.applicant.v1.Applicant.ListApplicants:input_type -> api.applicant.v1.ListApplicantsRequest
	10, // 12: api.applicant.v1.Applicant.UpsertApplicantAttribute:input_type -> api.applicant.v1.UpsertApplicantAttributeRequest
	3,  // 13: api.applicant.v1.Applicant.CreateApplicant:output_type -> api.applicant.v1.CreateApplicantReply
	5,  // 14: api.applicant.v1.Applicant.GetApplicant:output_type -> api.applicant.v1.GetApplicantReply
	7,  // 15: api.applicant.v1.Applicant.UpdateApplicant:output_type -> api.applicant.v1.UpdateApplicantReply
	9,  // 16: api.applicant.v1.Applicant.ListApplicants:output_type -> api.applicant.v1.ListApplicantsReply
	0,  // 17: api.applicant.v1.Applicant.UpsertApplicantAttribute:output_type -> api.applicant.v1.ApplicantAttribute
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_applicant_v1_applicant_proto_init() }
func file_api_applicant_v1_applicant_proto_init() {
	if File_api_applicant_v1_applicant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_applicant_v1_applicant_proto_rawDesc), len(file_api_applicant_v1_applicant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_applicant_v1_applicant_proto_goTypes,
		DependencyIndexes: file_api_applicant_v1_applicant_proto_depIdxs,
		MessageInfos:      file_api_applicant_v1_applicant_proto_msgTypes,
	}.Build()
	File_api_applicant_v1_applicant_proto = out.File
	file_api_applicant_v1_applicant_proto_goTypes = nil
	file_api_applicant_v1_applicant_proto_depIdxs = nil
}
