// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: applicant/v1/applicant.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ApplicantService_ListApplicants_FullMethodName            = "/api.applicant.v1.ApplicantService/ListApplicants"
	ApplicantService_CreateApplicant_FullMethodName           = "/api.applicant.v1.ApplicantService/CreateApplicant"
	ApplicantService_GetApplicant_FullMethodName              = "/api.applicant.v1.ApplicantService/GetApplicant"
	ApplicantService_UpdateApplicant_FullMethodName           = "/api.applicant.v1.ApplicantService/UpdateApplicant"
	ApplicantService_GetApplicantAttributes_FullMethodName    = "/api.applicant.v1.ApplicantService/GetApplicantAttributes"
	ApplicantService_UpsertApplicantAttributes_FullMethodName = "/api.applicant.v1.ApplicantService/UpsertApplicantAttributes"
)

// ApplicantServiceClient is the client API for ApplicantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplicantServiceClient interface {
	ListApplicants(ctx context.Context, in *ListApplicantsRequest, opts ...grpc.CallOption) (*ListApplicantsResponse, error)
	CreateApplicant(ctx context.Context, in *CreateApplicantRequest, opts ...grpc.CallOption) (*Applicant, error)
	GetApplicant(ctx context.Context, in *GetApplicantRequest, opts ...grpc.CallOption) (*Applicant, error)
	UpdateApplicant(ctx context.Context, in *UpdateApplicantRequest, opts ...grpc.CallOption) (*Applicant, error)
	GetApplicantAttributes(ctx context.Context, in *GetApplicantAttributesRequest, opts ...grpc.CallOption) (*ApplicantAttributes, error)
	UpsertApplicantAttributes(ctx context.Context, in *UpsertApplicantAttributesRequest, opts ...grpc.CallOption) (*ApplicantAttributes, error)
}

type applicantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicantServiceClient(cc grpc.ClientConnInterface) ApplicantServiceClient {
	return &applicantServiceClient{cc}
}

func (c *applicantServiceClient) ListApplicants(ctx context.Context, in *ListApplicantsRequest, opts ...grpc.CallOption) (*ListApplicantsResponse, error) {
	out := new(ListApplicantsResponse)
	err := c.cc.Invoke(ctx, ApplicantService_ListApplicants_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicantServiceClient) CreateApplicant(ctx context.Context, in *CreateApplicantRequest, opts ...grpc.CallOption) (*Applicant, error) {
	out := new(Applicant)
	err := c.cc.Invoke(ctx, ApplicantService_CreateApplicant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicantServiceClient) GetApplicant(ctx context.Context, in *GetApplicantRequest, opts ...grpc.CallOption) (*Applicant, error) {
	out := new(Applicant)
	err := c.cc.Invoke(ctx, ApplicantService_GetApplicant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicantServiceClient) UpdateApplicant(ctx context.Context, in *UpdateApplicantRequest, opts ...grpc.CallOption) (*Applicant, error) {
	out := new(Applicant)
	err := c.cc.Invoke(ctx, ApplicantService_UpdateApplicant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicantServiceClient) GetApplicantAttributes(ctx context.Context, in *GetApplicantAttributesRequest, opts ...grpc.CallOption) (*ApplicantAttributes, error) {
	out := new(ApplicantAttributes)
	err := c.cc.Invoke(ctx, ApplicantService_GetApplicantAttributes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicantServiceClient) UpsertApplicantAttributes(ctx context.Context, in *UpsertApplicantAttributesRequest, opts ...grpc.CallOption) (*ApplicantAttributes, error) {
	out := new(ApplicantAttributes)
	err := c.cc.Invoke(ctx, ApplicantService_UpsertApplicantAttributes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicantServiceServer is the server API for ApplicantService service.
// All implementations must embed UnimplementedApplicantServiceServer
// for forward compatibility
type ApplicantServiceServer interface {
	ListApplicants(context.Context, *ListApplicantsRequest) (*ListApplicantsResponse, error)
	CreateApplicant(context.Context, *CreateApplicantRequest) (*Applicant, error)
	GetApplicant(context.Context, *GetApplicantRequest) (*Applicant, error)
	UpdateApplicant(context.Context, *UpdateApplicantRequest) (*Applicant, error)
	GetApplicantAttributes(context.Context, *GetApplicantAttributesRequest) (*ApplicantAttributes, error)
	UpsertApplicantAttributes(context.Context, *UpsertApplicantAttributesRequest) (*ApplicantAttributes, error)
	mustEmbedUnimplementedApplicantServiceServer()
}

// UnimplementedApplicantServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApplicantServiceServer struct {
}

func (UnimplementedApplicantServiceServer) ListApplicants(context.Context, *ListApplicantsRequest) (*ListApplicantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplicants not implemented")
}
func (UnimplementedApplicantServiceServer) CreateApplicant(context.Context, *CreateApplicantRequest) (*Applicant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApplicant not implemented")
}
func (UnimplementedApplicantServiceServer) GetApplicant(context.Context, *GetApplicantRequest) (*Applicant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicant not implemented")
}
func (UnimplementedApplicantServiceServer) UpdateApplicant(context.Context, *UpdateApplicantRequest) (*Applicant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApplicant not implemented")
}
func (UnimplementedApplicantServiceServer) GetApplicantAttributes(context.Context, *GetApplicantAttributesRequest) (*ApplicantAttributes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicantAttributes not implemented")
}
func (UnimplementedApplicantServiceServer) UpsertApplicantAttributes(context.Context, *UpsertApplicantAttributesRequest) (*ApplicantAttributes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertApplicantAttributes not implemented")
}
func (UnimplementedApplicantServiceServer) mustEmbedUnimplementedApplicantServiceServer() {}

// UnsafeApplicantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicantServiceServer will
// result in compilation errors.
type UnsafeApplicantServiceServer interface {
	mustEmbedUnimplementedApplicantServiceServer()
}

func RegisterApplicantServiceServer(s grpc.ServiceRegistrar, srv ApplicantServiceServer) {
	s.RegisterService(&ApplicantService_ServiceDesc, srv)
}

func _ApplicantService_ListApplicants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServiceServer).ListApplicants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicantService_ListApplicants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServiceServer).ListApplicants(ctx, req.(*ListApplicantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicantService_CreateApplicant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServiceServer).CreateApplicant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicantService_CreateApplicant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServiceServer).CreateApplicant(ctx, req.(*CreateApplicantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicantService_GetApplicant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServiceServer).GetApplicant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicantService_GetApplicant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServiceServer).GetApplicant(ctx, req.(*GetApplicantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicantService_UpdateApplicant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServiceServer).UpdateApplicant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicantService_UpdateApplicant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServiceServer).UpdateApplicant(ctx, req.(*UpdateApplicantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicantService_GetApplicantAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicantAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServiceServer).GetApplicantAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicantService_GetApplicantAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServiceServer).GetApplicantAttributes(ctx, req.(*GetApplicantAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicantService_UpsertApplicantAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertApplicantAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicantServiceServer).UpsertApplicantAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicantService_UpsertApplicantAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicantServiceServer).UpsertApplicantAttributes(ctx, req.(*UpsertApplicantAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplicantService_ServiceDesc is the grpc.ServiceDesc for ApplicantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.applicant.v1.ApplicantService",
	HandlerType: (*ApplicantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApplicants",
			Handler:    _ApplicantService_ListApplicants_Handler,
		},
		{
			MethodName: "CreateApplicant",
			Handler:    _ApplicantService_CreateApplicant_Handler,
		},
		{
			MethodName: "GetApplicant",
			Handler:    _ApplicantService_GetApplicant_Handler,
		},
		{
			MethodName: "UpdateApplicant",
			Handler:    _ApplicantService_UpdateApplicant_Handler,
		},
		{
			MethodName: "GetApplicantAttributes",
			Handler:    _ApplicantService_GetApplicantAttributes_Handler,
		},
		{
			MethodName: "UpsertApplicantAttributes",
			Handler:    _ApplicantService_UpsertApplicantAttributes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "applicant/v1/applicant.proto",
}
