// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: application/v1/application.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationApplicationServiceChangeApplicationStatus = "/api.application.v1.ApplicationService/ChangeApplicationStatus"
const OperationApplicationServiceCreateApplication = "/api.application.v1.ApplicationService/CreateApplication"
const OperationApplicationServiceGetApplication = "/api.application.v1.ApplicationService/GetApplication"
const OperationApplicationServiceGetApplicationAttributes = "/api.application.v1.ApplicationService/GetApplicationAttributes"
const OperationApplicationServiceListApplicationDocuments = "/api.application.v1.ApplicationService/ListApplicationDocuments"
const OperationApplicationServiceListApplications = "/api.application.v1.ApplicationService/ListApplications"
const OperationApplicationServiceUpdateApplication = "/api.application.v1.ApplicationService/UpdateApplication"
const OperationApplicationServiceUploadApplicationDocument = "/api.application.v1.ApplicationService/UploadApplicationDocument"
const OperationApplicationServiceUpsertApplicationAttributes = "/api.application.v1.ApplicationService/UpsertApplicationAttributes"

type ApplicationServiceHTTPServer interface {
	ChangeApplicationStatus(context.Context, *ChangeApplicationStatusRequest) (*Application, error)
	CreateApplication(context.Context, *CreateApplicationRequest) (*Application, error)
	GetApplication(context.Context, *GetApplicationRequest) (*Application, error)
	GetApplicationAttributes(context.Context, *GetApplicationAttributesRequest) (*ApplicationAttributes, error)
	ListApplicationDocuments(context.Context, *ListApplicationDocumentsRequest) (*ListApplicationDocumentsResponse, error)
	ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error)
	UpdateApplication(context.Context, *UpdateApplicationRequest) (*Application, error)
	UploadApplicationDocument(context.Context, *UploadApplicationDocumentRequest) (*ApplicationDocument, error)
	UpsertApplicationAttributes(context.Context, *UpsertApplicationAttributesRequest) (*ApplicationAttributes, error)
}

func RegisterApplicationServiceHTTPServer(s *http.Server, srv ApplicationServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/applications", _ApplicationService_CreateApplication0_HTTP_Handler(srv))
	r.GET("/v1/applications/{id}", _ApplicationService_GetApplication0_HTTP_Handler(srv))
	r.GET("/v1/applications", _ApplicationService_ListApplications0_HTTP_Handler(srv))
	r.PUT("/v1/applications/{id}", _ApplicationService_UpdateApplication0_HTTP_Handler(srv))
	r.GET("/v1/applications/{application_id}/attributes", _ApplicationService_GetApplicationAttributes0_HTTP_Handler(srv))
	r.POST("/v1/applications/{application_id}/attributes", _ApplicationService_UpsertApplicationAttributes0_HTTP_Handler(srv))
	r.POST("/v1/applications/{id}/status", _ApplicationService_ChangeApplicationStatus0_HTTP_Handler(srv))
	r.POST("/v1/applications/{application_id}/documents", _ApplicationService_UploadApplicationDocument0_HTTP_Handler(srv))
	r.GET("/v1/applications/{application_id}/documents", _ApplicationService_ListApplicationDocuments0_HTTP_Handler(srv))
}

func _ApplicationService_CreateApplication0_HTTP_Handler(srv ApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationServiceCreateApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateApplication(ctx, req.(*CreateApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Application)
		return ctx.Result(200, reply)
	}
}

func _ApplicationService_GetApplication0_HTTP_Handler(srv ApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetApplicationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationServiceGetApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetApplication(ctx, req.(*GetApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Application)
		return ctx.Result(200, reply)
	}
}

func _ApplicationService_ListApplications0_HTTP_Handler(srv ApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListApplicationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationServiceListApplications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListApplications(ctx, req.(*ListApplicationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApplicationsResponse)
		return ctx.Result(200, reply)
	}
}

func _ApplicationService_UpdateApplication0_HTTP_Handler(srv ApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationServiceUpdateApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateApplication(ctx, req.(*UpdateApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Application)
		return ctx.Result(200, reply)
	}
}

func _ApplicationService_GetApplicationAttributes0_HTTP_Handler(srv ApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetApplicationAttributesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationServiceGetApplicationAttributes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetApplicationAttributes(ctx, req.(*GetApplicationAttributesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationAttributes)
		return ctx.Result(200, reply)
	}
}

func _ApplicationService_UpsertApplicationAttributes0_HTTP_Handler(srv ApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertApplicationAttributesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationServiceUpsertApplicationAttributes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertApplicationAttributes(ctx, req.(*UpsertApplicationAttributesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationAttributes)
		return ctx.Result(200, reply)
	}
}

func _ApplicationService_ChangeApplicationStatus0_HTTP_Handler(srv ApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangeApplicationStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationServiceChangeApplicationStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ChangeApplicationStatus(ctx, req.(*ChangeApplicationStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Application)
		return ctx.Result(200, reply)
	}
}

func _ApplicationService_UploadApplicationDocument0_HTTP_Handler(srv ApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadApplicationDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationServiceUploadApplicationDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadApplicationDocument(ctx, req.(*UploadApplicationDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationDocument)
		return ctx.Result(200, reply)
	}
}

func _ApplicationService_ListApplicationDocuments0_HTTP_Handler(srv ApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListApplicationDocumentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationServiceListApplicationDocuments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListApplicationDocuments(ctx, req.(*ListApplicationDocumentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApplicationDocumentsResponse)
		return ctx.Result(200, reply)
	}
}

type ApplicationServiceHTTPClient interface {
	ChangeApplicationStatus(ctx context.Context, req *ChangeApplicationStatusRequest, opts ...http.CallOption) (rsp *Application, err error)
	CreateApplication(ctx context.Context, req *CreateApplicationRequest, opts ...http.CallOption) (rsp *Application, err error)
	GetApplication(ctx context.Context, req *GetApplicationRequest, opts ...http.CallOption) (rsp *Application, err error)
	GetApplicationAttributes(ctx context.Context, req *GetApplicationAttributesRequest, opts ...http.CallOption) (rsp *ApplicationAttributes, err error)
	ListApplicationDocuments(ctx context.Context, req *ListApplicationDocumentsRequest, opts ...http.CallOption) (rsp *ListApplicationDocumentsResponse, err error)
	ListApplications(ctx context.Context, req *ListApplicationsRequest, opts ...http.CallOption) (rsp *ListApplicationsResponse, err error)
	UpdateApplication(ctx context.Context, req *UpdateApplicationRequest, opts ...http.CallOption) (rsp *Application, err error)
	UploadApplicationDocument(ctx context.Context, req *UploadApplicationDocumentRequest, opts ...http.CallOption) (rsp *ApplicationDocument, err error)
	UpsertApplicationAttributes(ctx context.Context, req *UpsertApplicationAttributesRequest, opts ...http.CallOption) (rsp *ApplicationAttributes, err error)
}

type ApplicationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewApplicationServiceHTTPClient(client *http.Client) ApplicationServiceHTTPClient {
	return &ApplicationServiceHTTPClientImpl{client}
}

func (c *ApplicationServiceHTTPClientImpl) ChangeApplicationStatus(ctx context.Context, in *ChangeApplicationStatusRequest, opts ...http.CallOption) (*Application, error) {
	var out Application
	pattern := "/v1/applications/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationApplicationServiceChangeApplicationStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationServiceHTTPClientImpl) CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...http.CallOption) (*Application, error) {
	var out Application
	pattern := "/v1/applications"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationApplicationServiceCreateApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationServiceHTTPClientImpl) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...http.CallOption) (*Application, error) {
	var out Application
	pattern := "/v1/applications/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationApplicationServiceGetApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationServiceHTTPClientImpl) GetApplicationAttributes(ctx context.Context, in *GetApplicationAttributesRequest, opts ...http.CallOption) (*ApplicationAttributes, error) {
	var out ApplicationAttributes
	pattern := "/v1/applications/{application_id}/attributes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationApplicationServiceGetApplicationAttributes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationServiceHTTPClientImpl) ListApplicationDocuments(ctx context.Context, in *ListApplicationDocumentsRequest, opts ...http.CallOption) (*ListApplicationDocumentsResponse, error) {
	var out ListApplicationDocumentsResponse
	pattern := "/v1/applications/{application_id}/documents"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationApplicationServiceListApplicationDocuments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationServiceHTTPClientImpl) ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...http.CallOption) (*ListApplicationsResponse, error) {
	var out ListApplicationsResponse
	pattern := "/v1/applications"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationApplicationServiceListApplications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationServiceHTTPClientImpl) UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...http.CallOption) (*Application, error) {
	var out Application
	pattern := "/v1/applications/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationApplicationServiceUpdateApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationServiceHTTPClientImpl) UploadApplicationDocument(ctx context.Context, in *UploadApplicationDocumentRequest, opts ...http.CallOption) (*ApplicationDocument, error) {
	var out ApplicationDocument
	pattern := "/v1/applications/{application_id}/documents"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationApplicationServiceUploadApplicationDocument))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationServiceHTTPClientImpl) UpsertApplicationAttributes(ctx context.Context, in *UpsertApplicationAttributesRequest, opts ...http.CallOption) (*ApplicationAttributes, error) {
	var out ApplicationAttributes
	pattern := "/v1/applications/{application_id}/attributes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationApplicationServiceUpsertApplicationAttributes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationPartyServiceAddPartyToApplication = "/api.application.v1.PartyService/AddPartyToApplication"
const OperationPartyServiceListApplicationParties = "/api.application.v1.PartyService/ListApplicationParties"
const OperationPartyServiceRemovePartyFromApplication = "/api.application.v1.PartyService/RemovePartyFromApplication"

type PartyServiceHTTPServer interface {
	AddPartyToApplication(context.Context, *AddPartyToApplicationRequest) (*ApplicationParty, error)
	ListApplicationParties(context.Context, *ListApplicationPartiesRequest) (*ListApplicationPartiesResponse, error)
	RemovePartyFromApplication(context.Context, *RemovePartyFromApplicationRequest) (*emptypb.Empty, error)
}

func RegisterPartyServiceHTTPServer(s *http.Server, srv PartyServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/applications/{application_id}/parties", _PartyService_AddPartyToApplication0_HTTP_Handler(srv))
	r.DELETE("/v1/applications/{application_id}/parties/{party_id}", _PartyService_RemovePartyFromApplication0_HTTP_Handler(srv))
	r.GET("/v1/applications/{application_id}/parties", _PartyService_ListApplicationParties0_HTTP_Handler(srv))
}

func _PartyService_AddPartyToApplication0_HTTP_Handler(srv PartyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddPartyToApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPartyServiceAddPartyToApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddPartyToApplication(ctx, req.(*AddPartyToApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationParty)
		return ctx.Result(200, reply)
	}
}

func _PartyService_RemovePartyFromApplication0_HTTP_Handler(srv PartyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemovePartyFromApplicationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPartyServiceRemovePartyFromApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemovePartyFromApplication(ctx, req.(*RemovePartyFromApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _PartyService_ListApplicationParties0_HTTP_Handler(srv PartyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListApplicationPartiesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPartyServiceListApplicationParties)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListApplicationParties(ctx, req.(*ListApplicationPartiesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApplicationPartiesResponse)
		return ctx.Result(200, reply)
	}
}

type PartyServiceHTTPClient interface {
	AddPartyToApplication(ctx context.Context, req *AddPartyToApplicationRequest, opts ...http.CallOption) (rsp *ApplicationParty, err error)
	ListApplicationParties(ctx context.Context, req *ListApplicationPartiesRequest, opts ...http.CallOption) (rsp *ListApplicationPartiesResponse, err error)
	RemovePartyFromApplication(ctx context.Context, req *RemovePartyFromApplicationRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type PartyServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPartyServiceHTTPClient(client *http.Client) PartyServiceHTTPClient {
	return &PartyServiceHTTPClientImpl{client}
}

func (c *PartyServiceHTTPClientImpl) AddPartyToApplication(ctx context.Context, in *AddPartyToApplicationRequest, opts ...http.CallOption) (*ApplicationParty, error) {
	var out ApplicationParty
	pattern := "/v1/applications/{application_id}/parties"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPartyServiceAddPartyToApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PartyServiceHTTPClientImpl) ListApplicationParties(ctx context.Context, in *ListApplicationPartiesRequest, opts ...http.CallOption) (*ListApplicationPartiesResponse, error) {
	var out ListApplicationPartiesResponse
	pattern := "/v1/applications/{application_id}/parties"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPartyServiceListApplicationParties))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PartyServiceHTTPClientImpl) RemovePartyFromApplication(ctx context.Context, in *RemovePartyFromApplicationRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/applications/{application_id}/parties/{party_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPartyServiceRemovePartyFromApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
