// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: application/v1/application.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ApplicationService_CreateApplication_FullMethodName           = "/api.application.v1.ApplicationService/CreateApplication"
	ApplicationService_GetApplication_FullMethodName              = "/api.application.v1.ApplicationService/GetApplication"
	ApplicationService_ListApplications_FullMethodName            = "/api.application.v1.ApplicationService/ListApplications"
	ApplicationService_UpdateApplication_FullMethodName           = "/api.application.v1.ApplicationService/UpdateApplication"
	ApplicationService_GetApplicationAttributes_FullMethodName    = "/api.application.v1.ApplicationService/GetApplicationAttributes"
	ApplicationService_UpsertApplicationAttributes_FullMethodName = "/api.application.v1.ApplicationService/UpsertApplicationAttributes"
	ApplicationService_ChangeApplicationStatus_FullMethodName     = "/api.application.v1.ApplicationService/ChangeApplicationStatus"
	ApplicationService_UploadApplicationDocument_FullMethodName   = "/api.application.v1.ApplicationService/UploadApplicationDocument"
	ApplicationService_ListApplicationDocuments_FullMethodName    = "/api.application.v1.ApplicationService/ListApplicationDocuments"
	ApplicationService_GetPresignedUrl_FullMethodName             = "/api.application.v1.ApplicationService/GetPresignedUrl"
)

// ApplicationServiceClient is the client API for ApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplicationServiceClient interface {
	CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*Application, error)
	GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*Application, error)
	ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error)
	UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*Application, error)
	GetApplicationAttributes(ctx context.Context, in *GetApplicationAttributesRequest, opts ...grpc.CallOption) (*ApplicationAttributes, error)
	UpsertApplicationAttributes(ctx context.Context, in *UpsertApplicationAttributesRequest, opts ...grpc.CallOption) (*ApplicationAttributes, error)
	ChangeApplicationStatus(ctx context.Context, in *ChangeApplicationStatusRequest, opts ...grpc.CallOption) (*Application, error)
	UploadApplicationDocument(ctx context.Context, in *UploadApplicationDocumentRequest, opts ...grpc.CallOption) (*ApplicationDocument, error)
	ListApplicationDocuments(ctx context.Context, in *ListApplicationDocumentsRequest, opts ...grpc.CallOption) (*ListApplicationDocumentsResponse, error)
	GetPresignedUrl(ctx context.Context, in *GetPresignedUrlRequest, opts ...grpc.CallOption) (*GetPresignedUrlResponse, error)
}

type applicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationServiceClient(cc grpc.ClientConnInterface) ApplicationServiceClient {
	return &applicationServiceClient{cc}
}

func (c *applicationServiceClient) CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := c.cc.Invoke(ctx, ApplicationService_CreateApplication_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := c.cc.Invoke(ctx, ApplicationService_GetApplication_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error) {
	out := new(ListApplicationsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ListApplications_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := c.cc.Invoke(ctx, ApplicationService_UpdateApplication_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetApplicationAttributes(ctx context.Context, in *GetApplicationAttributesRequest, opts ...grpc.CallOption) (*ApplicationAttributes, error) {
	out := new(ApplicationAttributes)
	err := c.cc.Invoke(ctx, ApplicationService_GetApplicationAttributes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) UpsertApplicationAttributes(ctx context.Context, in *UpsertApplicationAttributesRequest, opts ...grpc.CallOption) (*ApplicationAttributes, error) {
	out := new(ApplicationAttributes)
	err := c.cc.Invoke(ctx, ApplicationService_UpsertApplicationAttributes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ChangeApplicationStatus(ctx context.Context, in *ChangeApplicationStatusRequest, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := c.cc.Invoke(ctx, ApplicationService_ChangeApplicationStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) UploadApplicationDocument(ctx context.Context, in *UploadApplicationDocumentRequest, opts ...grpc.CallOption) (*ApplicationDocument, error) {
	out := new(ApplicationDocument)
	err := c.cc.Invoke(ctx, ApplicationService_UploadApplicationDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListApplicationDocuments(ctx context.Context, in *ListApplicationDocumentsRequest, opts ...grpc.CallOption) (*ListApplicationDocumentsResponse, error) {
	out := new(ListApplicationDocumentsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ListApplicationDocuments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetPresignedUrl(ctx context.Context, in *GetPresignedUrlRequest, opts ...grpc.CallOption) (*GetPresignedUrlResponse, error) {
	out := new(GetPresignedUrlResponse)
	err := c.cc.Invoke(ctx, ApplicationService_GetPresignedUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationServiceServer is the server API for ApplicationService service.
// All implementations must embed UnimplementedApplicationServiceServer
// for forward compatibility
type ApplicationServiceServer interface {
	CreateApplication(context.Context, *CreateApplicationRequest) (*Application, error)
	GetApplication(context.Context, *GetApplicationRequest) (*Application, error)
	ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error)
	UpdateApplication(context.Context, *UpdateApplicationRequest) (*Application, error)
	GetApplicationAttributes(context.Context, *GetApplicationAttributesRequest) (*ApplicationAttributes, error)
	UpsertApplicationAttributes(context.Context, *UpsertApplicationAttributesRequest) (*ApplicationAttributes, error)
	ChangeApplicationStatus(context.Context, *ChangeApplicationStatusRequest) (*Application, error)
	UploadApplicationDocument(context.Context, *UploadApplicationDocumentRequest) (*ApplicationDocument, error)
	ListApplicationDocuments(context.Context, *ListApplicationDocumentsRequest) (*ListApplicationDocumentsResponse, error)
	GetPresignedUrl(context.Context, *GetPresignedUrlRequest) (*GetPresignedUrlResponse, error)
	mustEmbedUnimplementedApplicationServiceServer()
}

// UnimplementedApplicationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApplicationServiceServer struct {
}

func (UnimplementedApplicationServiceServer) CreateApplication(context.Context, *CreateApplicationRequest) (*Application, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApplication not implemented")
}
func (UnimplementedApplicationServiceServer) GetApplication(context.Context, *GetApplicationRequest) (*Application, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplication not implemented")
}
func (UnimplementedApplicationServiceServer) ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplications not implemented")
}
func (UnimplementedApplicationServiceServer) UpdateApplication(context.Context, *UpdateApplicationRequest) (*Application, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApplication not implemented")
}
func (UnimplementedApplicationServiceServer) GetApplicationAttributes(context.Context, *GetApplicationAttributesRequest) (*ApplicationAttributes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationAttributes not implemented")
}
func (UnimplementedApplicationServiceServer) UpsertApplicationAttributes(context.Context, *UpsertApplicationAttributesRequest) (*ApplicationAttributes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertApplicationAttributes not implemented")
}
func (UnimplementedApplicationServiceServer) ChangeApplicationStatus(context.Context, *ChangeApplicationStatusRequest) (*Application, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeApplicationStatus not implemented")
}
func (UnimplementedApplicationServiceServer) UploadApplicationDocument(context.Context, *UploadApplicationDocumentRequest) (*ApplicationDocument, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadApplicationDocument not implemented")
}
func (UnimplementedApplicationServiceServer) ListApplicationDocuments(context.Context, *ListApplicationDocumentsRequest) (*ListApplicationDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplicationDocuments not implemented")
}
func (UnimplementedApplicationServiceServer) GetPresignedUrl(context.Context, *GetPresignedUrlRequest) (*GetPresignedUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresignedUrl not implemented")
}
func (UnimplementedApplicationServiceServer) mustEmbedUnimplementedApplicationServiceServer() {}

// UnsafeApplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationServiceServer will
// result in compilation errors.
type UnsafeApplicationServiceServer interface {
	mustEmbedUnimplementedApplicationServiceServer()
}

func RegisterApplicationServiceServer(s grpc.ServiceRegistrar, srv ApplicationServiceServer) {
	s.RegisterService(&ApplicationService_ServiceDesc, srv)
}

func _ApplicationService_CreateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).CreateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_CreateApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).CreateApplication(ctx, req.(*CreateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetApplication(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListApplications(ctx, req.(*ListApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_UpdateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).UpdateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_UpdateApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).UpdateApplication(ctx, req.(*UpdateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetApplicationAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetApplicationAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetApplicationAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetApplicationAttributes(ctx, req.(*GetApplicationAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_UpsertApplicationAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertApplicationAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).UpsertApplicationAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_UpsertApplicationAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).UpsertApplicationAttributes(ctx, req.(*UpsertApplicationAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ChangeApplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeApplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ChangeApplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ChangeApplicationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ChangeApplicationStatus(ctx, req.(*ChangeApplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_UploadApplicationDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadApplicationDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).UploadApplicationDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_UploadApplicationDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).UploadApplicationDocument(ctx, req.(*UploadApplicationDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListApplicationDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListApplicationDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListApplicationDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListApplicationDocuments(ctx, req.(*ListApplicationDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetPresignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetPresignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetPresignedUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetPresignedUrl(ctx, req.(*GetPresignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplicationService_ServiceDesc is the grpc.ServiceDesc for ApplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.application.v1.ApplicationService",
	HandlerType: (*ApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApplication",
			Handler:    _ApplicationService_CreateApplication_Handler,
		},
		{
			MethodName: "GetApplication",
			Handler:    _ApplicationService_GetApplication_Handler,
		},
		{
			MethodName: "ListApplications",
			Handler:    _ApplicationService_ListApplications_Handler,
		},
		{
			MethodName: "UpdateApplication",
			Handler:    _ApplicationService_UpdateApplication_Handler,
		},
		{
			MethodName: "GetApplicationAttributes",
			Handler:    _ApplicationService_GetApplicationAttributes_Handler,
		},
		{
			MethodName: "UpsertApplicationAttributes",
			Handler:    _ApplicationService_UpsertApplicationAttributes_Handler,
		},
		{
			MethodName: "ChangeApplicationStatus",
			Handler:    _ApplicationService_ChangeApplicationStatus_Handler,
		},
		{
			MethodName: "UploadApplicationDocument",
			Handler:    _ApplicationService_UploadApplicationDocument_Handler,
		},
		{
			MethodName: "ListApplicationDocuments",
			Handler:    _ApplicationService_ListApplicationDocuments_Handler,
		},
		{
			MethodName: "GetPresignedUrl",
			Handler:    _ApplicationService_GetPresignedUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application/v1/application.proto",
}

const (
	PartyService_AddPartyToApplication_FullMethodName      = "/api.application.v1.PartyService/AddPartyToApplication"
	PartyService_RemovePartyFromApplication_FullMethodName = "/api.application.v1.PartyService/RemovePartyFromApplication"
	PartyService_ListApplicationParties_FullMethodName     = "/api.application.v1.PartyService/ListApplicationParties"
)

// PartyServiceClient is the client API for PartyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartyServiceClient interface {
	AddPartyToApplication(ctx context.Context, in *AddPartyToApplicationRequest, opts ...grpc.CallOption) (*ApplicationParty, error)
	RemovePartyFromApplication(ctx context.Context, in *RemovePartyFromApplicationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListApplicationParties(ctx context.Context, in *ListApplicationPartiesRequest, opts ...grpc.CallOption) (*ListApplicationPartiesResponse, error)
}

type partyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartyServiceClient(cc grpc.ClientConnInterface) PartyServiceClient {
	return &partyServiceClient{cc}
}

func (c *partyServiceClient) AddPartyToApplication(ctx context.Context, in *AddPartyToApplicationRequest, opts ...grpc.CallOption) (*ApplicationParty, error) {
	out := new(ApplicationParty)
	err := c.cc.Invoke(ctx, PartyService_AddPartyToApplication_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) RemovePartyFromApplication(ctx context.Context, in *RemovePartyFromApplicationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PartyService_RemovePartyFromApplication_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) ListApplicationParties(ctx context.Context, in *ListApplicationPartiesRequest, opts ...grpc.CallOption) (*ListApplicationPartiesResponse, error) {
	out := new(ListApplicationPartiesResponse)
	err := c.cc.Invoke(ctx, PartyService_ListApplicationParties_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartyServiceServer is the server API for PartyService service.
// All implementations must embed UnimplementedPartyServiceServer
// for forward compatibility
type PartyServiceServer interface {
	AddPartyToApplication(context.Context, *AddPartyToApplicationRequest) (*ApplicationParty, error)
	RemovePartyFromApplication(context.Context, *RemovePartyFromApplicationRequest) (*emptypb.Empty, error)
	ListApplicationParties(context.Context, *ListApplicationPartiesRequest) (*ListApplicationPartiesResponse, error)
	mustEmbedUnimplementedPartyServiceServer()
}

// UnimplementedPartyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPartyServiceServer struct {
}

func (UnimplementedPartyServiceServer) AddPartyToApplication(context.Context, *AddPartyToApplicationRequest) (*ApplicationParty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPartyToApplication not implemented")
}
func (UnimplementedPartyServiceServer) RemovePartyFromApplication(context.Context, *RemovePartyFromApplicationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePartyFromApplication not implemented")
}
func (UnimplementedPartyServiceServer) ListApplicationParties(context.Context, *ListApplicationPartiesRequest) (*ListApplicationPartiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplicationParties not implemented")
}
func (UnimplementedPartyServiceServer) mustEmbedUnimplementedPartyServiceServer() {}

// UnsafePartyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartyServiceServer will
// result in compilation errors.
type UnsafePartyServiceServer interface {
	mustEmbedUnimplementedPartyServiceServer()
}

func RegisterPartyServiceServer(s grpc.ServiceRegistrar, srv PartyServiceServer) {
	s.RegisterService(&PartyService_ServiceDesc, srv)
}

func _PartyService_AddPartyToApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPartyToApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).AddPartyToApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_AddPartyToApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).AddPartyToApplication(ctx, req.(*AddPartyToApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_RemovePartyFromApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePartyFromApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).RemovePartyFromApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_RemovePartyFromApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).RemovePartyFromApplication(ctx, req.(*RemovePartyFromApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_ListApplicationParties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationPartiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).ListApplicationParties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyService_ListApplicationParties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).ListApplicationParties(ctx, req.(*ListApplicationPartiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartyService_ServiceDesc is the grpc.ServiceDesc for PartyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.application.v1.PartyService",
	HandlerType: (*PartyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPartyToApplication",
			Handler:    _PartyService_AddPartyToApplication_Handler,
		},
		{
			MethodName: "RemovePartyFromApplication",
			Handler:    _PartyService_RemovePartyFromApplication_Handler,
		},
		{
			MethodName: "ListApplicationParties",
			Handler:    _PartyService_ListApplicationParties_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application/v1/application.proto",
}
