// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: api/application/v1/application.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationApplicationCreateApplication = "/api.application.v1.Application/CreateApplication"
const OperationApplicationGetApplication = "/api.application.v1.Application/GetApplication"
const OperationApplicationListApplications = "/api.application.v1.Application/ListApplications"
const OperationApplicationListStatusLogs = "/api.application.v1.Application/ListStatusLogs"
const OperationApplicationSoftDeleteApplication = "/api.application.v1.Application/SoftDeleteApplication"
const OperationApplicationUpdateApplication = "/api.application.v1.Application/UpdateApplication"

type ApplicationHTTPServer interface {
	CreateApplication(context.Context, *CreateApplicationRequest) (*CreateApplicationReply, error)
	GetApplication(context.Context, *GetApplicationRequest) (*GetApplicationReply, error)
	ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsReply, error)
	ListStatusLogs(context.Context, *ListStatusLogsRequest) (*ListStatusLogsReply, error)
	SoftDeleteApplication(context.Context, *SoftDeleteApplicationRequest) (*SoftDeleteApplicationReply, error)
	UpdateApplication(context.Context, *UpdateApplicationRequest) (*UpdateApplicationReply, error)
}

func RegisterApplicationHTTPServer(s *http.Server, srv ApplicationHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/applications", _Application_CreateApplication0_HTTP_Handler(srv))
	r.GET("/v1/applications/{id}", _Application_GetApplication0_HTTP_Handler(srv))
	r.GET("/v1/applications", _Application_ListApplications0_HTTP_Handler(srv))
	r.PUT("/v1/applications/{id}", _Application_UpdateApplication0_HTTP_Handler(srv))
	r.DELETE("/v1/applications/{id}", _Application_SoftDeleteApplication0_HTTP_Handler(srv))
	r.GET("/v1/applications/{application_id}/status-logs", _Application_ListStatusLogs0_HTTP_Handler(srv))
}

func _Application_CreateApplication0_HTTP_Handler(srv ApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationCreateApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateApplication(ctx, req.(*CreateApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateApplicationReply)
		return ctx.Result(200, reply)
	}
}

func _Application_GetApplication0_HTTP_Handler(srv ApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetApplicationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationGetApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetApplication(ctx, req.(*GetApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetApplicationReply)
		return ctx.Result(200, reply)
	}
}

func _Application_ListApplications0_HTTP_Handler(srv ApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListApplicationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationListApplications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListApplications(ctx, req.(*ListApplicationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApplicationsReply)
		return ctx.Result(200, reply)
	}
}

func _Application_UpdateApplication0_HTTP_Handler(srv ApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationUpdateApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateApplication(ctx, req.(*UpdateApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateApplicationReply)
		return ctx.Result(200, reply)
	}
}

func _Application_SoftDeleteApplication0_HTTP_Handler(srv ApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SoftDeleteApplicationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationSoftDeleteApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SoftDeleteApplication(ctx, req.(*SoftDeleteApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SoftDeleteApplicationReply)
		return ctx.Result(200, reply)
	}
}

func _Application_ListStatusLogs0_HTTP_Handler(srv ApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListStatusLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationApplicationListStatusLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListStatusLogs(ctx, req.(*ListStatusLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListStatusLogsReply)
		return ctx.Result(200, reply)
	}
}

type ApplicationHTTPClient interface {
	CreateApplication(ctx context.Context, req *CreateApplicationRequest, opts ...http.CallOption) (rsp *CreateApplicationReply, err error)
	GetApplication(ctx context.Context, req *GetApplicationRequest, opts ...http.CallOption) (rsp *GetApplicationReply, err error)
	ListApplications(ctx context.Context, req *ListApplicationsRequest, opts ...http.CallOption) (rsp *ListApplicationsReply, err error)
	ListStatusLogs(ctx context.Context, req *ListStatusLogsRequest, opts ...http.CallOption) (rsp *ListStatusLogsReply, err error)
	SoftDeleteApplication(ctx context.Context, req *SoftDeleteApplicationRequest, opts ...http.CallOption) (rsp *SoftDeleteApplicationReply, err error)
	UpdateApplication(ctx context.Context, req *UpdateApplicationRequest, opts ...http.CallOption) (rsp *UpdateApplicationReply, err error)
}

type ApplicationHTTPClientImpl struct {
	cc *http.Client
}

func NewApplicationHTTPClient(client *http.Client) ApplicationHTTPClient {
	return &ApplicationHTTPClientImpl{client}
}

func (c *ApplicationHTTPClientImpl) CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...http.CallOption) (*CreateApplicationReply, error) {
	var out CreateApplicationReply
	pattern := "/v1/applications"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationApplicationCreateApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationHTTPClientImpl) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...http.CallOption) (*GetApplicationReply, error) {
	var out GetApplicationReply
	pattern := "/v1/applications/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationApplicationGetApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationHTTPClientImpl) ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...http.CallOption) (*ListApplicationsReply, error) {
	var out ListApplicationsReply
	pattern := "/v1/applications"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationApplicationListApplications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationHTTPClientImpl) ListStatusLogs(ctx context.Context, in *ListStatusLogsRequest, opts ...http.CallOption) (*ListStatusLogsReply, error) {
	var out ListStatusLogsReply
	pattern := "/v1/applications/{application_id}/status-logs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationApplicationListStatusLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationHTTPClientImpl) SoftDeleteApplication(ctx context.Context, in *SoftDeleteApplicationRequest, opts ...http.CallOption) (*SoftDeleteApplicationReply, error) {
	var out SoftDeleteApplicationReply
	pattern := "/v1/applications/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationApplicationSoftDeleteApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ApplicationHTTPClientImpl) UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...http.CallOption) (*UpdateApplicationReply, error) {
	var out UpdateApplicationReply
	pattern := "/v1/applications/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationApplicationUpdateApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
