// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: application_document.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createApplicationDocument = `-- name: CreateApplicationDocument :one
INSERT INTO application_documents (
    id, application_id, document_name, file_url, document_type, uploaded_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, application_id, document_name, file_url, document_type, uploaded_at
`

type CreateApplicationDocumentParams struct {
	ID            uuid.UUID      `json:"id"`
	ApplicationID uuid.UUID      `json:"application_id"`
	DocumentName  string         `json:"document_name"`
	FileUrl       string         `json:"file_url"`
	DocumentType  sql.NullString `json:"document_type"`
	UploadedAt    sql.NullTime   `json:"uploaded_at"`
}

func (q *Queries) CreateApplicationDocument(ctx context.Context, arg CreateApplicationDocumentParams) (ApplicationDocument, error) {
	row := q.db.QueryRowContext(ctx, createApplicationDocument,
		arg.ID,
		arg.ApplicationID,
		arg.DocumentName,
		arg.FileUrl,
		arg.DocumentType,
		arg.UploadedAt,
	)
	var i ApplicationDocument
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentName,
		&i.FileUrl,
		&i.DocumentType,
		&i.UploadedAt,
	)
	return i, err
}

const deleteApplicationDocument = `-- name: DeleteApplicationDocument :exec
DELETE FROM application_documents
WHERE id = $1
`

func (q *Queries) DeleteApplicationDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteApplicationDocument, id)
	return err
}

const listApplicationDocuments = `-- name: ListApplicationDocuments :many
SELECT id, application_id, document_name, file_url, document_type, uploaded_at FROM application_documents
WHERE application_id = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) ListApplicationDocuments(ctx context.Context, applicationID uuid.UUID) ([]ApplicationDocument, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationDocuments, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationDocument
	for rows.Next() {
		var i ApplicationDocument
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.DocumentName,
			&i.FileUrl,
			&i.DocumentType,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
