// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: decision.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCommitteeSession = `-- name: CreateCommitteeSession :one
INSERT INTO application_committee_sessions (
    application_id, session_sequence, status, scheduled_at
) VALUES ($1, $2, 'SCHEDULED', $3) RETURNING id, application_id, session_sequence, status, scheduled_at, started_at, completed_at, created_at
`

type CreateCommitteeSessionParams struct {
	ApplicationID   uuid.UUID     `json:"application_id"`
	SessionSequence sql.NullInt32 `json:"session_sequence"`
	ScheduledAt     sql.NullTime  `json:"scheduled_at"`
}

func (q *Queries) CreateCommitteeSession(ctx context.Context, arg CreateCommitteeSessionParams) (ApplicationCommitteeSession, error) {
	row := q.db.QueryRowContext(ctx, createCommitteeSession, arg.ApplicationID, arg.SessionSequence, arg.ScheduledAt)
	var i ApplicationCommitteeSession
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SessionSequence,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const finalizeCommitteeDecision = `-- name: FinalizeCommitteeDecision :one
INSERT INTO application_committee_decisions (
    committee_session_id, decision, decision_reason, approved_amount, 
    approved_tenor, approved_interest_rate, requires_next_committee
) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, committee_session_id, decision, decision_reason, approved_amount, approved_tenor, approved_interest_rate, requires_next_committee, decided_at
`

type FinalizeCommitteeDecisionParams struct {
	CommitteeSessionID    uuid.UUID      `json:"committee_session_id"`
	Decision              sql.NullString `json:"decision"`
	DecisionReason        sql.NullString `json:"decision_reason"`
	ApprovedAmount        sql.NullString `json:"approved_amount"`
	ApprovedTenor         sql.NullInt32  `json:"approved_tenor"`
	ApprovedInterestRate  sql.NullString `json:"approved_interest_rate"`
	RequiresNextCommittee sql.NullBool   `json:"requires_next_committee"`
}

func (q *Queries) FinalizeCommitteeDecision(ctx context.Context, arg FinalizeCommitteeDecisionParams) (ApplicationCommitteeDecision, error) {
	row := q.db.QueryRowContext(ctx, finalizeCommitteeDecision,
		arg.CommitteeSessionID,
		arg.Decision,
		arg.DecisionReason,
		arg.ApprovedAmount,
		arg.ApprovedTenor,
		arg.ApprovedInterestRate,
		arg.RequiresNextCommittee,
	)
	var i ApplicationCommitteeDecision
	err := row.Scan(
		&i.ID,
		&i.CommitteeSessionID,
		&i.Decision,
		&i.DecisionReason,
		&i.ApprovedAmount,
		&i.ApprovedTenor,
		&i.ApprovedInterestRate,
		&i.RequiresNextCommittee,
		&i.DecidedAt,
	)
	return i, err
}

const getApplicationDecision = `-- name: GetApplicationDecision :one
SELECT id, application_id, decision, decision_source, final_amount, final_tenor, final_interest_rate, decision_reason, decided_by, decided_at FROM application_decisions WHERE application_id = $1 LIMIT 1
`

func (q *Queries) GetApplicationDecision(ctx context.Context, applicationID uuid.UUID) (ApplicationDecision, error) {
	row := q.db.QueryRowContext(ctx, getApplicationDecision, applicationID)
	var i ApplicationDecision
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Decision,
		&i.DecisionSource,
		&i.FinalAmount,
		&i.FinalTenor,
		&i.FinalInterestRate,
		&i.DecisionReason,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const recordFinalDecision = `-- name: RecordFinalDecision :one
INSERT INTO application_decisions (
    application_id, decision, decision_source, final_amount, 
    final_tenor, final_interest_rate, decision_reason, decided_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, application_id, decision, decision_source, final_amount, final_tenor, final_interest_rate, decision_reason, decided_by, decided_at
`

type RecordFinalDecisionParams struct {
	ApplicationID     uuid.UUID      `json:"application_id"`
	Decision          sql.NullString `json:"decision"`
	DecisionSource    sql.NullString `json:"decision_source"`
	FinalAmount       sql.NullString `json:"final_amount"`
	FinalTenor        sql.NullInt32  `json:"final_tenor"`
	FinalInterestRate sql.NullString `json:"final_interest_rate"`
	DecisionReason    sql.NullString `json:"decision_reason"`
	DecidedBy         uuid.NullUUID  `json:"decided_by"`
}

func (q *Queries) RecordFinalDecision(ctx context.Context, arg RecordFinalDecisionParams) (ApplicationDecision, error) {
	row := q.db.QueryRowContext(ctx, recordFinalDecision,
		arg.ApplicationID,
		arg.Decision,
		arg.DecisionSource,
		arg.FinalAmount,
		arg.FinalTenor,
		arg.FinalInterestRate,
		arg.DecisionReason,
		arg.DecidedBy,
	)
	var i ApplicationDecision
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Decision,
		&i.DecisionSource,
		&i.FinalAmount,
		&i.FinalTenor,
		&i.FinalInterestRate,
		&i.DecisionReason,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const submitCommitteeVote = `-- name: SubmitCommitteeVote :one
INSERT INTO application_committee_votes (
    committee_session_id, user_id, vote, vote_reason
) VALUES ($1, $2, $3, $4) RETURNING id, committee_session_id, user_id, vote, vote_reason, voted_at
`

type SubmitCommitteeVoteParams struct {
	CommitteeSessionID uuid.UUID      `json:"committee_session_id"`
	UserID             uuid.UUID      `json:"user_id"`
	Vote               sql.NullString `json:"vote"`
	VoteReason         sql.NullString `json:"vote_reason"`
}

func (q *Queries) SubmitCommitteeVote(ctx context.Context, arg SubmitCommitteeVoteParams) (ApplicationCommitteeVote, error) {
	row := q.db.QueryRowContext(ctx, submitCommitteeVote,
		arg.CommitteeSessionID,
		arg.UserID,
		arg.Vote,
		arg.VoteReason,
	)
	var i ApplicationCommitteeVote
	err := row.Scan(
		&i.ID,
		&i.CommitteeSessionID,
		&i.UserID,
		&i.Vote,
		&i.VoteReason,
		&i.VotedAt,
	)
	return i, err
}
