// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Applicant struct {
	ID                uuid.UUID      `json:"id"`
	ApplicantType     string         `json:"applicant_type"`
	IdentityNumber    sql.NullString `json:"identity_number"`
	TaxID             sql.NullString `json:"tax_id"`
	FullName          sql.NullString `json:"full_name"`
	BirthDate         sql.NullTime   `json:"birth_date"`
	EstablishmentDate sql.NullTime   `json:"establishment_date"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	CreatedBy         uuid.NullUUID  `json:"created_by"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
}

type ApplicantAttribute struct {
	ID          uuid.UUID      `json:"id"`
	ApplicantID uuid.UUID      `json:"applicant_id"`
	AttrKey     string         `json:"attr_key"`
	AttrValue   sql.NullString `json:"attr_value"`
	DataType    sql.NullString `json:"data_type"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Application struct {
	ID                 uuid.UUID      `json:"id"`
	ApplicantID        uuid.UUID      `json:"applicant_id"`
	ProductID          uuid.UUID      `json:"product_id"`
	AoID               uuid.UUID      `json:"ao_id"`
	LoanAmount         sql.NullString `json:"loan_amount"`
	TenorMonths        sql.NullInt32  `json:"tenor_months"`
	InterestType       sql.NullString `json:"interest_type"`
	InterestRate       sql.NullString `json:"interest_rate"`
	LoanPurpose        sql.NullString `json:"loan_purpose"`
	ApplicationChannel sql.NullString `json:"application_channel"`
	Status             string         `json:"status"`
	BranchCode         string         `json:"branch_code"`
	SubmittedAt        sql.NullTime   `json:"submitted_at"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	CreatedBy          uuid.NullUUID  `json:"created_by"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
}

type ApplicationAsset struct {
	ID              uuid.UUID      `json:"id"`
	ApplicationID   uuid.UUID      `json:"application_id"`
	AssetTypeCode   sql.NullString `json:"asset_type_code"`
	AssetName       sql.NullString `json:"asset_name"`
	OwnershipStatus sql.NullString `json:"ownership_status"`
	AcquisitionYear sql.NullInt32  `json:"acquisition_year"`
	EstimatedValue  sql.NullString `json:"estimated_value"`
	ValuationMethod sql.NullString `json:"valuation_method"`
	LocationText    sql.NullString `json:"location_text"`
	Encumbered      sql.NullBool   `json:"encumbered"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type ApplicationAttribute struct {
	ID            uuid.UUID      `json:"id"`
	ApplicationID uuid.UUID      `json:"application_id"`
	AttrKey       string         `json:"attr_key"`
	AttrValue     sql.NullString `json:"attr_value"`
	DataType      sql.NullString `json:"data_type"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type ApplicationCommitteeDecision struct {
	ID                    uuid.UUID      `json:"id"`
	CommitteeSessionID    uuid.UUID      `json:"committee_session_id"`
	Decision              sql.NullString `json:"decision"`
	DecisionReason        sql.NullString `json:"decision_reason"`
	ApprovedAmount        sql.NullString `json:"approved_amount"`
	ApprovedTenor         sql.NullInt32  `json:"approved_tenor"`
	ApprovedInterestRate  sql.NullString `json:"approved_interest_rate"`
	RequiresNextCommittee sql.NullBool   `json:"requires_next_committee"`
	DecidedAt             sql.NullTime   `json:"decided_at"`
}

type ApplicationCommitteeSession struct {
	ID              uuid.UUID      `json:"id"`
	ApplicationID   uuid.UUID      `json:"application_id"`
	SessionSequence sql.NullInt32  `json:"session_sequence"`
	Status          sql.NullString `json:"status"`
	ScheduledAt     sql.NullTime   `json:"scheduled_at"`
	StartedAt       sql.NullTime   `json:"started_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type ApplicationCommitteeVote struct {
	ID                 uuid.UUID      `json:"id"`
	CommitteeSessionID uuid.UUID      `json:"committee_session_id"`
	UserID             uuid.UUID      `json:"user_id"`
	Vote               sql.NullString `json:"vote"`
	VoteReason         sql.NullString `json:"vote_reason"`
	VotedAt            sql.NullTime   `json:"voted_at"`
}

type ApplicationDecision struct {
	ID                uuid.UUID      `json:"id"`
	ApplicationID     uuid.UUID      `json:"application_id"`
	Decision          sql.NullString `json:"decision"`
	DecisionSource    sql.NullString `json:"decision_source"`
	FinalAmount       sql.NullString `json:"final_amount"`
	FinalTenor        sql.NullInt32  `json:"final_tenor"`
	FinalInterestRate sql.NullString `json:"final_interest_rate"`
	DecisionReason    sql.NullString `json:"decision_reason"`
	DecidedBy         uuid.NullUUID  `json:"decided_by"`
	DecidedAt         sql.NullTime   `json:"decided_at"`
}

type ApplicationDecisionCondition struct {
	ID                    uuid.UUID      `json:"id"`
	ApplicationDecisionID uuid.UUID      `json:"application_decision_id"`
	ConditionType         sql.NullString `json:"condition_type"`
	ConditionText         sql.NullString `json:"condition_text"`
	Mandatory             sql.NullBool   `json:"mandatory"`
}

type ApplicationDocument struct {
	ID            uuid.UUID      `json:"id"`
	ApplicationID uuid.UUID      `json:"application_id"`
	DocumentName  string         `json:"document_name"`
	FileUrl       string         `json:"file_url"`
	DocumentType  sql.NullString `json:"document_type"`
	UploadedAt    sql.NullTime   `json:"uploaded_at"`
}

type ApplicationFinancialFact struct {
	ID              uuid.UUID      `json:"id"`
	ApplicationID   uuid.UUID      `json:"application_id"`
	GlCode          string         `json:"gl_code"`
	PeriodType      string         `json:"period_type"`
	PeriodLabel     string         `json:"period_label"`
	Amount          string         `json:"amount"`
	Source          sql.NullString `json:"source"`
	ConfidenceLevel sql.NullString `json:"confidence_level"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type ApplicationFinancialRatio struct {
	ID                 uuid.UUID      `json:"id"`
	ApplicationID      uuid.UUID      `json:"application_id"`
	RatioCode          sql.NullString `json:"ratio_code"`
	RatioValue         sql.NullString `json:"ratio_value"`
	CalculationVersion sql.NullString `json:"calculation_version"`
	CalculatedAt       sql.NullTime   `json:"calculated_at"`
}

type ApplicationLiability struct {
	ID                 uuid.UUID      `json:"id"`
	ApplicationID      uuid.UUID      `json:"application_id"`
	CreditorName       sql.NullString `json:"creditor_name"`
	LiabilityType      sql.NullString `json:"liability_type"`
	OutstandingAmount  sql.NullString `json:"outstanding_amount"`
	MonthlyInstallment sql.NullString `json:"monthly_installment"`
	InterestRate       sql.NullString `json:"interest_rate"`
	MaturityDate       sql.NullTime   `json:"maturity_date"`
	Source             sql.NullString `json:"source"`
	CreatedAt          sql.NullTime   `json:"created_at"`
}

type ApplicationParty struct {
	ApplicationID   uuid.UUID    `json:"application_id"`
	PartyID         uuid.UUID    `json:"party_id"`
	RoleCode        string       `json:"role_code"`
	LegalObligation sql.NullBool `json:"legal_obligation"`
	SlikRequired    sql.NullBool `json:"slik_required"`
}

type ApplicationStatusLog struct {
	ID            uuid.UUID      `json:"id"`
	ApplicationID uuid.UUID      `json:"application_id"`
	FromStatus    sql.NullString `json:"from_status"`
	ToStatus      sql.NullString `json:"to_status"`
	ChangedBy     uuid.NullUUID  `json:"changed_by"`
	ChangeReason  sql.NullString `json:"change_reason"`
	ChangedAt     sql.NullTime   `json:"changed_at"`
}

type ApplicationStatusRef struct {
	StatusCode  string         `json:"status_code"`
	StatusGroup sql.NullString `json:"status_group"`
	IsTerminal  sql.NullBool   `json:"is_terminal"`
	Description sql.NullString `json:"description"`
}

type ApplicationSurvey struct {
	ID            uuid.UUID      `json:"id"`
	ApplicationID uuid.NullUUID  `json:"application_id"`
	TemplateID    uuid.NullUUID  `json:"template_id"`
	SurveyType    sql.NullString `json:"survey_type"`
	Status        sql.NullString `json:"status"`
	SubmittedBy   uuid.NullUUID  `json:"submitted_by"`
	VerifiedBy    uuid.NullUUID  `json:"verified_by"`
	VerifiedAt    sql.NullTime   `json:"verified_at"`
	AssignedTo    uuid.NullUUID  `json:"assigned_to"`
	SurveyPurpose sql.NullString `json:"survey_purpose"`
	StartedAt     sql.NullTime   `json:"started_at"`
	SubmittedAt   sql.NullTime   `json:"submitted_at"`
}

type AssetType struct {
	AssetTypeCode string         `json:"asset_type_code"`
	AssetCategory sql.NullString `json:"asset_category"`
	Description   sql.NullString `json:"description"`
}

type Branch struct {
	BranchCode string         `json:"branch_code"`
	BranchName sql.NullString `json:"branch_name"`
	RegionCode sql.NullString `json:"region_code"`
}

type CreditAuthorityMatrix struct {
	ID                uuid.UUID      `json:"id"`
	CommitteeLevel    sql.NullInt32  `json:"committee_level"`
	ProductID         uuid.NullUUID  `json:"product_id"`
	MaxAmount         sql.NullString `json:"max_amount"`
	MaxTenor          sql.NullInt32  `json:"max_tenor"`
	RequiresCommittee sql.NullBool   `json:"requires_committee"`
}

type CreditCommitteeMember struct {
	CommitteeSessionID uuid.UUID      `json:"committee_session_id"`
	UserID             uuid.UUID      `json:"user_id"`
	Role               sql.NullString `json:"role"`
	Active             sql.NullBool   `json:"active"`
}

type CustomColumnAttributeRegistry struct {
	AttributeCode string         `json:"attribute_code"`
	AppliesTo     string         `json:"applies_to"`
	Scope         string         `json:"scope"`
	ValueType     string         `json:"value_type"`
	RiskRelevant  sql.NullBool   `json:"risk_relevant"`
	Description   sql.NullString `json:"description"`
}

type FinancialGlAccount struct {
	GlCode        string         `json:"gl_code"`
	GlName        sql.NullString `json:"gl_name"`
	StatementType string         `json:"statement_type"`
	Category      string         `json:"category"`
	Sign          int32          `json:"sign"`
	IsDebtService sql.NullBool   `json:"is_debt_service"`
	IsOperating   sql.NullBool   `json:"is_operating"`
	Description   sql.NullString `json:"description"`
}

type LoanOfficer struct {
	ID          uuid.UUID      `json:"id"`
	OfficerCode sql.NullString `json:"officer_code"`
	BranchCode  string         `json:"branch_code"`
}

type LoanProduct struct {
	ID             uuid.UUID      `json:"id"`
	ProductCode    sql.NullString `json:"product_code"`
	ProductName    sql.NullString `json:"product_name"`
	Segment        sql.NullString `json:"segment"`
	Active         sql.NullBool   `json:"active"`
	AssignmentMode sql.NullString `json:"assignment_mode"`
}

type Party struct {
	ID          uuid.UUID      `json:"id"`
	PartyType   sql.NullString `json:"party_type"`
	Identifier  sql.NullString `json:"identifier"`
	Name        sql.NullString `json:"name"`
	DateOfBirth sql.NullTime   `json:"date_of_birth"`
}

type ProductStatusFlow struct {
	ProductID    uuid.UUID      `json:"product_id"`
	FromStatus   string         `json:"from_status"`
	ToStatus     string         `json:"to_status"`
	IsDefault    sql.NullBool   `json:"is_default"`
	RequiresRole sql.NullString `json:"requires_role"`
}

type SurveyAnswer struct {
	ID            uuid.UUID      `json:"id"`
	SurveyID      uuid.NullUUID  `json:"survey_id"`
	QuestionID    uuid.NullUUID  `json:"question_id"`
	AnswerText    sql.NullString `json:"answer_text"`
	AnswerNumber  sql.NullString `json:"answer_number"`
	AnswerBoolean sql.NullBool   `json:"answer_boolean"`
	AnswerDate    sql.NullTime   `json:"answer_date"`
	AnsweredAt    sql.NullTime   `json:"answered_at"`
}

type SurveyDataMapping struct {
	ID            uuid.UUID      `json:"id"`
	QuestionID    uuid.UUID      `json:"question_id"`
	TargetType    string         `json:"target_type"`
	TargetCode    string         `json:"target_code"`
	TransformRule sql.NullString `json:"transform_rule"`
}

type SurveyEvidence struct {
	ID           uuid.UUID      `json:"id"`
	SurveyID     uuid.NullUUID  `json:"survey_id"`
	EvidenceType sql.NullString `json:"evidence_type"`
	FileUrl      sql.NullString `json:"file_url"`
	Description  sql.NullString `json:"description"`
	CapturedAt   sql.NullTime   `json:"captured_at"`
}

type SurveyQuestion struct {
	ID           uuid.UUID      `json:"id"`
	SectionID    uuid.NullUUID  `json:"section_id"`
	QuestionCode sql.NullString `json:"question_code"`
	QuestionText sql.NullString `json:"question_text"`
	AnswerType   sql.NullString `json:"answer_type"`
	IsMandatory  sql.NullBool   `json:"is_mandatory"`
	RiskRelevant sql.NullBool   `json:"risk_relevant"`
	Sequence     sql.NullInt32  `json:"sequence"`
}

type SurveyQuestionOption struct {
	ID          uuid.UUID      `json:"id"`
	QuestionID  uuid.NullUUID  `json:"question_id"`
	OptionValue sql.NullString `json:"option_value"`
	OptionLabel sql.NullString `json:"option_label"`
	Sequence    sql.NullInt32  `json:"sequence"`
}

type SurveySection struct {
	ID          uuid.UUID      `json:"id"`
	TemplateID  uuid.NullUUID  `json:"template_id"`
	SectionCode sql.NullString `json:"section_code"`
	SectionName sql.NullString `json:"section_name"`
	Sequence    sql.NullInt32  `json:"sequence"`
}

type SurveyTemplate struct {
	ID           uuid.UUID      `json:"id"`
	TemplateCode sql.NullString `json:"template_code"`
	TemplateName sql.NullString `json:"template_name"`
	HeadType     sql.NullString `json:"head_type"`
	ProductID    uuid.NullUUID  `json:"product_id"`
	Active       sql.NullBool   `json:"active"`
}
