// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignSurvey(ctx context.Context, arg AssignSurveyParams) (ApplicationSurvey, error)
	CreateApplicant(ctx context.Context, arg CreateApplicantParams) (Applicant, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateApplicationDocument(ctx context.Context, arg CreateApplicationDocumentParams) (ApplicationDocument, error)
	CreateApplicationParty(ctx context.Context, arg CreateApplicationPartyParams) (ApplicationParty, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (ApplicationAsset, error)
	CreateAttributeRegistry(ctx context.Context, arg CreateAttributeRegistryParams) error
	CreateCommitteeSession(ctx context.Context, arg CreateCommitteeSessionParams) (ApplicationCommitteeSession, error)
	CreateLiability(ctx context.Context, arg CreateLiabilityParams) (ApplicationLiability, error)
	CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error)
	CreateStatusLog(ctx context.Context, arg CreateStatusLogParams) (ApplicationStatusLog, error)
	CreateSurveyEvidence(ctx context.Context, arg CreateSurveyEvidenceParams) (SurveyEvidence, error)
	CreateSurveyTemplate(ctx context.Context, arg CreateSurveyTemplateParams) (SurveyTemplate, error)
	DeleteApplicantAttributes(ctx context.Context, applicantID uuid.UUID) error
	DeleteApplicationAttributes(ctx context.Context, applicationID uuid.UUID) error
	DeleteApplicationDocument(ctx context.Context, id uuid.UUID) error
	FinalizeCommitteeDecision(ctx context.Context, arg FinalizeCommitteeDecisionParams) (ApplicationCommitteeDecision, error)
	GetApplicant(ctx context.Context, id uuid.UUID) (Applicant, error)
	GetApplicantAttributes(ctx context.Context, applicantID uuid.UUID) ([]ApplicantAttribute, error)
	GetApplication(ctx context.Context, id uuid.UUID) (Application, error)
	GetApplicationAttributes(ctx context.Context, applicationID uuid.UUID) ([]ApplicationAttribute, error)
	GetApplicationDecision(ctx context.Context, applicationID uuid.UUID) (ApplicationDecision, error)
	GetLoanProduct(ctx context.Context, id uuid.UUID) (LoanProduct, error)
	GetPartiesByApplication(ctx context.Context, applicationID uuid.UUID) ([]GetPartiesByApplicationRow, error)
	GetSurvey(ctx context.Context, id uuid.UUID) (ApplicationSurvey, error)
	GetSurveyTemplateWithSections(ctx context.Context, id uuid.UUID) ([]GetSurveyTemplateWithSectionsRow, error)
	ListApplicantAttributesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ApplicantAttribute, error)
	ListApplicants(ctx context.Context, arg ListApplicantsParams) ([]Applicant, error)
	ListApplicationAttributesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ApplicationAttribute, error)
	ListApplicationDocuments(ctx context.Context, applicationID uuid.UUID) ([]ApplicationDocument, error)
	ListApplicationStatuses(ctx context.Context) ([]ApplicationStatusRef, error)
	ListApplications(ctx context.Context, arg ListApplicationsParams) ([]Application, error)
	ListAssets(ctx context.Context, applicationID uuid.UUID) ([]ApplicationAsset, error)
	ListAttributeRegistry(ctx context.Context) ([]CustomColumnAttributeRegistry, error)
	ListBranches(ctx context.Context) ([]Branch, error)
	ListFinancialFacts(ctx context.Context, applicationID uuid.UUID) ([]ApplicationFinancialFact, error)
	ListFinancialGLAccounts(ctx context.Context) ([]FinancialGlAccount, error)
	ListGLAccounts(ctx context.Context) ([]FinancialGlAccount, error)
	ListLiabilities(ctx context.Context, applicationID uuid.UUID) ([]ApplicationLiability, error)
	ListLoanOfficers(ctx context.Context, branchCode string) ([]LoanOfficer, error)
	ListLoanProducts(ctx context.Context) ([]LoanProduct, error)
	ListStatusLogs(ctx context.Context, applicationID uuid.UUID) ([]ApplicationStatusLog, error)
	ListSurveyTemplates(ctx context.Context) ([]SurveyTemplate, error)
	ListSurveysByApplication(ctx context.Context, applicationID uuid.NullUUID) ([]ApplicationSurvey, error)
	RecordFinalDecision(ctx context.Context, arg RecordFinalDecisionParams) (ApplicationDecision, error)
	SoftDeleteApplication(ctx context.Context, id uuid.UUID) error
	SubmitCommitteeVote(ctx context.Context, arg SubmitCommitteeVoteParams) (ApplicationCommitteeVote, error)
	UpdateApplicant(ctx context.Context, arg UpdateApplicantParams) (Applicant, error)
	UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (ApplicationAsset, error)
	UpdateLiability(ctx context.Context, arg UpdateLiabilityParams) (ApplicationLiability, error)
	UpdateSurveyStatus(ctx context.Context, arg UpdateSurveyStatusParams) (ApplicationSurvey, error)
	UpsertApplicantAttribute(ctx context.Context, arg UpsertApplicantAttributeParams) (ApplicantAttribute, error)
	UpsertApplicationAttribute(ctx context.Context, arg UpsertApplicationAttributeParams) (ApplicationAttribute, error)
	UpsertFinancialFact(ctx context.Context, arg UpsertFinancialFactParams) (ApplicationFinancialFact, error)
	UpsertFinancialRatio(ctx context.Context, arg UpsertFinancialRatioParams) (ApplicationFinancialRatio, error)
	UpsertSurveyAnswer(ctx context.Context, arg UpsertSurveyAnswerParams) (SurveyAnswer, error)
}

var _ Querier = (*Queries)(nil)
