// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: reference.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getLoanProduct = `-- name: GetLoanProduct :one
SELECT id, product_code, product_name, segment, active, assignment_mode FROM loan_products WHERE id = $1
`

func (q *Queries) GetLoanProduct(ctx context.Context, id uuid.UUID) (LoanProduct, error) {
	row := q.db.QueryRowContext(ctx, getLoanProduct, id)
	var i LoanProduct
	err := row.Scan(
		&i.ID,
		&i.ProductCode,
		&i.ProductName,
		&i.Segment,
		&i.Active,
		&i.AssignmentMode,
	)
	return i, err
}

const listApplicationStatuses = `-- name: ListApplicationStatuses :many
SELECT status_code, status_group, is_terminal, description FROM application_status_refs
`

func (q *Queries) ListApplicationStatuses(ctx context.Context) ([]ApplicationStatusRef, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationStatusRef
	for rows.Next() {
		var i ApplicationStatusRef
		if err := rows.Scan(
			&i.StatusCode,
			&i.StatusGroup,
			&i.IsTerminal,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranches = `-- name: ListBranches :many
SELECT branch_code, branch_name, region_code FROM branches
`

func (q *Queries) ListBranches(ctx context.Context) ([]Branch, error) {
	rows, err := q.db.QueryContext(ctx, listBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(&i.BranchCode, &i.BranchName, &i.RegionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinancialGLAccounts = `-- name: ListFinancialGLAccounts :many
SELECT gl_code, gl_name, statement_type, category, sign, is_debt_service, is_operating, description FROM financial_gl_accounts
`

func (q *Queries) ListFinancialGLAccounts(ctx context.Context) ([]FinancialGlAccount, error) {
	rows, err := q.db.QueryContext(ctx, listFinancialGLAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinancialGlAccount
	for rows.Next() {
		var i FinancialGlAccount
		if err := rows.Scan(
			&i.GlCode,
			&i.GlName,
			&i.StatementType,
			&i.Category,
			&i.Sign,
			&i.IsDebtService,
			&i.IsOperating,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoanOfficers = `-- name: ListLoanOfficers :many
SELECT id, officer_code, branch_code FROM loan_officers WHERE branch_code = $1
`

func (q *Queries) ListLoanOfficers(ctx context.Context, branchCode string) ([]LoanOfficer, error) {
	rows, err := q.db.QueryContext(ctx, listLoanOfficers, branchCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanOfficer
	for rows.Next() {
		var i LoanOfficer
		if err := rows.Scan(&i.ID, &i.OfficerCode, &i.BranchCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoanProducts = `-- name: ListLoanProducts :many
SELECT id, product_code, product_name, segment, active, assignment_mode FROM loan_products WHERE active = TRUE
`

func (q *Queries) ListLoanProducts(ctx context.Context) ([]LoanProduct, error) {
	rows, err := q.db.QueryContext(ctx, listLoanProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanProduct
	for rows.Next() {
		var i LoanProduct
		if err := rows.Scan(
			&i.ID,
			&i.ProductCode,
			&i.ProductName,
			&i.Segment,
			&i.Active,
			&i.AssignmentMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
