// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/financial/v1/financial.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Financial_ListFinancialFacts_FullMethodName   = "/api.financial.v1.Financial/ListFinancialFacts"
	Financial_UpsertFinancialFact_FullMethodName  = "/api.financial.v1.Financial/UpsertFinancialFact"
	Financial_CreateAsset_FullMethodName          = "/api.financial.v1.Financial/CreateAsset"
	Financial_ListAssets_FullMethodName           = "/api.financial.v1.Financial/ListAssets"
	Financial_CreateLiability_FullMethodName      = "/api.financial.v1.Financial/CreateLiability"
	Financial_ListLiabilities_FullMethodName      = "/api.financial.v1.Financial/ListLiabilities"
	Financial_UpsertFinancialRatio_FullMethodName = "/api.financial.v1.Financial/UpsertFinancialRatio"
)

// FinancialClient is the client API for Financial service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinancialClient interface {
	ListFinancialFacts(ctx context.Context, in *ListFinancialFactsRequest, opts ...grpc.CallOption) (*ListFinancialFactsReply, error)
	UpsertFinancialFact(ctx context.Context, in *UpsertFinancialFactRequest, opts ...grpc.CallOption) (*FinancialFact, error)
	CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*Asset, error)
	ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*ListAssetsReply, error)
	CreateLiability(ctx context.Context, in *CreateLiabilityRequest, opts ...grpc.CallOption) (*Liability, error)
	ListLiabilities(ctx context.Context, in *ListLiabilitiesRequest, opts ...grpc.CallOption) (*ListLiabilitiesReply, error)
	UpsertFinancialRatio(ctx context.Context, in *UpsertFinancialRatioRequest, opts ...grpc.CallOption) (*FinancialRatio, error)
}

type financialClient struct {
	cc grpc.ClientConnInterface
}

func NewFinancialClient(cc grpc.ClientConnInterface) FinancialClient {
	return &financialClient{cc}
}

func (c *financialClient) ListFinancialFacts(ctx context.Context, in *ListFinancialFactsRequest, opts ...grpc.CallOption) (*ListFinancialFactsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFinancialFactsReply)
	err := c.cc.Invoke(ctx, Financial_ListFinancialFacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialClient) UpsertFinancialFact(ctx context.Context, in *UpsertFinancialFactRequest, opts ...grpc.CallOption) (*FinancialFact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinancialFact)
	err := c.cc.Invoke(ctx, Financial_UpsertFinancialFact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialClient) CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, Financial_CreateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialClient) ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*ListAssetsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssetsReply)
	err := c.cc.Invoke(ctx, Financial_ListAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialClient) CreateLiability(ctx context.Context, in *CreateLiabilityRequest, opts ...grpc.CallOption) (*Liability, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Liability)
	err := c.cc.Invoke(ctx, Financial_CreateLiability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialClient) ListLiabilities(ctx context.Context, in *ListLiabilitiesRequest, opts ...grpc.CallOption) (*ListLiabilitiesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLiabilitiesReply)
	err := c.cc.Invoke(ctx, Financial_ListLiabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialClient) UpsertFinancialRatio(ctx context.Context, in *UpsertFinancialRatioRequest, opts ...grpc.CallOption) (*FinancialRatio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinancialRatio)
	err := c.cc.Invoke(ctx, Financial_UpsertFinancialRatio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinancialServer is the server API for Financial service.
// All implementations must embed UnimplementedFinancialServer
// for forward compatibility.
type FinancialServer interface {
	ListFinancialFacts(context.Context, *ListFinancialFactsRequest) (*ListFinancialFactsReply, error)
	UpsertFinancialFact(context.Context, *UpsertFinancialFactRequest) (*FinancialFact, error)
	CreateAsset(context.Context, *CreateAssetRequest) (*Asset, error)
	ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsReply, error)
	CreateLiability(context.Context, *CreateLiabilityRequest) (*Liability, error)
	ListLiabilities(context.Context, *ListLiabilitiesRequest) (*ListLiabilitiesReply, error)
	UpsertFinancialRatio(context.Context, *UpsertFinancialRatioRequest) (*FinancialRatio, error)
	mustEmbedUnimplementedFinancialServer()
}

// UnimplementedFinancialServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinancialServer struct{}

func (UnimplementedFinancialServer) ListFinancialFacts(context.Context, *ListFinancialFactsRequest) (*ListFinancialFactsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFinancialFacts not implemented")
}
func (UnimplementedFinancialServer) UpsertFinancialFact(context.Context, *UpsertFinancialFactRequest) (*FinancialFact, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertFinancialFact not implemented")
}
func (UnimplementedFinancialServer) CreateAsset(context.Context, *CreateAssetRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAsset not implemented")
}
func (UnimplementedFinancialServer) ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssets not implemented")
}
func (UnimplementedFinancialServer) CreateLiability(context.Context, *CreateLiabilityRequest) (*Liability, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLiability not implemented")
}
func (UnimplementedFinancialServer) ListLiabilities(context.Context, *ListLiabilitiesRequest) (*ListLiabilitiesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLiabilities not implemented")
}
func (UnimplementedFinancialServer) UpsertFinancialRatio(context.Context, *UpsertFinancialRatioRequest) (*FinancialRatio, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertFinancialRatio not implemented")
}
func (UnimplementedFinancialServer) mustEmbedUnimplementedFinancialServer() {}
func (UnimplementedFinancialServer) testEmbeddedByValue()                   {}

// UnsafeFinancialServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinancialServer will
// result in compilation errors.
type UnsafeFinancialServer interface {
	mustEmbedUnimplementedFinancialServer()
}

func RegisterFinancialServer(s grpc.ServiceRegistrar, srv FinancialServer) {
	// If the following call panics, it indicates UnimplementedFinancialServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Financial_ServiceDesc, srv)
}

func _Financial_ListFinancialFacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFinancialFactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServer).ListFinancialFacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Financial_ListFinancialFacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServer).ListFinancialFacts(ctx, req.(*ListFinancialFactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Financial_UpsertFinancialFact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertFinancialFactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServer).UpsertFinancialFact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Financial_UpsertFinancialFact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServer).UpsertFinancialFact(ctx, req.(*UpsertFinancialFactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Financial_CreateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServer).CreateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Financial_CreateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServer).CreateAsset(ctx, req.(*CreateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Financial_ListAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServer).ListAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Financial_ListAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServer).ListAssets(ctx, req.(*ListAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Financial_CreateLiability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLiabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServer).CreateLiability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Financial_CreateLiability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServer).CreateLiability(ctx, req.(*CreateLiabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Financial_ListLiabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLiabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServer).ListLiabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Financial_ListLiabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServer).ListLiabilities(ctx, req.(*ListLiabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Financial_UpsertFinancialRatio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertFinancialRatioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServer).UpsertFinancialRatio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Financial_UpsertFinancialRatio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServer).UpsertFinancialRatio(ctx, req.(*UpsertFinancialRatioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Financial_ServiceDesc is the grpc.ServiceDesc for Financial service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Financial_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.financial.v1.Financial",
	HandlerType: (*FinancialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFinancialFacts",
			Handler:    _Financial_ListFinancialFacts_Handler,
		},
		{
			MethodName: "UpsertFinancialFact",
			Handler:    _Financial_UpsertFinancialFact_Handler,
		},
		{
			MethodName: "CreateAsset",
			Handler:    _Financial_CreateAsset_Handler,
		},
		{
			MethodName: "ListAssets",
			Handler:    _Financial_ListAssets_Handler,
		},
		{
			MethodName: "CreateLiability",
			Handler:    _Financial_CreateLiability_Handler,
		},
		{
			MethodName: "ListLiabilities",
			Handler:    _Financial_ListLiabilities_Handler,
		},
		{
			MethodName: "UpsertFinancialRatio",
			Handler:    _Financial_UpsertFinancialRatio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/financial/v1/financial.proto",
}
