// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/financial/v1/financial.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinancialFact struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId   string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	GlCode          string                 `protobuf:"bytes,3,opt,name=gl_code,json=glCode,proto3" json:"gl_code,omitempty"`
	PeriodType      string                 `protobuf:"bytes,4,opt,name=period_type,json=periodType,proto3" json:"period_type,omitempty"`
	PeriodLabel     string                 `protobuf:"bytes,5,opt,name=period_label,json=periodLabel,proto3" json:"period_label,omitempty"`
	Amount          string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Source          string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	ConfidenceLevel string                 `protobuf:"bytes,8,opt,name=confidence_level,json=confidenceLevel,proto3" json:"confidence_level,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FinancialFact) Reset() {
	*x = FinancialFact{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialFact) ProtoMessage() {}

func (x *FinancialFact) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialFact.ProtoReflect.Descriptor instead.
func (*FinancialFact) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{0}
}

func (x *FinancialFact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FinancialFact) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *FinancialFact) GetGlCode() string {
	if x != nil {
		return x.GlCode
	}
	return ""
}

func (x *FinancialFact) GetPeriodType() string {
	if x != nil {
		return x.PeriodType
	}
	return ""
}

func (x *FinancialFact) GetPeriodLabel() string {
	if x != nil {
		return x.PeriodLabel
	}
	return ""
}

func (x *FinancialFact) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FinancialFact) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FinancialFact) GetConfidenceLevel() string {
	if x != nil {
		return x.ConfidenceLevel
	}
	return ""
}

func (x *FinancialFact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Asset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId   string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	AssetTypeCode   string                 `protobuf:"bytes,3,opt,name=asset_type_code,json=assetTypeCode,proto3" json:"asset_type_code,omitempty"`
	AssetName       string                 `protobuf:"bytes,4,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	OwnershipStatus string                 `protobuf:"bytes,5,opt,name=ownership_status,json=ownershipStatus,proto3" json:"ownership_status,omitempty"`
	AcquisitionYear int32                  `protobuf:"varint,6,opt,name=acquisition_year,json=acquisitionYear,proto3" json:"acquisition_year,omitempty"`
	EstimatedValue  string                 `protobuf:"bytes,7,opt,name=estimated_value,json=estimatedValue,proto3" json:"estimated_value,omitempty"`
	ValuationMethod string                 `protobuf:"bytes,8,opt,name=valuation_method,json=valuationMethod,proto3" json:"valuation_method,omitempty"`
	LocationText    string                 `protobuf:"bytes,9,opt,name=location_text,json=locationText,proto3" json:"location_text,omitempty"`
	Encumbered      bool                   `protobuf:"varint,10,opt,name=encumbered,proto3" json:"encumbered,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Asset) GetAssetTypeCode() string {
	if x != nil {
		return x.AssetTypeCode
	}
	return ""
}

func (x *Asset) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *Asset) GetOwnershipStatus() string {
	if x != nil {
		return x.OwnershipStatus
	}
	return ""
}

func (x *Asset) GetAcquisitionYear() int32 {
	if x != nil {
		return x.AcquisitionYear
	}
	return 0
}

func (x *Asset) GetEstimatedValue() string {
	if x != nil {
		return x.EstimatedValue
	}
	return ""
}

func (x *Asset) GetValuationMethod() string {
	if x != nil {
		return x.ValuationMethod
	}
	return ""
}

func (x *Asset) GetLocationText() string {
	if x != nil {
		return x.LocationText
	}
	return ""
}

func (x *Asset) GetEncumbered() bool {
	if x != nil {
		return x.Encumbered
	}
	return false
}

type Liability struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId      string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	CreditorName       string                 `protobuf:"bytes,3,opt,name=creditor_name,json=creditorName,proto3" json:"creditor_name,omitempty"`
	LiabilityType      string                 `protobuf:"bytes,4,opt,name=liability_type,json=liabilityType,proto3" json:"liability_type,omitempty"`
	OutstandingAmount  string                 `protobuf:"bytes,5,opt,name=outstanding_amount,json=outstandingAmount,proto3" json:"outstanding_amount,omitempty"`
	MonthlyInstallment string                 `protobuf:"bytes,6,opt,name=monthly_installment,json=monthlyInstallment,proto3" json:"monthly_installment,omitempty"`
	InterestRate       string                 `protobuf:"bytes,7,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	MaturityDate       string                 `protobuf:"bytes,8,opt,name=maturity_date,json=maturityDate,proto3" json:"maturity_date,omitempty"`
	Source             string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Liability) Reset() {
	*x = Liability{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Liability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Liability) ProtoMessage() {}

func (x *Liability) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Liability.ProtoReflect.Descriptor instead.
func (*Liability) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{2}
}

func (x *Liability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Liability) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Liability) GetCreditorName() string {
	if x != nil {
		return x.CreditorName
	}
	return ""
}

func (x *Liability) GetLiabilityType() string {
	if x != nil {
		return x.LiabilityType
	}
	return ""
}

func (x *Liability) GetOutstandingAmount() string {
	if x != nil {
		return x.OutstandingAmount
	}
	return ""
}

func (x *Liability) GetMonthlyInstallment() string {
	if x != nil {
		return x.MonthlyInstallment
	}
	return ""
}

func (x *Liability) GetInterestRate() string {
	if x != nil {
		return x.InterestRate
	}
	return ""
}

func (x *Liability) GetMaturityDate() string {
	if x != nil {
		return x.MaturityDate
	}
	return ""
}

func (x *Liability) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type FinancialRatio struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId      string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	RatioCode          string                 `protobuf:"bytes,3,opt,name=ratio_code,json=ratioCode,proto3" json:"ratio_code,omitempty"`
	RatioValue         string                 `protobuf:"bytes,4,opt,name=ratio_value,json=ratioValue,proto3" json:"ratio_value,omitempty"`
	CalculationVersion string                 `protobuf:"bytes,5,opt,name=calculation_version,json=calculationVersion,proto3" json:"calculation_version,omitempty"`
	CalculatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=calculated_at,json=calculatedAt,proto3" json:"calculated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FinancialRatio) Reset() {
	*x = FinancialRatio{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialRatio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialRatio) ProtoMessage() {}

func (x *FinancialRatio) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialRatio.ProtoReflect.Descriptor instead.
func (*FinancialRatio) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{3}
}

func (x *FinancialRatio) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FinancialRatio) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *FinancialRatio) GetRatioCode() string {
	if x != nil {
		return x.RatioCode
	}
	return ""
}

func (x *FinancialRatio) GetRatioValue() string {
	if x != nil {
		return x.RatioValue
	}
	return ""
}

func (x *FinancialRatio) GetCalculationVersion() string {
	if x != nil {
		return x.CalculationVersion
	}
	return ""
}

func (x *FinancialRatio) GetCalculatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculatedAt
	}
	return nil
}

type ListFinancialFactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFinancialFactsRequest) Reset() {
	*x = ListFinancialFactsRequest{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFinancialFactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFinancialFactsRequest) ProtoMessage() {}

func (x *ListFinancialFactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFinancialFactsRequest.ProtoReflect.Descriptor instead.
func (*ListFinancialFactsRequest) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{4}
}

func (x *ListFinancialFactsRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListFinancialFactsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facts         []*FinancialFact       `protobuf:"bytes,1,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFinancialFactsReply) Reset() {
	*x = ListFinancialFactsReply{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFinancialFactsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFinancialFactsReply) ProtoMessage() {}

func (x *ListFinancialFactsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFinancialFactsReply.ProtoReflect.Descriptor instead.
func (*ListFinancialFactsReply) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{5}
}

func (x *ListFinancialFactsReply) GetFacts() []*FinancialFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

type UpsertFinancialFactRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId   string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	GlCode          string                 `protobuf:"bytes,2,opt,name=gl_code,json=glCode,proto3" json:"gl_code,omitempty"`
	PeriodType      string                 `protobuf:"bytes,3,opt,name=period_type,json=periodType,proto3" json:"period_type,omitempty"`
	PeriodLabel     string                 `protobuf:"bytes,4,opt,name=period_label,json=periodLabel,proto3" json:"period_label,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Source          string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	ConfidenceLevel string                 `protobuf:"bytes,7,opt,name=confidence_level,json=confidenceLevel,proto3" json:"confidence_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpsertFinancialFactRequest) Reset() {
	*x = UpsertFinancialFactRequest{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFinancialFactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFinancialFactRequest) ProtoMessage() {}

func (x *UpsertFinancialFactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFinancialFactRequest.ProtoReflect.Descriptor instead.
func (*UpsertFinancialFactRequest) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertFinancialFactRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetGlCode() string {
	if x != nil {
		return x.GlCode
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetPeriodType() string {
	if x != nil {
		return x.PeriodType
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetPeriodLabel() string {
	if x != nil {
		return x.PeriodLabel
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetConfidenceLevel() string {
	if x != nil {
		return x.ConfidenceLevel
	}
	return ""
}

type CreateAssetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId   string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	AssetTypeCode   string                 `protobuf:"bytes,2,opt,name=asset_type_code,json=assetTypeCode,proto3" json:"asset_type_code,omitempty"`
	AssetName       string                 `protobuf:"bytes,3,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	OwnershipStatus string                 `protobuf:"bytes,4,opt,name=ownership_status,json=ownershipStatus,proto3" json:"ownership_status,omitempty"`
	AcquisitionYear int32                  `protobuf:"varint,5,opt,name=acquisition_year,json=acquisitionYear,proto3" json:"acquisition_year,omitempty"`
	EstimatedValue  string                 `protobuf:"bytes,6,opt,name=estimated_value,json=estimatedValue,proto3" json:"estimated_value,omitempty"`
	ValuationMethod string                 `protobuf:"bytes,7,opt,name=valuation_method,json=valuationMethod,proto3" json:"valuation_method,omitempty"`
	LocationText    string                 `protobuf:"bytes,8,opt,name=location_text,json=locationText,proto3" json:"location_text,omitempty"`
	Encumbered      bool                   `protobuf:"varint,9,opt,name=encumbered,proto3" json:"encumbered,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAssetRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CreateAssetRequest) GetAssetTypeCode() string {
	if x != nil {
		return x.AssetTypeCode
	}
	return ""
}

func (x *CreateAssetRequest) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *CreateAssetRequest) GetOwnershipStatus() string {
	if x != nil {
		return x.OwnershipStatus
	}
	return ""
}

func (x *CreateAssetRequest) GetAcquisitionYear() int32 {
	if x != nil {
		return x.AcquisitionYear
	}
	return 0
}

func (x *CreateAssetRequest) GetEstimatedValue() string {
	if x != nil {
		return x.EstimatedValue
	}
	return ""
}

func (x *CreateAssetRequest) GetValuationMethod() string {
	if x != nil {
		return x.ValuationMethod
	}
	return ""
}

func (x *CreateAssetRequest) GetLocationText() string {
	if x != nil {
		return x.LocationText
	}
	return ""
}

func (x *CreateAssetRequest) GetEncumbered() bool {
	if x != nil {
		return x.Encumbered
	}
	return false
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{8}
}

func (x *ListAssetsRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListAssetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsReply) Reset() {
	*x = ListAssetsReply{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsReply) ProtoMessage() {}

func (x *ListAssetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsReply.ProtoReflect.Descriptor instead.
func (*ListAssetsReply) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{9}
}

func (x *ListAssetsReply) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type CreateLiabilityRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId      string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	CreditorName       string                 `protobuf:"bytes,2,opt,name=creditor_name,json=creditorName,proto3" json:"creditor_name,omitempty"`
	LiabilityType      string                 `protobuf:"bytes,3,opt,name=liability_type,json=liabilityType,proto3" json:"liability_type,omitempty"`
	OutstandingAmount  string                 `protobuf:"bytes,4,opt,name=outstanding_amount,json=outstandingAmount,proto3" json:"outstanding_amount,omitempty"`
	MonthlyInstallment string                 `protobuf:"bytes,5,opt,name=monthly_installment,json=monthlyInstallment,proto3" json:"monthly_installment,omitempty"`
	InterestRate       string                 `protobuf:"bytes,6,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	MaturityDate       string                 `protobuf:"bytes,7,opt,name=maturity_date,json=maturityDate,proto3" json:"maturity_date,omitempty"`
	Source             string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateLiabilityRequest) Reset() {
	*x = CreateLiabilityRequest{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLiabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLiabilityRequest) ProtoMessage() {}

func (x *CreateLiabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLiabilityRequest.ProtoReflect.Descriptor instead.
func (*CreateLiabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{10}
}

func (x *CreateLiabilityRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CreateLiabilityRequest) GetCreditorName() string {
	if x != nil {
		return x.CreditorName
	}
	return ""
}

func (x *CreateLiabilityRequest) GetLiabilityType() string {
	if x != nil {
		return x.LiabilityType
	}
	return ""
}

func (x *CreateLiabilityRequest) GetOutstandingAmount() string {
	if x != nil {
		return x.OutstandingAmount
	}
	return ""
}

func (x *CreateLiabilityRequest) GetMonthlyInstallment() string {
	if x != nil {
		return x.MonthlyInstallment
	}
	return ""
}

func (x *CreateLiabilityRequest) GetInterestRate() string {
	if x != nil {
		return x.InterestRate
	}
	return ""
}

func (x *CreateLiabilityRequest) GetMaturityDate() string {
	if x != nil {
		return x.MaturityDate
	}
	return ""
}

func (x *CreateLiabilityRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListLiabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLiabilitiesRequest) Reset() {
	*x = ListLiabilitiesRequest{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLiabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLiabilitiesRequest) ProtoMessage() {}

func (x *ListLiabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLiabilitiesRequest.ProtoReflect.Descriptor instead.
func (*ListLiabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{11}
}

func (x *ListLiabilitiesRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListLiabilitiesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liabilities   []*Liability           `protobuf:"bytes,1,rep,name=liabilities,proto3" json:"liabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLiabilitiesReply) Reset() {
	*x = ListLiabilitiesReply{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLiabilitiesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLiabilitiesReply) ProtoMessage() {}

func (x *ListLiabilitiesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLiabilitiesReply.ProtoReflect.Descriptor instead.
func (*ListLiabilitiesReply) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{12}
}

func (x *ListLiabilitiesReply) GetLiabilities() []*Liability {
	if x != nil {
		return x.Liabilities
	}
	return nil
}

type UpsertFinancialRatioRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId      string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	RatioCode          string                 `protobuf:"bytes,2,opt,name=ratio_code,json=ratioCode,proto3" json:"ratio_code,omitempty"`
	RatioValue         string                 `protobuf:"bytes,3,opt,name=ratio_value,json=ratioValue,proto3" json:"ratio_value,omitempty"`
	CalculationVersion string                 `protobuf:"bytes,4,opt,name=calculation_version,json=calculationVersion,proto3" json:"calculation_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpsertFinancialRatioRequest) Reset() {
	*x = UpsertFinancialRatioRequest{}
	mi := &file_api_financial_v1_financial_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFinancialRatioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFinancialRatioRequest) ProtoMessage() {}

func (x *UpsertFinancialRatioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_financial_v1_financial_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFinancialRatioRequest.ProtoReflect.Descriptor instead.
func (*UpsertFinancialRatioRequest) Descriptor() ([]byte, []int) {
	return file_api_financial_v1_financial_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertFinancialRatioRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *UpsertFinancialRatioRequest) GetRatioCode() string {
	if x != nil {
		return x.RatioCode
	}
	return ""
}

func (x *UpsertFinancialRatioRequest) GetRatioValue() string {
	if x != nil {
		return x.RatioValue
	}
	return ""
}

func (x *UpsertFinancialRatioRequest) GetCalculationVersion() string {
	if x != nil {
		return x.CalculationVersion
	}
	return ""
}

var File_api_financial_v1_financial_proto protoreflect.FileDescriptor

const file_api_financial_v1_financial_proto_rawDesc = "" +
	"\n" +
	" api/financial/v1/financial.proto\x12\x10api.financial.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x02\n" +
	"\rFinancialFact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x17\n" +
	"\agl_code\x18\x03 \x01(\tR\x06glCode\x12\x1f\n" +
	"\vperiod_type\x18\x04 \x01(\tR\n" +
	"periodType\x12!\n" +
	"\fperiod_label\x18\x05 \x01(\tR\vperiodLabel\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12)\n" +
	"\x10confidence_level\x18\b \x01(\tR\x0fconfidenceLevel\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf4\x02\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12&\n" +
	"\x0fasset_type_code\x18\x03 \x01(\tR\rassetTypeCode\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x04 \x01(\tR\tassetName\x12)\n" +
	"\x10ownership_status\x18\x05 \x01(\tR\x0fownershipStatus\x12)\n" +
	"\x10acquisition_year\x18\x06 \x01(\x05R\x0facquisitionYear\x12'\n" +
	"\x0festimated_value\x18\a \x01(\tR\x0eestimatedValue\x12)\n" +
	"\x10valuation_method\x18\b \x01(\tR\x0fvaluationMethod\x12#\n" +
	"\rlocation_text\x18\t \x01(\tR\flocationText\x12\x1e\n" +
	"\n" +
	"encumbered\x18\n" +
	" \x01(\bR\n" +
	"encumbered\"\xd0\x02\n" +
	"\tLiability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12#\n" +
	"\rcreditor_name\x18\x03 \x01(\tR\fcreditorName\x12%\n" +
	"\x0eliability_type\x18\x04 \x01(\tR\rliabilityType\x12-\n" +
	"\x12outstanding_amount\x18\x05 \x01(\tR\x11outstandingAmount\x12/\n" +
	"\x13monthly_installment\x18\x06 \x01(\tR\x12monthlyInstallment\x12#\n" +
	"\rinterest_rate\x18\a \x01(\tR\finterestRate\x12#\n" +
	"\rmaturity_date\x18\b \x01(\tR\fmaturityDate\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\"\xf9\x01\n" +
	"\x0eFinancialRatio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"ratio_code\x18\x03 \x01(\tR\tratioCode\x12\x1f\n" +
	"\vratio_value\x18\x04 \x01(\tR\n" +
	"ratioValue\x12/\n" +
	"\x13calculation_version\x18\x05 \x01(\tR\x12calculationVersion\x12?\n" +
	"\rcalculated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcalculatedAt\"B\n" +
	"\x19ListFinancialFactsRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"P\n" +
	"\x17ListFinancialFactsReply\x125\n" +
	"\x05facts\x18\x01 \x03(\v2\x1f.api.financial.v1.FinancialFactR\x05facts\"\xfb\x01\n" +
	"\x1aUpsertFinancialFactRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x17\n" +
	"\agl_code\x18\x02 \x01(\tR\x06glCode\x12\x1f\n" +
	"\vperiod_type\x18\x03 \x01(\tR\n" +
	"periodType\x12!\n" +
	"\fperiod_label\x18\x04 \x01(\tR\vperiodLabel\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12)\n" +
	"\x10confidence_level\x18\a \x01(\tR\x0fconfidenceLevel\"\xf1\x02\n" +
	"\x12CreateAssetRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12&\n" +
	"\x0fasset_type_code\x18\x02 \x01(\tR\rassetTypeCode\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x03 \x01(\tR\tassetName\x12)\n" +
	"\x10ownership_status\x18\x04 \x01(\tR\x0fownershipStatus\x12)\n" +
	"\x10acquisition_year\x18\x05 \x01(\x05R\x0facquisitionYear\x12'\n" +
	"\x0festimated_value\x18\x06 \x01(\tR\x0eestimatedValue\x12)\n" +
	"\x10valuation_method\x18\a \x01(\tR\x0fvaluationMethod\x12#\n" +
	"\rlocation_text\x18\b \x01(\tR\flocationText\x12\x1e\n" +
	"\n" +
	"encumbered\x18\t \x01(\bR\n" +
	"encumbered\":\n" +
	"\x11ListAssetsRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"B\n" +
	"\x0fListAssetsReply\x12/\n" +
	"\x06assets\x18\x01 \x03(\v2\x17.api.financial.v1.AssetR\x06assets\"\xcd\x02\n" +
	"\x16CreateLiabilityRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12#\n" +
	"\rcreditor_name\x18\x02 \x01(\tR\fcreditorName\x12%\n" +
	"\x0eliability_type\x18\x03 \x01(\tR\rliabilityType\x12-\n" +
	"\x12outstanding_amount\x18\x04 \x01(\tR\x11outstandingAmount\x12/\n" +
	"\x13monthly_installment\x18\x05 \x01(\tR\x12monthlyInstallment\x12#\n" +
	"\rinterest_rate\x18\x06 \x01(\tR\finterestRate\x12#\n" +
	"\rmaturity_date\x18\a \x01(\tR\fmaturityDate\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\"?\n" +
	"\x16ListLiabilitiesRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"U\n" +
	"\x14ListLiabilitiesReply\x12=\n" +
	"\vliabilities\x18\x01 \x03(\v2\x1b.api.financial.v1.LiabilityR\vliabilities\"\xb5\x01\n" +
	"\x1bUpsertFinancialRatioRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"ratio_code\x18\x02 \x01(\tR\tratioCode\x12\x1f\n" +
	"\vratio_value\x18\x03 \x01(\tR\n" +
	"ratioValue\x12/\n" +
	"\x13calculation_version\x18\x04 \x01(\tR\x12calculationVersion2\xc2\b\n" +
	"\tFinancial\x12\xa7\x01\n" +
	"\x12ListFinancialFacts\x12+.api.financial.v1.ListFinancialFactsRequest\x1a).api.financial.v1.ListFinancialFactsReply\"9\x82\xd3\xe4\x93\x023\x121/v1/applications/{application_id}/financial-facts\x12\xa2\x01\n" +
	"\x13UpsertFinancialFact\x12,.api.financial.v1.UpsertFinancialFactRequest\x1a\x1f.api.financial.v1.FinancialFact\"<\x82\xd3\xe4\x93\x026:\x01*\"1/v1/applications/{application_id}/financial-facts\x12\x81\x01\n" +
	"\vCreateAsset\x12$.api.financial.v1.CreateAssetRequest\x1a\x17.api.financial.v1.Asset\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/applications/{application_id}/assets\x12\x86\x01\n" +
	"\n" +
	"ListAssets\x12#.api.financial.v1.ListAssetsRequest\x1a!.api.financial.v1.ListAssetsReply\"0\x82\xd3\xe4\x93\x02*\x12(/v1/applications/{application_id}/assets\x12\x92\x01\n" +
	"\x0fCreateLiability\x12(.api.financial.v1.CreateLiabilityRequest\x1a\x1b.api.financial.v1.Liability\"8\x82\xd3\xe4\x93\x022:\x01*\"-/v1/applications/{application_id}/liabilities\x12\x9a\x01\n" +
	"\x0fListLiabilities\x12(.api.financial.v1.ListLiabilitiesRequest\x1a&.api.financial.v1.ListLiabilitiesReply\"5\x82\xd3\xe4\x93\x02/\x12-/v1/applications/{application_id}/liabilities\x12\xa6\x01\n" +
	"\x14UpsertFinancialRatio\x12-.api.financial.v1.UpsertFinancialRatioRequest\x1a .api.financial.v1.FinancialRatio\"=\x82\xd3\xe4\x93\x027:\x01*\"2/v1/applications/{application_id}/financial-ratiosBB\n" +
	"\x10api.financial.v1P\x01Z,credit-analytics-backend/api/financial/v1;v1b\x06proto3"

var (
	file_api_financial_v1_financial_proto_rawDescOnce sync.Once
	file_api_financial_v1_financial_proto_rawDescData []byte
)

func file_api_financial_v1_financial_proto_rawDescGZIP() []byte {
	file_api_financial_v1_financial_proto_rawDescOnce.Do(func() {
		file_api_financial_v1_financial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_financial_v1_financial_proto_rawDesc), len(file_api_financial_v1_financial_proto_rawDesc)))
	})
	return file_api_financial_v1_financial_proto_rawDescData
}

var file_api_financial_v1_financial_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_financial_v1_financial_proto_goTypes = []any{
	(*FinancialFact)(nil),               // 0: api.financial.v1.FinancialFact
	(*Asset)(nil),                       // 1: api.financial.v1.Asset
	(*Liability)(nil),                   // 2: api.financial.v1.Liability
	(*FinancialRatio)(nil),              // 3: api.financial.v1.FinancialRatio
	(*ListFinancialFactsRequest)(nil),   // 4: api.financial.v1.ListFinancialFactsRequest
	(*ListFinancialFactsReply)(nil),     // 5: api.financial.v1.ListFinancialFactsReply
	(*UpsertFinancialFactRequest)(nil),  // 6: api.financial.v1.UpsertFinancialFactRequest
	(*CreateAssetRequest)(nil),          // 7: api.financial.v1.CreateAssetRequest
	(*ListAssetsRequest)(nil),           // 8: api.financial.v1.ListAssetsRequest
	(*ListAssetsReply)(nil),             // 9: api.financial.v1.ListAssetsReply
	(*CreateLiabilityRequest)(nil),      // 10: api.financial.v1.CreateLiabilityRequest
	(*ListLiabilitiesRequest)(nil),      // 11: api.financial.v1.ListLiabilitiesRequest
	(*ListLiabilitiesReply)(nil),        // 12: api.financial.v1.ListLiabilitiesReply
	(*UpsertFinancialRatioRequest)(nil), // 13: api.financial.v1.UpsertFinancialRatioRequest
	(*timestamppb.Timestamp)(nil),       // 14: google.protobuf.Timestamp
}
var file_api_financial_v1_financial_proto_depIdxs = []int32{
	14, // 0: api.financial.v1.FinancialFact.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: api.financial.v1.FinancialRatio.calculated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: api.financial.v1.ListFinancialFactsReply.facts:type_name -> api.financial.v1.FinancialFact
	1,  // 3: api.financial.v1.ListAssetsReply.assets:type_name -> api.financial.v1.Asset
	2,  // 4: api.financial.v1.ListLiabilitiesReply.liabilities:type_name -> api.financial.v1.Liability
	4,  // 5: api.financial.v1.Financial.ListFinancialFacts:input_type -> api.financial.v1.ListFinancialFactsRequest
	6,  // 6: api.financial.v1.Financial.UpsertFinancialFact:input_type -> api.financial.v1.UpsertFinancialFactRequest
	7,  // 7: api.financial.v1.Financial.CreateAsset:input_type -> api.financial.v1.CreateAssetRequest
	8,  // 8: api.financial.v1.Financial.ListAssets:input_type -> api.financial.v1.ListAssetsRequest
	10, // 9: api.financial.v1.Financial.CreateLiability:input_type -> api.financial.v1.CreateLiabilityRequest
	11, // 10: api.financial.v1.Financial.ListLiabilities:input_type -> api.financial.v1.ListLiabilitiesRequest
	13, // 11: api.financial.v1.Financial.UpsertFinancialRatio:input_type -> api.financial.v1.UpsertFinancialRatioRequest
	5,  // 12: api.financial.v1.Financial.ListFinancialFacts:output_type -> api.financial.v1.ListFinancialFactsReply
	0,  // 13: api.financial.v1.Financial.UpsertFinancialFact:output_type -> api.financial.v1.FinancialFact
	1,  // 14: api.financial.v1.Financial.CreateAsset:output_type -> api.financial.v1.Asset
	9,  // 15: api.financial.v1.Financial.ListAssets:output_type -> api.financial.v1.ListAssetsReply
	2,  // 16: api.financial.v1.Financial.CreateLiability:output_type -> api.financial.v1.Liability
	12, // 17: api.financial.v1.Financial.ListLiabilities:output_type -> api.financial.v1.ListLiabilitiesReply
	3,  // 18: api.financial.v1.Financial.UpsertFinancialRatio:output_type -> api.financial.v1.FinancialRatio
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_financial_v1_financial_proto_init() }
func file_api_financial_v1_financial_proto_init() {
	if File_api_financial_v1_financial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_financial_v1_financial_proto_rawDesc), len(file_api_financial_v1_financial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_financial_v1_financial_proto_goTypes,
		DependencyIndexes: file_api_financial_v1_financial_proto_depIdxs,
		MessageInfos:      file_api_financial_v1_financial_proto_msgTypes,
	}.Build()
	File_api_financial_v1_financial_proto = out.File
	file_api_financial_v1_financial_proto_goTypes = nil
	file_api_financial_v1_financial_proto_depIdxs = nil
}
