// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: api/financial/v1/financial.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFinancialCreateAsset = "/api.financial.v1.Financial/CreateAsset"
const OperationFinancialCreateLiability = "/api.financial.v1.Financial/CreateLiability"
const OperationFinancialListAssets = "/api.financial.v1.Financial/ListAssets"
const OperationFinancialListFinancialFacts = "/api.financial.v1.Financial/ListFinancialFacts"
const OperationFinancialListLiabilities = "/api.financial.v1.Financial/ListLiabilities"
const OperationFinancialUpsertFinancialFact = "/api.financial.v1.Financial/UpsertFinancialFact"
const OperationFinancialUpsertFinancialRatio = "/api.financial.v1.Financial/UpsertFinancialRatio"

type FinancialHTTPServer interface {
	CreateAsset(context.Context, *CreateAssetRequest) (*Asset, error)
	CreateLiability(context.Context, *CreateLiabilityRequest) (*Liability, error)
	ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsReply, error)
	ListFinancialFacts(context.Context, *ListFinancialFactsRequest) (*ListFinancialFactsReply, error)
	ListLiabilities(context.Context, *ListLiabilitiesRequest) (*ListLiabilitiesReply, error)
	UpsertFinancialFact(context.Context, *UpsertFinancialFactRequest) (*FinancialFact, error)
	UpsertFinancialRatio(context.Context, *UpsertFinancialRatioRequest) (*FinancialRatio, error)
}

func RegisterFinancialHTTPServer(s *http.Server, srv FinancialHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/applications/{application_id}/financial-facts", _Financial_ListFinancialFacts0_HTTP_Handler(srv))
	r.POST("/v1/applications/{application_id}/financial-facts", _Financial_UpsertFinancialFact0_HTTP_Handler(srv))
	r.POST("/v1/applications/{application_id}/assets", _Financial_CreateAsset0_HTTP_Handler(srv))
	r.GET("/v1/applications/{application_id}/assets", _Financial_ListAssets0_HTTP_Handler(srv))
	r.POST("/v1/applications/{application_id}/liabilities", _Financial_CreateLiability0_HTTP_Handler(srv))
	r.GET("/v1/applications/{application_id}/liabilities", _Financial_ListLiabilities0_HTTP_Handler(srv))
	r.POST("/v1/applications/{application_id}/financial-ratios", _Financial_UpsertFinancialRatio0_HTTP_Handler(srv))
}

func _Financial_ListFinancialFacts0_HTTP_Handler(srv FinancialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFinancialFactsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialListFinancialFacts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFinancialFacts(ctx, req.(*ListFinancialFactsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFinancialFactsReply)
		return ctx.Result(200, reply)
	}
}

func _Financial_UpsertFinancialFact0_HTTP_Handler(srv FinancialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertFinancialFactRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialUpsertFinancialFact)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertFinancialFact(ctx, req.(*UpsertFinancialFactRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FinancialFact)
		return ctx.Result(200, reply)
	}
}

func _Financial_CreateAsset0_HTTP_Handler(srv FinancialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAssetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialCreateAsset)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAsset(ctx, req.(*CreateAssetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Asset)
		return ctx.Result(200, reply)
	}
}

func _Financial_ListAssets0_HTTP_Handler(srv FinancialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAssetsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialListAssets)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAssets(ctx, req.(*ListAssetsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAssetsReply)
		return ctx.Result(200, reply)
	}
}

func _Financial_CreateLiability0_HTTP_Handler(srv FinancialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateLiabilityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialCreateLiability)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateLiability(ctx, req.(*CreateLiabilityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Liability)
		return ctx.Result(200, reply)
	}
}

func _Financial_ListLiabilities0_HTTP_Handler(srv FinancialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLiabilitiesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialListLiabilities)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLiabilities(ctx, req.(*ListLiabilitiesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLiabilitiesReply)
		return ctx.Result(200, reply)
	}
}

func _Financial_UpsertFinancialRatio0_HTTP_Handler(srv FinancialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertFinancialRatioRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialUpsertFinancialRatio)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertFinancialRatio(ctx, req.(*UpsertFinancialRatioRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FinancialRatio)
		return ctx.Result(200, reply)
	}
}

type FinancialHTTPClient interface {
	CreateAsset(ctx context.Context, req *CreateAssetRequest, opts ...http.CallOption) (rsp *Asset, err error)
	CreateLiability(ctx context.Context, req *CreateLiabilityRequest, opts ...http.CallOption) (rsp *Liability, err error)
	ListAssets(ctx context.Context, req *ListAssetsRequest, opts ...http.CallOption) (rsp *ListAssetsReply, err error)
	ListFinancialFacts(ctx context.Context, req *ListFinancialFactsRequest, opts ...http.CallOption) (rsp *ListFinancialFactsReply, err error)
	ListLiabilities(ctx context.Context, req *ListLiabilitiesRequest, opts ...http.CallOption) (rsp *ListLiabilitiesReply, err error)
	UpsertFinancialFact(ctx context.Context, req *UpsertFinancialFactRequest, opts ...http.CallOption) (rsp *FinancialFact, err error)
	UpsertFinancialRatio(ctx context.Context, req *UpsertFinancialRatioRequest, opts ...http.CallOption) (rsp *FinancialRatio, err error)
}

type FinancialHTTPClientImpl struct {
	cc *http.Client
}

func NewFinancialHTTPClient(client *http.Client) FinancialHTTPClient {
	return &FinancialHTTPClientImpl{client}
}

func (c *FinancialHTTPClientImpl) CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...http.CallOption) (*Asset, error) {
	var out Asset
	pattern := "/v1/applications/{application_id}/assets"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFinancialCreateAsset))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialHTTPClientImpl) CreateLiability(ctx context.Context, in *CreateLiabilityRequest, opts ...http.CallOption) (*Liability, error) {
	var out Liability
	pattern := "/v1/applications/{application_id}/liabilities"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFinancialCreateLiability))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialHTTPClientImpl) ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...http.CallOption) (*ListAssetsReply, error) {
	var out ListAssetsReply
	pattern := "/v1/applications/{application_id}/assets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFinancialListAssets))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialHTTPClientImpl) ListFinancialFacts(ctx context.Context, in *ListFinancialFactsRequest, opts ...http.CallOption) (*ListFinancialFactsReply, error) {
	var out ListFinancialFactsReply
	pattern := "/v1/applications/{application_id}/financial-facts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFinancialListFinancialFacts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialHTTPClientImpl) ListLiabilities(ctx context.Context, in *ListLiabilitiesRequest, opts ...http.CallOption) (*ListLiabilitiesReply, error) {
	var out ListLiabilitiesReply
	pattern := "/v1/applications/{application_id}/liabilities"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFinancialListLiabilities))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialHTTPClientImpl) UpsertFinancialFact(ctx context.Context, in *UpsertFinancialFactRequest, opts ...http.CallOption) (*FinancialFact, error) {
	var out FinancialFact
	pattern := "/v1/applications/{application_id}/financial-facts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFinancialUpsertFinancialFact))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialHTTPClientImpl) UpsertFinancialRatio(ctx context.Context, in *UpsertFinancialRatioRequest, opts ...http.CallOption) (*FinancialRatio, error) {
	var out FinancialRatio
	pattern := "/v1/applications/{application_id}/financial-ratios"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFinancialUpsertFinancialRatio))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
